DECLARE @TRACEFILE NVARCHAR(100)

SELECT
	@TRACEFILE = PATH
FROM 
	SYS.TRACES 
WHERE 
	IS_DEFAULT = 1

SELECT
    T.STARTTIME,
    TC.NAME AS EVENTCATEGORY,
    TE.NAME AS EVENTNAME,
 
    CASE T.EVENTSUBCLASS
        WHEN 0 THEN '0 - BEGIN'
        WHEN 1 THEN '1 - COMMIT'
        WHEN 2 THEN '2 - STARTED'
        ELSE CONVERT(VARCHAR(20), T.EVENTSUBCLASS)
    END AS EVENTSUBCLASS,
 
    T.SPID,
    T.DATABASENAME,
    T.OBJECTNAME,
    T.OBJECTTYPE,
    TSV.SUBCLASS_NAME AS OBJECTTYPENAME,
    T.LOGINNAME,
    T.HOSTNAME,
    T.APPLICATIONNAME,
    T.TEXTDATA
FROM SYS.FN_TRACE_GETTABLE(@TRACEFILE, DEFAULT) AS T
LEFT JOIN SYS.TRACE_EVENTS AS TE
    ON TE.TRACE_EVENT_ID = T.EVENTCLASS
LEFT JOIN SYS.TRACE_CATEGORIES AS TC
    ON TC.CATEGORY_ID = TE.CATEGORY_ID
LEFT JOIN SYS.TRACE_COLUMNS AS TRC
    ON TRC.NAME = 'OBJECTTYPE'
LEFT JOIN SYS.TRACE_SUBCLASS_VALUES AS TSV
    ON TSV.TRACE_EVENT_ID = T.EVENTCLASS
   AND TSV.TRACE_COLUMN_ID = TRC.TRACE_COLUMN_ID
   AND TSV.SUBCLASS_VALUE = T.OBJECTTYPE
--WHERE
--	T.DATABASENAME = 'SOMA'
--	AND TC.NAME = 'Objects'
ORDER BY
    T.STARTTIME;