--SELECT *  
--INTO CAD_DEVP_RIACHUELO_CAR11
--FROM OPENQUERY (CS2,'        
--SELECT DISTINCT A.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', A.* FROM PARC_GERAL A
--JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--WHERE C.ID_CARTEIRA=32
--AND C.STATUS IN (0,4,3,5)')
--GO

SELECT *  
INTO CAD_DEVP_RIACHUELO_CAR11
FROM OPENQUERY (CS2,'        
SELECT DISTINCT A.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', A.* FROM PARC_GERAL A
WHERE C.ID_CARTEIRA=32
AND C.STATUS IN (0,4,3,5)')
GO

SELECT A.* FROM CAD_DEVP A
JOIN AUX_DEVF B ON B.CONTRATO_FIN = A.CONTRATO_FIN
JOIN CAD_DEVP_CARREFOUR_TESTE C ON C.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_FIN

SELECT * FROM CAD_DEVF_CARREFOUR_TESTE_2

--SELECT DISTINCT B.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', B.NUM_PREST AS ''CODID_PARC'', A.* FROM PARC_GERAL A
--JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--JOIN PARC_GERAL_SEM_PARAR_RECUPERA B ON A.NUM_PARC = B.NUM_PARC AND A.ID_CONTR = B.ID_CONTR
--WHERE C.ID_CARTEIRA=32
--AND C.STATUS IN (0,4,3,5)

--SELECT * FROM CAD_DEVP_RIACHUELO_CAR11
--DELETE FROM CAD_DEVP WHERE CONTRATO_FIN = '44487603ID'

--DROP TABLE CAD_DEVP_RIACHUELO_CAR11

SELECT
	B.CONTRATOFIXO AS CONTRATO_FIN,
	--A.NUM_PARC2 AS PARCELA_PARC,
	'P' AS TIPO_PARC,
	A.VENC AS VENC_PARC,
	A.VALOR AS VALOR_PARC,
	status as COD_STPA,
	1 as PLANO_PARC
	--,CODID_PARC
	INTO CAD_DEVP_RIACHUELO_CAR11_AUX
	FROM CAD_DEVP_RIACHUELO_CAR11 A
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
	WHERE B.DATA_INCLUSAO = '20240910'
	GO

with cte
as
(
select
*,
row_number() over (partition by contrato_fin order by venc_parc) as NUm_parc2
from CAD_DEVP_RIACHUELO_CAR11_AUX
)
select *
into CAD_DEVP_RIACHUELO_CAR11_INSERT
from cte
GO

	UPDATE CAD_DEVP_RIACHUELO_CAR11_INSERT SET cod_stpa = 7  WHERE cod_stpa = 0
	GO
	UPDATE CAD_DEVP_RIACHUELO_CAR11_INSERT SET cod_stpa = 16 WHERE cod_stpa = 2
	GO
	UPDATE CAD_DEVP_RIACHUELO_CAR11_INSERT SET cod_stpa = 0  WHERE cod_stpa IN (1,3)
	GO
	UPDATE CAD_DEVP_RIACHUELO_CAR11_INSERT SET cod_stpa = 14 WHERE cod_stpa = 5
	GO

INSERT INTO CAD_DEVP (CONTRATO_FIN, PARCELA_PARC, TIPO_PARC, VENC_PARC, VALOR_PARC, COD_STPA, PLANO_PARC) --, CODID_PARC)
	SELECT
	A.CONTRATO_FIN,
	NUM_PARC2 AS PARCELA_PARC,
	A.TIPO_PARC,
	A.VENC_PARC,
	A.VALOR_PARC,
	A.COD_STPA,
	A.PLANO_PARC
	--,A.CODID_PARC
	FROM CAD_DEVP_RIACHUELO_CAR11_INSERT A
	LEFT JOIN CAD_DEVP B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND NUM_PARC2 = PARCELA_PARC AND A.TIPO_PARC = B.TIPO_PARC
	WHERE B.CONTRATO_FIN IS NULL
	GO