DELETE A FROM AUX_DEVF A 
JOIN CAD_IDCONTRATO_BKP_SEMPARAR_20240825 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

DELETE A FROM CAD_ACOP A 
JOIN CAD_IDCONTRATO_BKP_SEMPARAR_20240825 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

DELETE A FROM CAD_ACO A 
JOIN CAD_IDCONTRATO_BKP_SEMPARAR_20240825 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

DELETE A FROM CAD_ACO A 
JOIN CAD_IDCONTRATO_BKP_SEMPARAR_20240825 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

DELETE A FROM CAD_DEVP A 
JOIN CAD_IDCONTRATO_BKP_SEMPARAR_20240825 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

DELETE A FROM CAD_DEVF A 
JOIN CAD_IDCONTRATO_BKP_SEMPARAR_20240825 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

WHILE 1 = 1
BEGIN
DELETE top(100000) A FROM CAD_DEVT A
JOIN CAD_DEVT_SEMPARAR_CAR8 B ON A.CPF_DEV = B.CPF collate SQL_Latin1_General_CP1_CI_AS

IF @@ROWCOUNT < 100000
	BREAK;
END

WHILE 1 = 1
BEGIN
DELETE TOP(100000) A FROM CAD_DEVE A
JOIN CAD_DEVE_SEMPARAR_CAR8 B ON A.CPF_DEV = B.CPF collate SQL_Latin1_General_CP1_CI_AS
IF @@ROWCOUNT < 100000
	BREAK;
END

WHILE 1 = 1
BEGIN
DELETE TOP(100000) A FROM CAD_DEVMAIL A
JOIN CAD_DEVMAIL_SEMPARAR_CAR8 B ON A.CPF_DEV = B.CPF collate SQL_Latin1_General_CP1_CI_AS

IF @@ROWCOUNT < 100000
	BREAK;
END

DELETE A FROM ACIONA A
JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
JOIN ACIONAMENTOS_SEMPARAR_CAR8 C ON B.CONTRATO_ORIGINAL = C.NUM_CONTRATO collate SQL_Latin1_General_CP1_CI_AS

DROP TABLE ACIONAMENTOS_SEMPARAR_CAR8

DELETE A FROM EVENTO A
JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
JOIN EVENTO_SEMPARAR_CAR8 C ON B.CONTRATO_ORIGINAL = C.NUM_CONTRATO collate SQL_Latin1_General_CP1_CI_AS