--SELECT      (SCHEMA_NAME(t.schema_id) + '.' + t.name) AS 'TableName'
--FROM        sys.tables  t
--WHERE       t.name LIKE '%SEMPARAR_CAR8%'
--ORDER BY    TableName;

DROP TABLE dbo.ACIONAMENTOS_SEMPARAR_CAR8
DROP TABLE dbo.ACORDO_PARCELAS_SEMPARAR_CAR8
DROP TABLE dbo.ACORDO_PARCELAS_SEMPARAR_CAR8_INSERT
DROP TABLE dbo.ACORDO_SEMPARAR_CAR8
DROP TABLE dbo.CAD_DEVE_SEMPARAR_CAR8
DROP TABLE dbo.CAD_DEVF_INSERT_SEMPARAR_CAR8
DROP TABLE dbo.CAD_DEVF_SEMPARAR_CAR8
DROP TABLE dbo.CAD_DEVF_SEMPARAR_CAR8_aux_insert
DROP TABLE dbo.CAD_DEVMAIL_SEMPARAR_CAR8
DROP TABLE dbo.CAD_DEVP_SEMPARAR_CAR8
DROP TABLE dbo.CAD_DEVP_SEMPARAR_CAR8_AUX
DROP TABLE dbo.CAD_DEVP_SEMPARAR_CAR8_INSERT
DROP TABLE dbo.CAD_DEVT_SEMPARAR_CAR8
DROP TABLE dbo.EVENTO_SEMPARAR_CAR8
DROP TABLE dbo.NUMACORDO_SEMPARAR_CAR8
DROP TABLE dbo.TOKEN_SEMPARAR_CAR8