SELECT * 
INTO EVENTO_CARREFOUR
FROM ACIONAMENTOS_CARREFOUR WHERE COD IN (4104,4102)
GO

INSERT INTO EVENTO_CARREFOUR
(
NUM_CONTRATO
,CPF
,ID_CONTR
,SEQ
,ID_TEL
,DATA
,CODIGO
,ID_FUNCIONARIO
,LOGIN
,NOME
,STATUS
,CPF_F
,MOTIVO
,AUTORIZACAO
,DDD
,NUMERO
,COD
,HISTORICO
,COMENTARIO
)
SELECT 
NUM_CONTRATO
,CPF
,ID_CONTR
,SEQ
,ID_TEL
,DATA
,CODIGO
,ID_FUNCIONARIO
,LOGIN
,NOME
,STATUS
,CPF_F
,MOTIVO
,AUTORIZACAO
,DDD
,NUMERO
,COD
,HISTORICO
,COMENTARIO
FROM ACIONAMENTOS_CARREFOUR WHERE COD IN (4104,4102)
GO

DELETE FROM ACIONAMENTOS_RIACHUELO_MIGRACAO_2 WHERE COD IN (4104,4102)
GO

SELECT * FROM EVENTO_RIACHUELO_MIGRACAO WHERE COD IN (4104,4102)

--DROP TABLE EVENTO_CARREFOUR

SELECT * 
INTO EVENTO_CARREFOUR
FROM OPENQUERY (CS2,'
SELECT B.NUM_CONTRATO, B.CPF, A.ID_CONTR, A.SEQ, A.ID_TEL, A.DATA, A.CODIGO,
C.ID_FUNCIONARIO, C.LOGIN, C.NOME, C.STATUS, C.CPF_F,
D.MOTIVO, D.AUTORIZACAO,
E.DDD, E.NUMERO,
F.COD, F.HISTORICO, CONVERT(D.MENSAGEM,CHAR(500)) AS ''MENSAGEM'', CONVERT(A.MENSAGEM,CHAR(500)) AS ''COMENTARIO''
FROM HISTORICO_SISTEMA A
JOIN CONTRATO B ON A.ID_CONTR = B.ID_CONTR
JOIN FUNCIONARIO C ON A.ID_FUNCIONARIO = C.ID_FUNCIONARIO
LEFT JOIN HISTORICO_TEXTO D ON A.ID_CONTR = D.ID_CONTR AND A.SEQ = D.SEQ
LEFT JOIN TELEFONE E ON B.CPF = E.CPF AND A.ID_TEL = E.ID_TEL
JOIN CODIGO F ON A.CODIGO = F.COD
WHERE B.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
AND A.DATA >= ''20240921''
ORDER BY A.DATA;')
GO

SELECT *
INTO EVENTO_CARREFOUR_BKP
FROM EVENTO_CARREFOUR

UPDATE EVENTO_CARREFOUR SET MENSAGEM = COMENTARIO WHERE MENSAGEM IS NULL
GO

--SELECT * FROM EVENTO_RIACHUELO_MIGRACAO_2

--SELECT * FROM EVENTO_RIACHUELO_MIGRACAO DROP TABLE EVENTO_RIACHUELO_MIGRACAO_2

update EVENTO_CARREFOUR set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf), LEN(cpf))
GO

CREATE CLUSTERED INDEX CL_IX ON EVENTO_CARREFOUR ([DATA], NUM_CONTRATO)
GO

WHILE 1 = 1
BEGIN

	DELETE TOP(100000) A FROM SRC.DBO.EVENTO A
	JOIN EVENTO_CARREFOUR C ON A.CONTRATO_FIN = C.NUM_CONTRATO collate SQL_Latin1_General_CP1_CI_AS
	--WHERE C.[DATA] >= '20241201'

	IF @@ROWCOUNT < 100000
		BREAK;

END
GO

SELECT DISTINCT CPF, [DATA], COD, ID_FUNCIONARIO, NUM_CONTRATO, C.COD_TEL, LEFT(HISTORICO,100) AS HISTORICO, LEFT(COMENTARIO,255) AS COMENTARIO, AUTORIZACAO
INTO EVENTO_CARREFOUR_INSERT
FROM EVENTO_CARREFOUR A
OUTER APPLY (SELECT TOP 1 COD_TEL FROM SRC.DBO.CAD_DEVT WHERE DDD = DDD_TEL AND NUMERO COLLATE SQL_Latin1_General_CP1_CI_AS = TEL_TEL) C
--WHERE [DATA] >= '20241201'

INSERT INTO SRC.DBO.EVENTO (CPF_DEV, DATA_EVENTO, COD_EVENTO, COD_RECUP, CONTRATO_FIN, COD_TEL, MOTIVO_EVENTO, OBS, OBS2)
SELECT * FROM EVENTO_CARREFOUR_INSERT