SELECT A.CONTRATO_FIN, TIPO_PARCACO, PARCELA_ACOP, DATA_PGTO, b.data_pagto, VALOR_ACOP, A.NACORDO_ACO
FROM [dbo].[ACORDO_PARCELAS_CARREFOUR_INSERT] A
LEFT JOIN RECIBOCREDOR B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.PARCELA_ACOP = B.PARCELA_PARC AND A.NACORDO_ACO = B.NACORDO_ACO
WHERE COD_STPA = 4
and a.contrato_fin = '66934771943'

SELECT * FROM ACORDO_PARCELAS_CARREFOUR_INSERT
where contrato_fin = '66934771943'

select * from recibocredor
where contrato_fin = '66934771943'

with cte as (
select b.COD_id
,row_number() over (partition by B.CONTRATO_FIN, B.PARCELA_PARC, B.NACORDO_ACO order by cod_id) as seqnum
FROM [dbo].[ACORDO_PARCELAS_CARREFOUR_INSERT] A
JOIN RECIBOCREDOR B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.PARCELA_ACOP = B.PARCELA_PARC AND A.NACORDO_ACO = B.NACORDO_ACO
WHERE COD_STPA = 4
)
select * 
INTO  RECIBOCREDOR_CARREFOUR_AUX
from cte
where seqnum > 1

delete from RECIBOCREDOR
where exists (SELECT 1 FROM RECIBOCREDOR_CARREFOUR_AUX B WHERE RECIBOCREDOR.COD_ID = B.COD_ID)

SELECT A.CONTRATO_FIN, A.COD_CLI, A.CPF_DEV, A.* 
--DELETE A
FROM CAD_DEVF A
JOIN AUX_DEVF B ON A.CONTRATO_FIN = B.CONTRATO_FIN
JOIN CAD_DEVF_CARREFOUR C ON B.CONTRATO_ORIGINAL = C.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS
WHERE COD_CLI NOT IN(84,110) --COD_CLI = 110
AND A.CONTRATO_FIN LIKE '%ID'

SELECT * FROM CAD_DEVF WHERE CPF_DEV = '21394826893'
--49268254ID          