select A.* from cad_devf A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATOFIXO = A.CONTRATO_FIN
WHERE B.DATA_INCLUSAO = '2024-07-11 17:46:59.870'

select * from AUXSRC.DBO.ACORDOS_GETNET 

select * from CAD_STAC

select A.* from cad_ACO A
--update A set status_aco = 0 FROM CAD_ACO A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATOFIXO = A.CONTRATO_FIN
WHERE B.DATA_INCLUSAO = '2024-07-11 17:46:59.870'

select * from CAD_STAC

UPDATE A SET STATCONT_FIN = 1, COBRANCA_FIN = 1 from cad_devf A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATOFIXO = A.CONTRATO_FIN
WHERE B.DATA_INCLUSAO = '2024-07-11 17:46:59.870'

INSERT INTO CAD_IDCONTRATO (CONTRATO_ORIGINAL, CPF_DEV, DATA_INCLUSAO)
SELECT a.CONTRATO_ORIGINAL, CPF, '2024-08-04 21:34:37.247'  FROM AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_2] A
LEFT JOIN CAD_IDCONTRATO B ON A.CONTRATO_ORIGINAL = B.CONTRATO_ORIGINAL COLLATE Latin1_General_CI_AS AND A.CPF = B.CPF_DEV COLLATE Latin1_General_CI_AS
WHERE B.CONTRATO_ORIGINAL IS NULL

select * from CAD_IDCONTRATO
WHERE DATA_INCLUSAO = '2024-07-11 17:46:59.870'

select a.contratofixo 
into AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2]
from CAD_IDCONTRATO a
left join cad_devf b on a.CONTRATOFIXO = b.CONTRATO_FIN
WHERE DATA_INCLUSAO = '2024-08-04 21:34:37.247'
and b.CONTRATO_FIN is null

contrato_fin ok
cpf_dev ok
cod_cli 132
cod_car 1
tipo_fin ?
valor_fin ok
moeda_fin 1

INSERT INTO CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN)
SELECT 
B.CONTRATOFIXO AS CONTRATO_FIN,
B.CPF_DEV,
142 AS COD_CLI,
1 AS COD_CAR,
'P' AS TIPO_FIN,
A.PRINCIPAL_ATUAL AS VALOR_FIN,
1 AS MOEDA_FIN
INTO AUXSRC.DBO.ACORDOS_GETNET_AUX_AUX_2
FROM AUXSRC.DBO.ACORDOS_GETNET_AUX_2 A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
INNER JOIN AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2] C ON B.CONTRATOFIXO = C.CONTRATOFIXO
WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'

SELECT * FROM CAD_IDCONTRATO
WHERE DATA_INCLUSAO = '2024-08-04 21:34:37.247'

insert into CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN)
SELECT CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN
FROM AUXSRC.DBO.ACORDOS_GETNET_AUX_AUX_2 
WHERE ID BETWEEN 10001 AND 11000

INSERT INTO AUX_DEVF (CONTRATO_FIN)
SELECT CONTRATOFIXO FROM CAD_IDCONTRATO WHERE DATA_INCLUSAO = '2024-07-11 17:46:59.870'

INSERT INTO AUX_DEVF (CONTRATO_FIN)
SELECT CONTRATOFIXO FROM AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2]

SELECT TOP 10 * FROM AUX_DEVF
WHERE CONTRATO_FIN IN (SELECT CONTRATOFIXO FROM CAD_IDCONTRATO WHERE DATA_INCLUSAO = '2024-07-11 17:46:59.870')

SELECT TOP 10 * FROM CAD_DEVP

INSERT INTO CAD_DEVP (CONTRATO_FIN, PARCELA_PARC, TIPO_PARC, VENC_PARC, VALOR_PARC)
SELECT
B.CONTRATOFIXO AS CONTRATO_FIN,
A.NUM_PARC AS PARCELA_PARC,
'P' AS TIPO_PARC,
A.VENC AS VENC_PARC,
A.VALOR AS VALOR_PARC
FROM AUXSRC.dbo.CAD_DEVP_GETNET_AUX_2 A
INNER JOIN AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2] B ON B.CONTRATO_ORIGINAL = a.CONTRATO_ORIGINAL

SELECT * FROM AUXSRC.dbo.CAD_DEVP_GETNET

SELECT TOP 100 * FROM CAD_ACOP

select top 10 * from cad_aco

INSERT INTO CAD_ACO (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACO, DTACORDO_ACO, PLANO_ACO, VLRACORDO_ACO, VENC_ACO)
SELECT
CONTRATOFIXO,
1 AS NACORDO_ACO,
NUM_PARC_PRIM AS PARCELA_ACO,
DATA AS DTACORDO_ACO,
NUM_PARCELAS AS PLANO_ACO,
PRINCIPAL AS VLRACORDO_ACO,
VENC_PARC_ABERTO AS VENC_ACO
FROM AUXSRC.DBO.[ACORDOS2_GETNET_2] A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) COLLATE SQL_Latin1_General_CP1_CI_AS
where a.status <> 7

SELECT * FROM CAD_ACOP

INSERT INTO CAD_ACOP (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACOP, TIPO_PARCACO, PLANO_ACOP, VALOR_ACOP, VENC_ACOP, COD_STPA, VLRJUR_ACOP, VLRMUL_ACOP)
SELECT
B.CONTRATO_FIN,
NACORDO_ACO,
NUM_PARC AS PARCELA_ACOP,
'A' AS TIPO_PARCACO,
B.PLANO_ACO AS PLANO_ACOP,
PRINCIPAL_O AS VALOR_ACOP,
VENCIMENTO AS VENC_ACOP,
3 AS COD_STPA,
JUROS_O AS VLRJUR_ACOP,
MULTA_O AS VLRMUL_ACOP
FROM AUXSRC.DBO.ACORDOS_PARCELAS_GETNET_2  A
INNER JOIN CAD_IDCONTRATO C ON C.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) collate SQL_Latin1_General_CP1_CI_AS
INNER JOIN CAD_ACO AS B ON C.CONTRATOFIXO = B.CONTRATO_FIN

SELECT * FROM CAD_ACOP
WHERE COD_STPA <> 0

SELECT * FROM AUXSRC.DBO.ACORDOS_PARCELAS_GETNET

select * from CAD_STPA

SELECT * FROM AUXSRC.DBO.ACIONAMENTOS_GETNET
WHERE ID_FUNCIONARIO NOT IN (2134,2135,2140)
AND COD NOT IN (11,129,402,1121,1883,6017)

--INSERT INTO CAD_IDCONTRATO(CONTRATO_ORIGINAL, CPF_DEV, DATA_INCLUSAO)
SELECT  
convert(varchar,A.ID_CONTR),
A.CPF COLLATE SQL_Latin1_General_CP1_CI_AS,
'2024-07-11 17:46:59.870'
FROM AUXSRC.DBO.ACIONAMENTOS_GETNET A
WHERE NOT EXISTS (SELECT * FROM CAD_IDCONTRATO B WHERE B.CONTRATO_ORIGINAL = convert(varchar,A.ID_CONTR) AND B.CPF_DEV = A.CPF COLLATE SQL_Latin1_General_CP1_CI_AS)

WITH CTE AS
(
SELECT *, ROW_NUMBER() over (partition by CONTRATO_ORIGINAL, CPF_DEV order by IDCONTRATO_FIN) as seqnum
FROM CAD_IDCONTRATO WHERE DATA_INCLUSAO = '2024-07-11 17:46:59.870'
)
DELETE FROM CTE
WHERE SEQNUM > 1


INSERT INTO ACIONA(
CONTRATO_FIN
,DATA_ACIONA
,COD_ACIONAMENTO
,COD_RECUP
,DDD_TEL
,TEL_TEL
)
SELECT
B.CONTRATOFIXO AS CONTRATO_FIN
,DATA AS DATA_ACIONA
,COD AS COD_ACIONAMENTO
,ID_FUNCIONARIO AS COD_RECUP
,DDD AS DDD_TEL
,NUMERO AS TEL_TEL
FROM AUXSRC.DBO.ACIONAMENTOS_GETNET A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = CONVERT(varchar,A.ID_CONTR)
WHERE --ID_FUNCIONARIO NOT IN (2134,2135,2140) AND
COD NOT IN (111)

SELECT B.CONTRATOFIXO AS CONTRATO_FIN, A.*
INTO ACIONAMENTOS2_GETNET_2
FROM [ACIONAMENTOS2_GETNET_AUX_2] A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = a.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS
where  b.DATA_INCLUSAO = '2024-08-04 21:34:37.247'


SELECT *
--DELETE
 from ACIONA
where CONTRATO_FIN IN
(
SELECT CONTRATOFIXO FROM CAD_IDCONTRATO WHERE DATA_INCLUSAO = '2024-07-11 17:46:59.870'
)

select top 1000 * from aciona where data_aciona >= '20240712'

select * from cad_acionamento

SELECT * FROM ACIONA

select * from cad_idcontrato where idcontrato_fin in (42304441,41843878)