select A.* from SRC.[dbo].[ACIONAMENTOS_GETNET_AUX_2] A
JOIN SRC.dbo.CAD_IDCONTRATO B ON A.CONTRATO_ORIGINAL = B.CONTRATO_ORIGINAL collate Latin1_General_CI_AS

INSERT INTO ACIONA(
CONTRATO_FIN
,DATA_ACIONA
,COD_ACIONAMENTO
,COD_RECUP
,DDD_TEL
,TEL_TEL
,AGENDA_ACIONA
)
SELECT DISTINCT
B.CONTRATOFIXO AS CONTRATO_FIN
,DATA AS DATA_ACIONA
,COD AS COD_ACIONAMENTO
,ID_FUNCIONARIO AS COD_RECUP
,LEFT(DDD,3) AS DDD_TEL
,RIGHT(NUMERO,9) AS TEL_TEL
,COMENTARIO
FROM SRC.[dbo].ACIONAMENTOS_GETNET_SINQIA A
JOIN SRC.dbo.CAD_IDCONTRATO B ON A.NUM_CONTRATO = B.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
--WHERE --ID_FUNCIONARIO NOT IN (2134,2135,2140) AND
--COD NOT IN (111)

SELECT * FROM CAD_IDCONTRATO WHERE DATA_INCLUSAO = '20240903'

DELETE FROM CAD_IDCONTRATO WHERE IDCONTRATO_FIN ='44487603'

SELECT * FROM src.DBO.[ACIONAMENTOS_GETNET_AUX_2]
WHERE 

select distinct contrato_original, id_contr 
--into CONTRATO_ORIGINAL_GETNET_2
from AUXSRC.dbo.CAD_DEVP_GETNET_AUX_aux_2

SELECT * FROM [dbo].[CADDEV_2_GETNET_2]

UPDATE A SET COD_STPA = 3 FROM CAD_DEVP A
JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
JOIN ACORDO_GETNET_SINQIA C ON B.CONTRATO_ORIGINAL = CONVERT(varchar,C.CONTRATO_ORIGINAL) COLLATE SQL_Latin1_General_CP1_CI_AS
WHERE C.STATUS = 0