INSERT INTO CAD_DEVT (CPF_DEV,DDD_TEL, TEL_TEL, PERC_TEL, COD_TIPO, COD_TEL)
select distinct cpf, ddd, RIGHT(numero,10), COALESCE(SCORE,0), TIPO
,(row_number() over (partition by cpf order by cpf)) as seqnum
from
Auxsrc.[dbo].[CADDEVT4_GETNET_2] a inner join CAD_IDCONTRATO B ON A.CPF collate SQL_Latin1_General_CP1_CI_AS = B.CPF_DEV
left join cad_devt c on b.cpf_dev = c.cpf_dev
WHERE B.DATA_INCLUSAO = '20240813' and c.cpf_dev is null

	update Auxsrc.[dbo].[CADDEVT4_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))

	INSERT INTO CAD_DEVmail (CPF_DEV,desc_devmail, PERC_mail, COD_TIPO, COD_devmail)
select distinct cpf, email, COALESCE(SCORE,0), TIPO
,(row_number() over (partition by cpf order by cpf)) as seqnum
from
Auxsrc.[dbo].[CADDEVE4_GETNET_2] a inner join CAD_IDCONTRATO B ON A.CPF collate SQL_Latin1_General_CP1_CI_AS = B.CPF_DEV
left join cad_devmail c on b.cpf_dev = c.cpf_dev
WHERE B.DATA_INCLUSAO = '20240813' and c.cpf_dev is null

	update Auxsrc.[dbo].[CADDEVE4_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))

	INSERT INTO CAD_DEVe (CPF_DEV,RUA_END,NUM_END, COMPL_END, BAIRRO_END, CIDADE_END, COD_UF, CEP_END, PERC_end, COD_TIPO, COD_end)
select distinct CPF
,left(RUA,65)
,left(NUMERO,6)
,left(COMPL,30)
,left(BAIRRO,30)
,CIDADE
,d.COD_UF
,left(CEP,8), COALESCE(SCORE,0), TIPO
,(row_number() over (partition by cpf order by cpf)) as seqnum
from
Auxsrc.[dbo].[CADDEVEND4_GETNET_2] a inner join CAD_IDCONTRATO B ON A.CPF collate SQL_Latin1_General_CP1_CI_AS = B.CPF_DEV
left join cad_deve c on b.cpf_dev = c.cpf_dev
inner join cad_uf d on d.DESC_UF = estado collate SQL_Latin1_General_CP1_CI_AS
WHERE B.DATA_INCLUSAO = '20240813' and c.cpf_dev is null

	update Auxsrc.[dbo].[CADDEVEND4_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))
	


SELECT A.CPF_DEV FROM CAD_DEV A INNER JOIN CAD_IDCONTRATO B ON A.CPF_DEV = B.CPF_DEV
WHERE B.DATA_INCLUSAO = '20240813'

SELECT A.*
INTO CAD_DEV_AJUSTE_ZERO_GETNET2
FROM CAD_DEV A INNER JOIN CAD_IDCONTRATO B ON A.CPF_DEV = B.CPF_DEV
WHERE B.DATA_INCLUSAO = '20240813' AND LEFT(A.CPF_DEV,1) = '0'

DELETE FROM CAD_DEV WHERE CPF_DEV IN (SELECT CPF_DEV FROM CAD_DEV_AJUSTE_ZERO_GETNET2)

SELECT * 
INTO CAD_DEV_AJUSTE_ZERO_AUX_GETNET2
FROM CAD_DEV_AJUSTE_ZERO_GETNET2

INSERT INTO CAD_DEV(
CPF_DEV
,NOME_DEV
,NASC_DEV
,RG_DEV
,EXP_DEV
,ORG_DEV
,MAE_DEV
,PAI_DEV
,CONJNOME_DEV
,CONJCPF_DEV
,PROFISSAO_DEV
,RENDA_DEV
,COD_SEXO
,COD_ESTCIV
,COD_TIPESS
,NAC_DEV
,EMAIL_DEV
,RESID_DEV
,OCUPA_DEV
,TEMPORESID_DEV
,TPDOC_DEV
,NATURA_DEV
,COD_UF
,CPF_AUX
,EMPRESA_DEV
,DDD_DEV
,DTNASC_DEV
,VIRCOBWEBENVIO_DEV
,ESCOLARIDADE_DEV
,DTSALARIO_DEV
,DTENVIODEBT_DEV
,VIRCOBWEBSENHA_DEV
,NOME_SOCIAL
)
SELECT
CPF_DEV
,NOME_DEV
,NASC_DEV
,RG_DEV
,EXP_DEV
,ORG_DEV
,MAE_DEV
,PAI_DEV
,CONJNOME_DEV
,CONJCPF_DEV
,PROFISSAO_DEV
,RENDA_DEV
,COD_SEXO
,COD_ESTCIV
,COD_TIPESS
,NAC_DEV
,EMAIL_DEV
,RESID_DEV
,OCUPA_DEV
,TEMPORESID_DEV
,TPDOC_DEV
,NATURA_DEV
,COD_UF
,CPF_AUX
,EMPRESA_DEV
,DDD_DEV
,DTNASC_DEV
,VIRCOBWEBENVIO_DEV
,ESCOLARIDADE_DEV
,DTSALARIO_DEV
,DTENVIODEBT_DEV
,VIRCOBWEBSENHA_DEV
,NOME_SOCIAL
FROM CAD_DEV_AJUSTE_ZERO_AUX_GETNET2 

DELETE FROM CAD_DEV_AJUSTE_ZERO_AUX_GETNET2 WHERE CPF_DEV IN (
SELECT CPF_DEV FROM CAD_DEV WHERE CPF_DEV IN (SELECT CPF_DEV FROM CAD_DEV_AJUSTE_ZERO_AUX_GETNET2))

update CAD_IDCONTRATO set cpf_DEV = SUBSTRING(cpf_DEV, PATINDEX('%[^0]%', cpf_DEV+'.'), LEN(cpf_DEV)) WHERE DATA_INCLUSAO = '20240813'

	update CAD_DEV_AJUSTE_ZERO_AUX_GETNET2 set cpf_DEV = SUBSTRING(cpf_DEV, PATINDEX('%[^0]%', cpf_DEV+'.'), LEN(cpf_DEV))
	update AUXSRC.DBO.[CADDEVEND3_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))
	update AUXSRC.DBO.[CADDEVT3_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))
	update AUXSRC.DBO.[CADDEVE3_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))