--SP_HELPTEXT STPCAD_ID

SELECT CONTRATOFIXO 
INTO ACORDO_RIACHUELO_MIGRACAO_2_CONTRATOFIN
FROM ACORDO_RIACHUELO_MIGRACAO_2 A
	JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS

CREATE CLUSTERED INDEX CL_IX ON ACORDO_RIACHUELO_MIGRACAO_2_CONTRATOFIN(CONTRATOFIXO)
GO

DECLARE @ID INT
WHILE 1 =1
BEGIN
    --DECLARE @ID INT
	EXEC STPCAD_ID

	SELECT @ID = MAX(ID) FROM CAD_ID

	UPDATE TOP(1) A SET A.numacocon_aco = @ID FROM SRC.DBO.CAD_ACO A JOIN ACORDO_RIACHUELO_MIGRACAO_2_CONTRATOFIN B ON A.CONTRATO_FIN = B.CONTRATOFIXO
	--JOIN AUXSRC.DBO.ACORDO_RIACHUELO_MIGRACAO_CONTRATOFIN C ON B.CONTRATO_ORIGINAL = C.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS
	WHERE numacocon_aco IS NULL

	IF @@ROWCOUNT = 0
		BREAK;
END

--SELECT * FROM AUX_REMESSA_TOKEN
--SEM_PARAR_RECUPERA_CONTRATO

--SELECT * FROM AUX_ACORDO_SEM_PARAR_RECUPERA

SELECT *  
INTO AUX_ACORDO_SEM_PARAR_RECUPERA
FROM OPENQUERY (CS2,'        
SELECT DISTINCT A.* FROM ACORDO_SEM_PARAR_RECUPERA A
JOIN ACORDO B ON A.ID_ACORDO = B.ID_ACORDO
JOIN CONTRATO C ON C.ID_CONTR = B.ID_CONTR
WHERE C.ID_CARTEIRA IN (20,22,24,25,26)
AND C.STATUS IN (0,4,3,5)')
GO

SELECT *  
INTO AUX_REMESSA_TOKEN
FROM OPENQUERY (CS2,'        
SELECT DISTINCT A.* FROM SEM_PARAR_RECUPERA_CONTRATO A
JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
WHERE C.ID_CARTEIRA IN (20,22,24,25,26)
AND C.STATUS IN (0,4,3,5)')
GO