--select * from cad_idcontrato where cpf_dev = '11037365000107'
----44044308ID
----13640055

----44034290ID
----11408203

--select * from cad_devf where contrato_fin = '44034290ID'

--select * from cad_devp where contrato_fin = '44071015ID'

--select * from CAD_DEVF_SEMPARAR_CAR8 where NUM_CONTRATO = '8171964'

--select * from CAD_DEVF_SEMPARAR_CAR8 where cpf like '%27025997889'

--select * from CAD_DEVP_SEMPARAR_CAR8 where CONTRATO_ORIGINAL = '8820653'

--select * from ACORDO_SEMPARAR_CAR8 where CONTRATO_ORIGINAL = '11408203'

--select * from cad_aco where contrato_fin = '44034290ID'

--select * from ACORDO_PARCELAS_SEMPARAR_CAR8 where CONTRATO_ORIGINAL = '11408203'

--select * from cad_acop where contrato_fin = '44034290ID'

--DELETE FROM CAD_ACOP WHERE CONTRATO_FIN = '44034290ID'
--DELETE FROM CAD_ACO WHERE CONTRATO_FIN = '44034290ID'

--/*
--4562967609 - pagamento da 1ª parcela no acordo 2 não baixada

--select * from ACORDO_PARCELAS_SEMPARAR_CAR8 where CONTRATO_ORIGINAL = '13640055'
--select * from cad_acop where contrato_fin = '44044308ID'
--*/

--SELECT * 
-- --INTO TOKEN_SEMPARAR_CAR8
--FROM OPENQUERY (CS2,'        
--SELECT
--A.* 
--FROM SEM_PARAR_RECUPERA_CONTRATO A
--  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--WHERE C.ID_CARTEIRA=''26''
--AND C.STATUS IN (''0'',''4'',''3'',''5'') 
--;')

--SEM_PARAR_RECUPERA_CONTRATO

--INSERT INTO AUX_REMESSA_TOKEN
--SELECT COD_CREDOR, DES_REGIS, CODIGO_TOKEN FROM TOKEN_SEMPARAR_CAR8

--UPDATE A SET NUMACORDO_ACO = B.COD_PARCE FROM CAD_ACO A
--JOIN NUMACORDO_SEMPARAR_CAR8 B ON TRY_CONVERT(INT,A.ID_EXTERNO) = B.ID_ACORDO

--select * from NUMACORDO_SEMPARAR_CAR8

--select * from ACORDO_SEMPARAR_CAR8

--DELETE B FROM ACORDO_PARCELAS_SEMPARAR_CAR8  A
--INNER JOIN CAD_IDCONTRATO C ON C.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) collate SQL_Latin1_General_CP1_CI_AS
--INNER JOIN CAD_ACOP AS B ON C.CONTRATOFIXO = B.CONTRATO_FIN

--DELETE B FROM ACORDO_SEMPARAR_CAR8  A
--INNER JOIN CAD_IDCONTRATO C ON C.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) collate SQL_Latin1_General_CP1_CI_AS
--INNER JOIN CAD_ACO AS B ON C.CONTRATOFIXO = B.CONTRATO_FIN

--AUX_REMESSA_TOKEN

SELECT * 
into ACIONAMENTOS_SEMPARAR_CAR8
FROM OPENQUERY (CS2,'
SELECT G.NUM_CONTRATO, B.CPF, A.ID_CONTR, A.SEQ, A.ID_TEL, A.DATA, A.CODIGO, A.MODO,
C.ID_FUNCIONARIO, C.LOGIN, C.NOME, C.STATUS, C.CPF_F,
D.MOTIVO, D.AUTORIZACAO,
E.DDD, E.NUMERO,
F.COD, F.HISTORICO, CONVERT(D.MENSAGEM,CHAR(500)) AS ''COMENTARIO''
FROM HISTORICO A
JOIN CONTRATO B ON A.ID_CONTR = B.ID_CONTR
JOIN PARC_GERAL G ON G.ID_CONTR = A.ID_CONTR
JOIN FUNCIONARIO C ON A.ID_FUNCIONARIO = C.ID_FUNCIONARIO
LEFT JOIN HISTORICO_TEXTO D ON A.ID_CONTR = D.ID_CONTR AND A.SEQ = D.SEQ
LEFT JOIN TELEFONE E ON B.CPF = E.CPF AND A.ID_TEL = E.ID_TEL
JOIN CODIGO F ON A.CODIGO = F.COD
WHERE B.ID_CARTEIRA=26
AND B.STATUS IN (0,4,3,5)
AND A.DATA >= ''20240101''
ORDER BY A.DATA;')
GO
--JOIN PARC_GERAL G ON G.ID_CONTR = A.ID_CONTR

--select * from cad_idcontrato where contratofixo = '44324801ID'

--BEGIN TRAN
--SELECT COD, CODIGO, ID_FUNCIONARIO, LOGIN FROM [ACIONAMENTOS_SEMPARAR_CAR8]
--UPDATE [ACIONAMENTOS_SEMPARAR_CAR8] SET COD = CODIGO, ID_FUNCIONARIO = LOGIN

--SELECT * FROM ACIONAMENTOS_SEMPARAR_CAR8 WHERE LOGIN = 'luana.dias'

--UPDATE ACIONAMENTOS_SEMPARAR_CAR8 SET LOGIN = 459 WHERE LOGIN = 'luana.dias'

--DROP TABLE CAD_DEVP_SEMPARAR_VALIDACAO

--PARC_GERAL_SEM_PARAR_RECUPERA
--SELECT *  
----INTO CAD_DEVP_SEMPARAR_VALIDACAO
--FROM OPENQUERY (CS2,'        
--SELECT A.* FROM PARC_GERAL_SEM_PARAR_RECUPERA A
--INNER JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--AND C.CPF LIKE (''%5216374736'')
--WHERE C.ID_CARTEIRA=''26''
--AND C.STATUS IN (''0'',''4'',''3'',''5'')')
--GO

--CÓDIGO DO CLIENTE -> NUM_CONTRATO DA TABELA CONTRATO
--COD_CREDOR da tbl SEM_PARAR_RECUPERA_CONTRATO

--SELECT *  
--INTO AUX_SEM_PARAR_RECUPERA_CONTRATO_SEMPARAR_VALIDACAO
--FROM OPENQUERY (CS2,'        
--SELECT A.* FROM CONTRATO C
--JOIN SEM_PARAR_RECUPERA_CONTRATO A ON C.ID_CONTR = A.ID_CONTR
--AND C.CPF LIKE (''%5216374736'')
--WHERE C.ID_CARTEIRA=''26''
--AND C.STATUS IN (''0'',''4'',''3'',''5'')')
--GO

--SELECT * FROM AUX_SEM_PARAR_RECUPERA_CONTRATO_SEMPARAR_VALIDACAO

--INSERT INTO AUX_SEMPARAR_SYSOPEN (CONTRATO_FIN, COD_CLIENTE, COD_CREDOR, CONTRATO_ORIGINAL)
--SELECT CONTRATOFIXO, DES_REGIS, COD_CREDOR, NUM_CONTRATO
--FROM AUX_SEM_PARAR_RECUPERA_CONTRATO_SEMPARAR_VALIDACAO A
--JOIN CAD_IDCONTRATO B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
--WHERE B.DATA_INCLUSAO = '20240903'

--SP_HELPTEXT STPCAD_ID

--DECLARE @ID INT

--WHILE 1 = 1
--BEGIN 
--	EXEC STPCAD_ID 

--	SELECT @ID = MAX(ID) FROM CAD_ID

--	UPDATE TOP(1) A SET NUMACOCON_ACO = @ID FROM CAD_ACO A
--	JOIN ACORDO_GETNET_SINQIA B ON A.ID_EXTERNO = B.ID_ACORDO
--	WHERE NUMACOCON_ACO IS NULL

--	IF @@ROWCOUNT = 0
--		BREAK;

--END

update ACIONAMENTOS_SEMPARAR_CAR8 set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf), LEN(cpf))
GO