--SELECT * FROM CAD_RECUP WHERE LOGIN_RECUP = 'MIGRACAO'

UPDATE A SET ID_FUNCIONARIO = 15251 
--SELECT ID_FUNCIONARIO 
FROM [ACIONAMENTOS_RIACHUELO_CAR10] A LEFT JOIN  CAD_RECUP B ON ID_FUNCIONARIO = COD_RECUP WHERE COD_RECUP IS NULL

UPDATE A SET ID_FUNCIONARIO = 15251 
--SELECT ID_FUNCIONARIO 
FROM EVENTO_RIACHUELO_CAR10 A LEFT JOIN  CAD_RECUP B ON ID_FUNCIONARIO = COD_RECUP WHERE COD_RECUP IS NULL