SELECT TOP 10
	COD_STAC,
	VENC_ACOP,
	*
FROM
	CAD_ACO AS A
	JOIN CAD_ACOP AS B ON A.CONTRATO_FIN = B.CONTRATO_FIN
WHERE
	COD_STAC = 0
	AND CAST(VENC_ACOP AS DATE) < CAST(GETDATE() AS DATE)
ORDER BY
	CAST(VENC_ACOP AS DATE) DESC


SELECT   
STACACDIA_CONF,   
STACPRDIA_CONF,   
STACCRDIA_CONF,    
STACPRCRDIA_CONF,   
STACACVENC_CONF,   
STACPRVENC_CONF,    
STACCRVENC_CONF,   
STACPRCRVENC_CONF    
STACPRCANC_CONF,   
STACACCANC_CONF,   
STACPRCRCANC_CONF,    
STACCRCANC_CONF,  
STDVSOLCLI_CONF,  
STDVCANC_CONF,  
DEVBCO_CONF,   
STPAPGASS_CONF,   -- PAGAMENTO ASSESSORIA  
STPAPGBCO_CONF,   -- PAGAMENTO BANCO  
STPAPGDIRETO_CONF,  -- PAGAMENTO DIRETO  
STPAPGBCOWEBSERV_CONF  -- PAGAMENTO BANCO WEB SERVICE  
FROM CONFIGURA (NOLOCK)   

--SELECT * FROM CAD_ACOP


DECLARE   
@PARCONTRATO_FIN CHAR(20) = '67011560157',  
@CONTRATO       VARCHAR(20),    
@COMANDO       VARCHAR(500),  
@DNR        VARCHAR(10),  
@CPF              VARCHAR(14),    
@CANC_PROM            INT,    
@VENC_PROM            INT,    
@CANC_ACO            INT,     
@VENC_ACO            INT,    
@ATRASO              INT,    
@COD_STAC            INT,    
@PARCELA             INT,    
@NACORDO             INT,    
@FLAG              INT,    
@EVENTO              INT,    
@PROMESSACREDICARD         INT,    
@CNPJ              VARCHAR(14),    
@PROTEA              INT,    
@PARCEMAB            INT,    
@VERSAO              VARCHAR(10),    
@DESC_STAC       VARCHAR(30),  
@COD_RECUP       INT,  
@PARCELAS_ORIGINAIS_ACOP   VARCHAR(20),  
@STACDIA             INT,    
@STPRDIA             INT,    
@STACCRDIA           INT,    
@STPRCRDIA           INT,    
@STACVENC            INT,    
@STPRVENC            INT,    
@STACCRVENC            INT,    
@STPRCRVENC            INT,    
@STPRCANC            INT,    
@STACCANC            INT,    
@STPRCRCANC            INT,    
@STCRCANC            INT,    
@STATUS              INT,    
@PERMITEACORDOSMULTIPLOS_CAR   INT,    
@STCB              INT,  
@RETIRARECUP_CAR     INT,  
@COD_CLI       INT,  
@COD_CAR       INT,  
@CANCELAACORDO      INT,  
@DEVOLCONTRATOCANCACOROTNOTUNA_CAR TINYINT,  
@TIPO_DEVOL       TINYINT,  
@EVENTODEVOL      INT,    
@FLAG_CONTRATO      BIT,  --= 1  VARIAVEL PARA IDENTIFICAR SE O PARAMETRO ESTÁ EM BRANCO
@STPAPGASS_CONF INT,   -- PAGAMENTO ASSESSORIA  
@STPAPGBCO_CONF INT,   -- PAGAMENTO BANCO  
@STPAPGDIRETO_CONF INT,   -- PAGAMENTO DIRETO  
@STPAPGBCOWEBSERV_CONF INT  -- PAGAMENTO BANCO WEB SERVICE  
  
SELECT @FLAG_CONTRATO = 1  
  
-- BUSCANDO A VERSÃO ATUAL  
  
SELECT @VERSAO = (SELECT TOP 1 VERATU FROM ERROVER (NOLOCK))  
  
SELECT @DNR    = (SELECT COUNT(1) FROM CAD_EMP (NOLOCK) WHERE CNPJ = '03689477000114')  
  
-- BUSCANDO OS STATUS DOS ACORDOS DA TABELA DE CONFIGURAÇÃO  
  
SELECT   
  
 @STACDIA    = STACACDIA_CONF,   
 @STPRDIA    = STACPRDIA_CONF,   
 @STACCRDIA    = STACCRDIA_CONF,    
    @STPRCRDIA    = STACPRCRDIA_CONF,   
 @STACVENC    = STACACVENC_CONF,   
 @STPRVENC    = STACPRVENC_CONF,    
    @STACCRVENC    = STACCRVENC_CONF,   
 @STPRCRVENC    = STACPRCRVENC_CONF,    
    @STPRCANC    = STACPRCANC_CONF,   
 @STACCANC    = STACACCANC_CONF,   
 @STPRCRCANC    = STACPRCRCANC_CONF,    
    @STCRCANC    = STACCRCANC_CONF,  
 --@TIPO_DEVOL    = STDVSOLCLI_CONF,  
 @TIPO_DEVOL    = STDVCANC_CONF,  
 @EVENTODEVOL   = DEVBCO_CONF,   
 @STPAPGASS_CONF   = STPAPGASS_CONF,   -- PAGAMENTO ASSESSORIA  
 @STPAPGBCO_CONF   = STPAPGBCO_CONF,   -- PAGAMENTO BANCO  
 @STPAPGDIRETO_CONF  = STPAPGDIRETO_CONF,  -- PAGAMENTO DIRETO  
 @STPAPGBCOWEBSERV_CONF  = STPAPGBCOWEBSERV_CONF  -- PAGAMENTO BANCO WEB SERVICE  
FROM CONFIGURA (NOLOCK)    

SELECT
  @COD_CLI = T.COD_CLI,  
  @COD_CAR = T.COD_CAR,     
  @CONTRATO = T.CONTRATO_FIN,    
  @CANC_PROM = T.CANC_PROM,    
  @VENC_PROM = T.VENC_PROM,    
  @CANC_ACO = T.CANC_ACO,    
  @VENC_ACO = T.VENC_ACO,    
  @ATRASO = T.ATRASO,
  @COD_STAC = 0,    
  @NACORDO = T.NACORDO_ACO,    
  @CPF = T.CPF_DEV,    
  @PERMITEACORDOSMULTIPLOS_CAR = T.PERMITEACORDOSMULTIPLOS_CAR,  
  @COD_RECUP = COD_RECUP,  
  @DEVOLCONTRATOCANCACOROTNOTUNA_CAR = DEVOLCONTRATOACOROTNOTUNA_CAR 
FROM(
	SELECT  
	  CAD_DEVF.COD_CLI,  
	  CAD_DEVF.COD_CAR,     
	  CAD_DEVF.CONTRATO_FIN,    
	  CONF_STPROM.CANC_PROM,    
	  CONF_STPROM.VENC_PROM,    
	  CONF_STPROM.CANC_ACO,    
	  CONF_STPROM.VENC_ACO,    
	  DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE()) AS ATRASO,  
	  CAD_ACO.COD_STAC,    
	  CAD_ACO.NACORDO_ACO,    
	  CAD_DEVF.CPF_DEV,    
	  CAD_CAR.PERMITEACORDOSMULTIPLOS_CAR,  
	  COALESCE(CAD_DEVF.COD_RECUP,-1) AS COD_RECUP,  
	  DEVOLCONTRATOACOROTNOTUNA_CAR   
	 FROM     
	  CAD_DEVF   (NOLOCK)   
	  JOIN CAD_CAR  (NOLOCK) ON (CAD_CAR.COD_CLI  = CAD_DEVF.COD_CLI  AND CAD_CAR.COD_CAR   = CAD_DEVF.COD_CAR   )  
	  JOIN CAD_CAR_AUX (NOLOCK) ON (CAD_CAR_AUX.COD_CLI = CAD_DEVF.COD_CLI  AND CAD_CAR_AUX.COD_CAR  = CAD_DEVF.COD_CAR   )  
	  JOIN CONF_STPROM (NOLOCK) ON (CONF_STPROM.COD_CLI = CAD_DEVF.COD_CLI  AND CONF_STPROM.COD_CAR  = CAD_DEVF.COD_CAR   )    
	  JOIN CAD_ACO  (NOLOCK) ON (CAD_ACO.CONTRATO_FIN = CAD_DEVF.CONTRATO_FIN              )    
	  JOIN CAD_ACOP  (NOLOCK) ON (CAD_ACOP.CONTRATO_FIN = CAD_DEVF.CONTRATO_FIN AND CAD_ACOP.NACORDO_ACO = CAD_ACO.NACORDO_ACO AND  
			  CAD_ACOP.PARCELA_ACOP = (SELECT MIN(ACOP2.PARCELA_ACOP) FROM CAD_ACOP AS ACOP2 WITH(NOLOCK)  
					 WHERE CAD_ACOP.CONTRATO_FIN = ACOP2.CONTRATO_FIN AND CAD_ACOP.NACORDO_ACO = ACOP2.NACORDO_ACO  
					 AND ACOP2.COD_STPA  = 0 AND YEAR(ACOP2.VENC_ACOP) BETWEEN 1900 AND 2099 )     )  
	 WHERE     
	  CAD_CAR.CONTROLE_CAR NOT IN ('CREDICARDJUR', 'CREDICARDITAU', 'C&ACAMPANHARJ', 'C&ACAMPANHAPR', 'SANTANDEROY') AND -- EXISTE UMA OUTRA ROTINA PARA ESTES CONTROLES    
  
	 -- OS 122237  
   
	 ( -- ABRE O BLOCO DIAS UTEIS = 1  
   
	 (    
		CONVERT(INT, DBO.FNDBADATASEMHORA(GETDATE()) - CAD_ACOP.VENC_ACOP ) >=  CONF_STPROM.VENC_PROM AND     
		CONVERT(INT, DBO.FNDBADATASEMHORA(GETDATE()) - CAD_ACOP.VENC_ACOP ) <= CONF_STPROM.CANC_PROM AND     
		0 IN (@STPRDIA, @STPRCRDIA) AND DIASUTEISPRO_CONF = 1  
	 )    
  
	 OR    
  
	 (    
		CONVERT(INT,  DBO.FNDBADATASEMHORA(GETDATE()) - CAD_ACOP.VENC_ACOP) >=  CONF_STPROM.CANC_PROM AND    
		0 IN (@STPRDIA, @STPRCRDIA, @STPRVENC, @STPRCRVENC) AND DIASUTEISPRO_CONF = 1  
	 )    
   
	 OR    
   
	 (    
		CONVERT(INT,  DBO.FNDBADATASEMHORA(GETDATE()) - CAD_ACOP.VENC_ACOP) >=  CONF_STPROM.VENC_ACO AND     
		CONVERT(INT,  DBO.FNDBADATASEMHORA(GETDATE()) - CAD_ACOP.VENC_ACOP) <= CONF_STPROM.CANC_ACO AND     
		0 IN (@STACDIA, @STACCRDIA) AND DIASUTEISACO_CONF = 1  
	 )    
  
	 OR    
  
	 (    
		CONVERT(INT,  DBO.FNDBADATASEMHORA(GETDATE()) - CAD_ACOP.VENC_ACOP) >=  CONF_STPROM.CANC_ACO AND     
		0 IN (@STACDIA, @STACCRDIA, @STACVENC, @STACCRVENC) AND DIASUTEISACO_CONF = 1  
		)    
   
   
	 ) -- FECHA O BLOCO DIAS CORRIDOS = 1  
  
	 AND NOT EXISTS (  
		 SELECT 1 FROM AUX_TELEFONICA_ACORDOS XXX (NOLOCK)    
		  WHERE XXX.CONTRATO_FIN = CAD_ACO.CONTRATO_FIN    
		 AND XXX.NACORDO_ACO = CAD_ACO.NACORDO_ACO    
		 AND LTRIM(RTRIM(XXX.CHVASSESSORIA)) = ''    
		   )    
  
		AND (CAD_DEVF.CONTRATO_FIN = @PARCONTRATO_FIN OR @FLAG_CONTRATO = 0)  
  
	  UNION ALL  
  
	  SELECT  
  
	  CAD_DEVF.COD_CLI,  
	  CAD_DEVF.COD_CAR,     
	  CAD_DEVF.CONTRATO_FIN,    
	  CONF_STPROM.CANC_PROM,    
	  CONF_STPROM.VENC_PROM,    
	  CONF_STPROM.CANC_ACO,    
	  CONF_STPROM.VENC_ACO,    
	  DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE()) AS ATRASO,  
	  CAD_ACO.COD_STAC,    
	  CAD_ACO.NACORDO_ACO,    
	  CAD_DEVF.CPF_DEV,    
	  CAD_CAR.PERMITEACORDOSMULTIPLOS_CAR,  
	  COALESCE(CAD_DEVF.COD_RECUP,-1) AS COD_RECUP,  
	  DEVOLCONTRATOACOROTNOTUNA_CAR  
  
	 FROM     
	  CAD_DEVF   (NOLOCK)   
	  JOIN CAD_CAR  (NOLOCK) ON (CAD_CAR.COD_CLI  = CAD_DEVF.COD_CLI  AND CAD_CAR.COD_CAR   = CAD_DEVF.COD_CAR   )  
	  JOIN CAD_CAR_AUX (NOLOCK) ON (CAD_CAR_AUX.COD_CLI = CAD_DEVF.COD_CLI  AND CAD_CAR_AUX.COD_CAR  = CAD_DEVF.COD_CAR   )  
	  JOIN CONF_STPROM (NOLOCK) ON (CONF_STPROM.COD_CLI = CAD_DEVF.COD_CLI  AND CONF_STPROM.COD_CAR  = CAD_DEVF.COD_CAR   )    
	  JOIN CAD_ACO  (NOLOCK) ON (CAD_ACO.CONTRATO_FIN = CAD_DEVF.CONTRATO_FIN              )    
	  JOIN CAD_ACOP  (NOLOCK) ON (CAD_ACOP.CONTRATO_FIN = CAD_DEVF.CONTRATO_FIN AND CAD_ACOP.NACORDO_ACO = CAD_ACO.NACORDO_ACO AND  
			  CAD_ACOP.PARCELA_ACOP = (SELECT MIN(ACOP2.PARCELA_ACOP) FROM CAD_ACOP AS ACOP2 WITH(NOLOCK)  
					 WHERE CAD_ACOP.CONTRATO_FIN = ACOP2.CONTRATO_FIN AND CAD_ACOP.NACORDO_ACO = ACOP2.NACORDO_ACO  
					 AND ACOP2.COD_STPA  = 0 AND YEAR(ACOP2.VENC_ACOP) BETWEEN 1900 AND 2099 )     )  
	 WHERE     
	  CAD_CAR.CONTROLE_CAR NOT IN ('CREDICARDJUR', 'CREDICARDITAU', 'C&ACAMPANHARJ', 'C&ACAMPANHAPR', 'SANTANDEROY') AND -- EXISTE UMA OUTRA ROTINA PARA ESTES CONTROLES    
       
	 ( -- ABRE O BLOCO DIAS UTEIS = 0  
    
	 (   
	  DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE())  >=  CONF_STPROM.VENC_PROM  AND  
	  DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE())  <= CONF_STPROM.CANC_PROM  AND    
	  CAD_ACO.COD_STAC IN (@STPRDIA, @STPRCRDIA) AND COALESCE(DIASUTEISPRO_CONF, 0) = 0  
	 )    
  
	 OR    
  
	 (    
		DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE())  >=  CONF_STPROM.CANC_PROM   AND  
		CAD_ACO.COD_STAC IN (@STPRDIA, @STPRCRDIA, @STPRVENC, @STPRCRVENC) AND COALESCE(DIASUTEISPRO_CONF, 0) = 0  
	 )    
    
	 OR    
    
	 (    
	   DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE())  >=  CONF_STPROM.VENC_ACO    AND  
		DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE())  <= CONF_STPROM.CANC_ACO    AND    
		CAD_ACO.COD_STAC IN (@STACDIA, @STACCRDIA) AND COALESCE(DIASUTEISACO_CONF, 0) = 0  
	 )    
    
	 OR    
    
	 (    
		DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE())  >=  CONF_STPROM.CANC_ACO       AND  
		CAD_ACO.COD_STAC IN (@STACDIA, @STACCRDIA, @STACVENC, @STACCRVENC) AND COALESCE(DIASUTEISACO_CONF, 0) = 0  
	 )  
    
	 ) -- FECHA O BLOCO  
    
	 AND NOT EXISTS (  
		 SELECT 1 FROM AUX_TELEFONICA_ACORDOS XXX (NOLOCK)    
		  WHERE XXX.CONTRATO_FIN = CAD_ACO.CONTRATO_FIN    
		 AND XXX.NACORDO_ACO = CAD_ACO.NACORDO_ACO    
		 AND LTRIM(RTRIM(XXX.CHVASSESSORIA)) = ''    
		   )    
     
		AND (CAD_DEVF.CONTRATO_FIN = @PARCONTRATO_FIN OR @FLAG_CONTRATO = 0) -- VERIFICAÇÃO SE EXISTIR O CONTRATO COMO PARAMETRO  
) AS T

 SELECT @EVENTO = NULL    
  
 SELECT @CANCELAACORDO = 1  
   
 --RETIRAR O RECUPERADOR DA FICHA CASO O ACORDO FOR CANCELADO  
  
 SELECT   
  @RETIRARECUP_CAR = COALESCE(RETIRARECUP_CAR,0)  
 FROM   
  CAD_CAR_AUX (NOLOCK)  
 WHERE   
  COD_CLI = @COD_CLI  
 AND  
  COD_CAR = @COD_CAR   
  
 -- VERIRIFICA SE É O CNPJ DA PROTEA  
  
 SELECT @PROTEA = (SELECT COUNT(1) FROM CAD_EMP (NOLOCK) WHERE CNPJ = '03580738000163')    
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
  
--                         PROMESSA NORMAL E PROMESSA CREDOR VENCIDOS     
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
PRINT CONVERT(VARCHAR(MAX),@ATRASO) + ' > ' + CONVERT(VARCHAR(MAX),@VENC_PROM) + ' AND ' + CONVERT(VARCHAR(MAX),@ATRASO) + ' <= ' + CONVERT(VARCHAR(MAX),@CANC_PROM) + ' AND ' + CONVERT(VARCHAR(MAX),@COD_STAC)
+ ' IN ' + CONVERT(VARCHAR(MAX),@STPRDIA) + ' OU ' + CONVERT(VARCHAR(MAX),@STPRCRDIA)
IF ((@ATRASO > @VENC_PROM) AND (@ATRASO <= @CANC_PROM) AND (@COD_STAC IN (@STPRDIA, @STPRCRDIA)))    
	PRINT 'ENTROU AQUI'
	BEGIN  -- INÍCIO SE O ATRASO FOR MAIOR QUE O VENCIMENTO DA PROMESSA E O ATRASO FOR MENOR OU IGUAL AO CANCELAMENTO DE PROMESSA E O STATUS DO ACORDO FOR PROMESSA EM DIA OU PROMESSA CREDOR EM DIA  
  
	IF @COD_STAC = @STPRDIA    
  
		BEGIN   -- INÍCIO SE O STATUS DO ACORDO FOR PROMESSA EM DIA  
  
			SELECT @STATUS = @STPRVENC    
     
			SELECT @EVENTO = (SELECT PRACVENC_CONF FROM CONFIGURA (NOLOCK))   
  
		END  -- FIM SE O STATUS DO ACORDO FOR PROMESSA EM DIA  
  
	ELSE    
  
		BEGIN  -- INÍCIO SE O STATUS DO ACORDO FOR PROMESSA CREDOR EM DIA  
  
			SELECT @STATUS = @STPRCRVENC    
  
			SELECT @EVENTO = (SELECT PRCRVENC_CONF FROM CONFIGURA (NOLOCK))   
      
		END  -- FIM SE O STATUS DO ACORDO FOR PROMESSA CREDOR EM DIA  
  
	END  -- FIM SE O ATRASO FOR MAIOR QUE O VENCIMENTO DA PROMESSA E O ATRASO FOR MENOR OU IGUAL AO CANCELAMENTO DE PROMESSA E O STATUS DO ACORDO FOR PROMESSA EM DIA OU PROMESSA CREDOR EM DIA  
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
  
--                          PROMESSA NORMAL E PROMESSA CREDOR CANCELADOS     
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
PRINT CONVERT(VARCHAR(MAX),@ATRASO) + ' > ' + CONVERT(VARCHAR(MAX),@CANC_PROM) + ' AND ' + CONVERT(VARCHAR(MAX),@COD_STAC) + ' IN ' + CONVERT(VARCHAR(MAX),@STPRDIA) + ' OU ' + CONVERT(VARCHAR(MAX),@STPRCRDIA) 
+ ' OU ' + CONVERT(VARCHAR(MAX),@STPRVENC) + ' OU ' + CONVERT(VARCHAR(MAX),@STPRCRVENC) 

IF ((@ATRASO > @CANC_PROM) AND (@COD_STAC IN (@STPRDIA, @STPRCRDIA, @STPRVENC, @STPRCRVENC)))    
  
BEGIN  -- INÍCIO SE O ATRASO FOR MAIOR QUE O CANCELAMENTO DA PROMESSA E O STATUS DO ACORDO FOR PROMESSA EM DIA, PROMESSA CREDOR EM DIA, PROMESSA VENCIDA OU PROMESSA CREDOR VENCIDA  
	PRINT 'ENTROU AQUI'
	IF (@COD_STAC = @STPRDIA) OR (@COD_STAC = @STPRVENC)    
  
	BEGIN  -- INÍCIO SE O STATUS DO ACORDO FOR PROMESSA EM DIA OU PROMESSA VENCIDA  
  
		SELECT @STATUS = @STPRCANC    
       
		SELECT @EVENTO = (SELECT PRACCANC_CONF FROM CONFIGURA (NOLOCK)) --CANCELAMENTO DA PROMESSA   
  
		SELECT @CANCELAACORDO = 0  
  
		--SELECT @COD_RECUP = 0   
  
	END  -- FIM SE O STATUS DO ACORDO FOR PROMESSA EM DIA OU PROMESSA VENCIDA  
  
	ELSE    
  
	BEGIN  -- INÍCIO SE O STATUS DO ACORDO FOR PROMESSA CREDOR CANCELADA  
  
		SELECT @STATUS = @STPRCRCANC     
         
		SELECT @EVENTO = (SELECT PRCRCANC_CONF FROM CONFIGURA (NOLOCK)) --CANCELAMENTO DA PROMESSA CREDOR    
  
		SELECT @CANCELAACORDO = 0  
  
	--SELECT @COD_RECUP = 0  
  
	END  -- INÍCIO SE O STATUS DO ACORDO FOR PROMESSA CREDOR CANCELADA 
	
  
	IF @PERMITEACORDOSMULTIPLOS_CAR = 0  
	BEGIN -- INÍCIO SE TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO NUMERO DO ACORDO.
		PRINT 'ACORDO MULTIPLO 1'
	END ELSE
	BEGIN -- INÍCIO SE NÃO TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO CONTRATO  
		PRINT 'NÃO TRABALHA COM ACORDO MULTIPLO 1'
	END -- FIM SE NÃO TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO CONTRATO    
END

  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
  
--                           ACORDO NORMAL E PROMESSA CREDOR VENCIDOS    
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
PRINT CONVERT(VARCHAR(MAX),@ATRASO) + ' >= ' + CONVERT(VARCHAR(MAX),@VENC_ACO) + ' AND ' + CONVERT(VARCHAR(MAX),@ATRASO) + ' <= ' + CONVERT(VARCHAR(MAX),@CANC_ACO) + ' AND ' +  
CONVERT(VARCHAR(MAX),@COD_STAC) + ' IN ' + CONVERT(VARCHAR(MAX),@STACDIA) + ' OU ' + CONVERT(VARCHAR(MAX),@STACCRDIA)
IF ((@ATRASO >= @VENC_ACO) AND (@ATRASO <= @CANC_ACO) AND (@COD_STAC IN (@STACDIA, @STACCRDIA)))    
  
BEGIN  -- INÍCIO SE O ATRASO FOR MAIOR QUE VENCIMENTO DO ACORDO E O ATRASO FOR MENOR OU IGUAL AO CANCELAMENTO DO ACORDO E O STATUS DO ACORDO FOR ACORDO EM DIA OU ACORDO CREDOR EM DIA  
	PRINT 'ENTROU AQUI'
	IF @COD_STAC = @STACDIA     
  
	BEGIN  -- INÍCIO SE O STATUS DO ACORDO FOR EM DIA  
  
		SELECT @STATUS = @STACVENC    
       
		SELECT @EVENTO = (SELECT ACVENC_CONF FROM CONFIGURA (NOLOCK)) --VENCIMENTO DO ACORDO    
  
	END  -- FIM SE O STATUS DO ACORDO FOR EM DIA  
  
	ELSE    
  
	BEGIN -- INÍCIO SE O STATUS DO ACORDO CREDOR FOR EM DIA    
  
		SELECT @STATUS = @STACCRVENC    
         
		SELECT @EVENTO = (SELECT ACCRVENC_CONF FROM CONFIGURA (NOLOCK)) --VENCIMENTO DO ACORDO CREDOR    
  
	END  -- FIM SE O STATUS DO ACORDO CREDOR FOR EM DIA    
  
END  -- FIM SE O ATRASO FOR MAIOR QUE VENCIMENTO DO ACORDO E O ATRASO FOR MENOR OU IGUAL AO CANCELAMENTO DO ACORDO E O STATUS DO ACORDO FOR ACORDO EM DIA OU ACORDO CREDOR EM DIA  
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
  
--                           ACORDO NORMAL E PROMESSA CREDOR CANCELADOS      
  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------    
  
PRINT CONVERT(VARCHAR(MAX),@ATRASO) + ' > ' + CONVERT(VARCHAR(MAX),@CANC_ACO) + ' AND ' + CONVERT(VARCHAR(MAX),@COD_STAC) + ' IN ' + CONVERT(VARCHAR(MAX),@STACDIA) + ' OU ' + CONVERT(VARCHAR(MAX),@STACCRDIA) 
+ ' OU ' + CONVERT(VARCHAR(MAX),@STACVENC) + ' OU ' + CONVERT(VARCHAR(MAX),@STACCRVENC) 
  
IF ((@ATRASO > @CANC_ACO) AND (@COD_STAC IN (@STACDIA, @STACCRDIA, @STACVENC, @STACCRVENC)))    
  
BEGIN  -- INÍCIO SE O ATRASO FOR MAIOR QUE O CANCELAMENTO DO ACORDO E O STATUS DO ACORDO FOR ACORDO EM DIA, ACORDO CREDOR EM DIA, ACORDO VENCIDO OU ACORDO CREDOR VENCIDO  
	PRINT 'ENTROU AQUI'
	IF (@COD_STAC = @STACDIA) OR (@COD_STAC = @STACVENC)  
  
	BEGIN  -- INÍCIO SE O STATUS DO ACORDO FOR ACORDO EM DIA OU ACORDO VENCIDO  
  
		SELECT @STATUS = @STACCANC    
        
		SELECT @EVENTO = (SELECT ACCANC_CONF FROM CONFIGURA (NOLOCK))   
       
		SELECT @CANCELAACORDO = 0  
  
		--SELECT @COD_RECUP = 0  
  
	END  -- INÍCIO SE O STATUS DO ACORDO FOR ACORDO EM DIA OU ACORDO VENCIDO  
  
	ELSE    
  
	BEGIN  -- INÍCIO SE O STATUS DO ACORDO FOR ACORDO CREDOR EM DIA OU ACORDO CREDOR VENCIDO  
       
		SELECT @STATUS = @STCRCANC      
       
		SELECT @EVENTO = (SELECT ACCRCANC_CONF FROM CONFIGURA (NOLOCK)) --CANCELAMENTO DO ACORDO CREDOR   
  
		SELECT @CANCELAACORDO = 0  
  
		--SELECT @COD_RECUP = 0   
  
	END  -- FIM SE O STATUS DO ACORDO FOR ACORDO CREDOR EM DIA OU ACORDO CREDOR VENCIDO  
  
    IF @PERMITEACORDOSMULTIPLOS_CAR = 0    
  
	BEGIN -- INÍCIO SE TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO NUMERO DO ACORDO.    
		PRINT 'ACORDO MULTIPLO 2'
		--UPDATE CAD_DEVP SET     
		--COD_STPA = 0     
		--WHERE CONTRATO_FIN = @CONTRATO    
		--AND CAD_DEVP.NACORDO_DEVP = @NACORDO    
		--AND COD_STPA NOT IN (@STPAPGASS_CONF, @STPAPGBCO_CONF, @STPAPGDIRETO_CONF, @STPAPGBCOWEBSERV_CONF)  
  
	END  -- FIM SE TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO NUMERO DO ACORDO.    
  
	ELSE    
  
	BEGIN -- INÍCIO SE NÃO TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO CONTRATO    
		PRINT 'NÃO TRABALHA COM ACORDO MULTIPLO 2'
		--UPDATE CAD_DEVP SET     
		--COD_STPA = 0     
		--WHERE CONTRATO_FIN = @CONTRATO         
		--AND COD_STPA NOT IN (@STPAPGASS_CONF, @STPAPGBCO_CONF, @STPAPGDIRETO_CONF, @STPAPGBCOWEBSERV_CONF)  
  
	END  -- FIM SE NÃO TRABALHA COM ACORDO MULTIPLO, O ACERTO É FEITO PELO CONTRATO  
END 

PRINT CONVERT(VARCHAR(MAX),@STACDIA) + ' <> '''' OU ' +  CONVERT(VARCHAR(MAX),@STPRDIA) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STACCRDIA) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STPRCRDIA) + ' <> '''' OU ' + 
CONVERT(VARCHAR(MAX),@STACVENC) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STPRVENC) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STACCRVENC) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STPRCRVENC) + ' <> '''' OU ' + 
CONVERT(VARCHAR(MAX),@STPRCANC) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STACCANC) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STPRCRCANC) + ' <> '''' OU ' + CONVERT(VARCHAR(MAX),@STCRCANC)

IF ((@STACDIA <> '') OR (@STPRDIA <> '') OR (@STACCRDIA <> '') OR (@STPRCRDIA <> '') OR (@STACVENC <> '') OR (@STPRVENC <> '') OR  (@STACCRVENC <> '') OR 
(@STPRCRVENC <> '') OR (@STPRCANC <> '') OR (@STACCANC <> '') OR (@STPRCRCANC <> '') OR (@STCRCANC <> ''))  
  
BEGIN -- INÍCIO SE O STATUS FOR VÁLIDO  
	PRINT 'ENTROU AQUI'
	SELECT @DESC_STAC = (SELECT DESC_STAC FROM CAD_STAC (NOLOCK) WHERE COD_STAC = @COD_STAC)  
  
	PRINT '---------------------------------------'  
	PRINT '     ROTINA DE STATUS DE ACORDO        '  
	PRINT '---------------------------------------'  
	PRINT 'CONTRATO: ' + @CONTRATO  
	PRINT 'STATUS  : ' + @DESC_STAC  
	PRINT 'NACORDO : ' + CAST(@NACORDO AS VARCHAR(2))  
	PRINT '---------------------------------------'  
	PRINT @DNR 
	PRINT @CONTRATO
	PRINT @NACORDO
  
	IF @DNR > 0  
  
	BEGIN  

		SELECT @PARCELAS_ORIGINAIS_ACOP = PARCELAS_ORIGINAIS_ACOP FROM CAD_ACOP (NOLOCK)  
		WHERE CONTRATO_FIN = @CONTRATO AND NACORDO_ACO = @NACORDO  
		AND COD_STPA <> 0  
  
		PRINT 'UPDATE CAD_DEVP 3 , INSERE NA EVENTO' 
		PRINT @CONTRATO
		PRINT @NACORDO
		PRINT @PARCELAS_ORIGINAIS_ACOP
		PRINT @STATUS

  
	END
	IF ISNULL(@STATUS,0) = 0
	BEGIN
		PRINT '@STATUS NULO'
	END
	ELSE
	BEGIN
		PRINT @STATUS
	END
END





SELECT   
STACACDIA_CONF,   
STACPRDIA_CONF,   
STACCRDIA_CONF,    
STACPRCRDIA_CONF,   
STACACVENC_CONF,   
STACPRVENC_CONF,    
STACCRVENC_CONF,   
STACPRCRVENC_CONF    
STACPRCANC_CONF,   
STACACCANC_CONF,   
STACPRCRCANC_CONF,    
STACCRCANC_CONF,  
STDVSOLCLI_CONF,  
STDVCANC_CONF,  
DEVBCO_CONF,   
STPAPGASS_CONF,   -- PAGAMENTO ASSESSORIA  
STPAPGBCO_CONF,   -- PAGAMENTO BANCO  
STPAPGDIRETO_CONF,  -- PAGAMENTO DIRETO  
STPAPGBCOWEBSERV_CONF  -- PAGAMENTO BANCO WEB SERVICE  
FROM CONFIGURA (NOLOCK)   

SELECT  
	  CAD_DEVF.COD_CLI,  
	  CAD_DEVF.COD_CAR,     
	  CAD_DEVF.CONTRATO_FIN,    
	  CONF_STPROM.CANC_PROM,    
	  CONF_STPROM.VENC_PROM,    
	  CONF_STPROM.CANC_ACO,    
	  CONF_STPROM.VENC_ACO,    
	  DATEDIFF(DAY,CAD_ACOP.VENC_ACOP,GETDATE()) - DBO.FNDBFINAISDESEMANA(CAD_ACOP.VENC_ACOP,GETDATE()) AS ATRASO,  
	  CAD_ACO.COD_STAC,    
	  CAD_ACO.NACORDO_ACO,    
	  CAD_DEVF.CPF_DEV,    
	  CAD_CAR.PERMITEACORDOSMULTIPLOS_CAR,  
	  COALESCE(CAD_DEVF.COD_RECUP,-1) AS COD_RECUP,  
	  DEVOLCONTRATOACOROTNOTUNA_CAR   
	 FROM     
	  CAD_DEVF   (NOLOCK)   
	  JOIN CAD_CAR  (NOLOCK) ON (CAD_CAR.COD_CLI  = CAD_DEVF.COD_CLI  AND CAD_CAR.COD_CAR   = CAD_DEVF.COD_CAR   )  
	  JOIN CAD_CAR_AUX (NOLOCK) ON (CAD_CAR_AUX.COD_CLI = CAD_DEVF.COD_CLI  AND CAD_CAR_AUX.COD_CAR  = CAD_DEVF.COD_CAR   )  
	  JOIN CONF_STPROM (NOLOCK) ON (CONF_STPROM.COD_CLI = CAD_DEVF.COD_CLI  AND CONF_STPROM.COD_CAR  = CAD_DEVF.COD_CAR   )    
	  JOIN CAD_ACO  (NOLOCK) ON (CAD_ACO.CONTRATO_FIN = CAD_DEVF.CONTRATO_FIN              )    
	  JOIN CAD_ACOP  (NOLOCK) ON (CAD_ACOP.CONTRATO_FIN = CAD_DEVF.CONTRATO_FIN AND CAD_ACOP.NACORDO_ACO = CAD_ACO.NACORDO_ACO AND  
			  CAD_ACOP.PARCELA_ACOP = (SELECT MIN(ACOP2.PARCELA_ACOP) FROM CAD_ACOP AS ACOP2 WITH(NOLOCK)  
					 WHERE CAD_ACOP.CONTRATO_FIN = ACOP2.CONTRATO_FIN AND CAD_ACOP.NACORDO_ACO = ACOP2.NACORDO_ACO  
					 AND ACOP2.COD_STPA  = 0 AND YEAR(ACOP2.VENC_ACOP) BETWEEN 1900 AND 2099 )     )  
	 WHERE     
	  CAD_CAR.CONTROLE_CAR NOT IN ('CREDICARDJUR', 'CREDICARDITAU', 'C&ACAMPANHARJ', 'C&ACAMPANHAPR', 'SANTANDEROY') AND -- EXISTE UMA OUTRA ROTINA PARA ESTES CONTROLES    
  CAD_DEVF.CONTRATO_FIN = '67011560157'