-- Etapas do custo separadas por STEP
----- NOVA VERSAO- ------
--Etapas do Job do Custo Medio
--Step 1 - Nome: AJUSTE_FILIAIS_ANTES_DO_CUSTO
-- PRIMEIRO STEP 1 ---
UPDATE A
	SET A.MATRIZ =  
			CASE WHEN A.MATRIZ = 'FABULA - MATRIZ' 	 	 THEN 'FABULA FILIAL PA'
				 WHEN A.MATRIZ = 'CD CAROL BASSI - ZZAB' THEN 'CAROL BASSI REGULADOR RJ'
			ELSE A.MATRIZ END	
FROM FILIAIS A
JOIN PROP_FILIAIS B ON A.FILIAL = B.FILIAL AND B.PROPRIEDADE = '01126'
WHERE 	B.VALOR_PROPRIEDADE  = 'COMERCIAL'
		AND A.MATRIZ <> CASE 
							WHEN A.MATRIZ = 'FABULA - MATRIZ' 	 	 THEN 'FABULA FILIAL PA'
				 	 		WHEN A.MATRIZ = 'CD CAROL BASSI - ZZAB' THEN 'CAROL BASSI REGULADOR RJ'
						ELSE A.MATRIZ END	
-- PRIMEIRO STEP 1 --
 
--Step 2 - Nome: Ajusta data Emissão Entradas não conferidas para o mês vigente
EXEC LX_GS_AJUSTA_ENTRADA_VIRADA_MES_CUSTO_MEDIO
 
Step 3 - Nome: ATUALIZAR_CUSTO_MEDIO_MP_PA
UPDATE CM_DATA_FECHAMENTO SET DATA_SALDO_MP = '20171231'
						GO
						UPDATE CM_DATA_FECHAMENTO SET DATA_SALDO_PA = '20171231'
						GO
						UPDATE PARAMETROS SET VALOR_ATUAL='31/12/2015' WHERE PARAMETRO = 'DATA_BLOQUEIO_MOV_MP'
						go
						UPDATE PARAMETROS SET VALOR_ATUAL='31/12/2015' WHERE PARAMETRO = 'DATA_BLOQUEIO_MOV_PA'
						go
						EXEC LX_CM_FECHAMENTO_CUSTO_MEDIO 'CM2507R',1
						go
 
--Step 4 - Nome: AJUSTE_FILIAIS_DEPOIS_DO_CUSTO
-- ULTIMO STEP  --
UPDATE A
	SET A.MATRIZ =  
			CASE WHEN A.MATRIZ = 'FABULA FILIAL PA' 	 	 THEN 'FABULA - MATRIZ'
				 WHEN A.MATRIZ = 'CAROL BASSI REGULADOR RJ'  THEN 'CD CAROL BASSI - ZZAB'
			ELSE A.MATRIZ END	
FROM FILIAIS A
JOIN PROP_FILIAIS B ON A.FILIAL = B.FILIAL AND B.PROPRIEDADE = '01126'
WHERE B.VALOR_PROPRIEDADE  = 'COMERCIAL'
AND A.MATRIZ <> CASE WHEN A.MATRIZ = 'FABULA FILIAL PA' 	 	 THEN 'FABULA - MATRIZ'
				 	 WHEN A.MATRIZ = 'CAROL BASSI REGULADOR RJ'  THEN 'CD CAROL BASSI - ZZAB'
				ELSE A.MATRIZ END	
-- ULTIMO STEP  --
