BACKUP DATABASE [CORPORERM] TO DISK = N'\\192.168.9.146\srv-arch03$\SVR-BD05\CORPORERM_2025_MES.BAK' WITH NOFORMAT, INIT,  NAME = N'CORPORERM-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

DECLARE @BACKUPSETID AS INT
SELECT @BACKUPSETID = POSITION FROM MSDB..BACKUPSET WHERE DATABASE_NAME=N'CORPORERM' AND BACKUP_SET_ID=(SELECT MAX(BACKUP_SET_ID) FROM MSDB..BACKUPSET WHERE DATABASE_NAME=N'CORPORERM' )
IF @BACKUPSETID IS NULL 
	BEGIN 
	    RAISERROR(N'Verify failed. Backup information for database ''CORPORERM'' not found.', 16, 1) 
	END

RESTORE VERIFYONLY FROM  DISK = N'\\192.168.9.146\srv-arch03$\SVR-BD05\CORPORERM_2025_MES.BAK' WITH FILE = @backupSetId,  NOUNLOAD,  NOREWIND
GO

--\\192.168.9.93\svr-bd05$ caminho para levar o bkp

----RESTORE CASO NECESSÁRIO (9.98)

--USE [master]
--RESTORE DATABASE [CORPORERM_JON] FROM  DISK = N'\\192.168.9.146\srv-arch03$\SVR-BD05\CORPORERM_2025_ABRIL.BAK' WITH  FILE = 1,  MOVE N'BaseVazia' TO N'E:\MSSQL\Data\CORPORERM_JON.mdf',  MOVE N'BaseVazia_log' TO N'E:\MSSQL\Data\CORPORERM_JON_1.ldf',  NOUNLOAD,  STATS = 5
----CHECA SE O BANCO ESTA OK
--DBCC CHECKDB('CORPORERM_JON')

----COLOCA EM SINGLE USER E DROPA A BASE
--USE MASTER;
--ALTER DATABASE CORPORERM_JON SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--DROP DATABASE CORPORERM_JON;
