BACKUP DATABASE [CORPORERM] TO DISK = N'\\192.168.9.146\srv-arch03$\SVR-BD05\CORPORERM_2025_ABRIL.BAK' WITH NOFORMAT, INIT,  NAME = N'CORPORERM-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

DECLARE @BACKUPSETID AS INT
SELECT @BACKUPSETID = POSITION FROM MSDB..BACKUPSET WHERE DATABASE_NAME=N'CORPORERM' AND BACKUP_SET_ID=(SELECT MAX(BACKUP_SET_ID) FROM MSDB..BACKUPSET WHERE DATABASE_NAME=N'CORPORERM' )
IF @BACKUPSETID IS NULL 
	BEGIN 
	    RAISERROR(N'Verify failed. Backup information for database ''CORPORERM'' not found.', 16, 1) 
	END

RESTORE VERIFYONLY FROM  DISK = N'\\192.168.9.146\srv-arch03$\SVR-BD05\CORPORERM_2025_ABRIL.BAK' WITH FILE = @backupSetId,  NOUNLOAD,  NOREWIND
GO

--\\192.168.9.93\svr-bd05$ caminho para levar o bkp