
--BY PASS NORMAL
IF SYSTEM_USER IN ('MARCOS.DINIZ', 'JONATHAN.VERAS', 'JOHNNY.BITTENCOURT','ANIMALE\alexandre.pereira','ALEXANDRE.PEREIRA') OR UPPER(APP_NAME()) LIKE '%RetailSyncClient%'    
        BEGIN    
            RETURN    
        END    

--BY PASS SOMENTE EM UM TRECHO ESPECIFICO
IF UPDATE(EMISSAO)
	BEGIN
		IF EXISTS(SELECT *
			FROM	Deleted, ESTOQUE_PROD_CTG_AJUSTE, ESTOQUE_PRODUTOS 
			WHERE	DELETED.NOME_CONTAGEM = ESTOQUE_PROD_CTG_AJUSTE.NOME_CONTAGEM AND
				ESTOQUE_PRODUTOS.FILIAL=DELETED.FILIAL AND
				ESTOQUE_PRODUTOS.PRODUTO=ESTOQUE_PROD_CTG_AJUSTE.PRODUTO AND
				ESTOQUE_PRODUTOS.COR_PRODUTO=ESTOQUE_PROD_CTG_AJUSTE.COR_PRODUTO AND
				DELETED.EMISSAO < ESTOQUE_PRODUTOS.DATA_AJUSTE ) OR
		   EXISTS(SELECT *
			FROM	Inserted, ESTOQUE_PROD_CTG_AJUSTE, ESTOQUE_PRODUTOS 
			WHERE	INSERTED.NOME_CONTAGEM = ESTOQUE_PROD_CTG_AJUSTE.NOME_CONTAGEM AND
				ESTOQUE_PRODUTOS.FILIAL=INSERTED.FILIAL AND
				ESTOQUE_PRODUTOS.PRODUTO=ESTOQUE_PROD_CTG_AJUSTE.PRODUTO AND
				ESTOQUE_PRODUTOS.COR_PRODUTO=ESTOQUE_PROD_CTG_AJUSTE.COR_PRODUTO AND
				INSERTED.EMISSAO < ESTOQUE_PRODUTOS.DATA_AJUSTE ) 

		BEGIN--BY PASS
			IF SYSTEM_USER NOT IN ('WILLIAN.FERNANDES','APP_AUDITORIA') 
			BEGIN
				SELECT 	@errno=30002,
					@errmsg='Não é possível Alterar Movimentacao de Estoque anterior ao Ajuste !'
				GOTO error
			END
            --BY PASS
		END
	END