DECLARE @CHAVE VARCHAR(50)=NULL
--DECLARE xcursor CURSOR FAST_FORWARD FOR
	SELECT count(1), A.TIPO_ORIGEM
	FROM SS_WMS_PORTAL_AGENDAMENTO A    
	LEFT JOIN ENTRADAS B ON A.CHAVE_NFE = B.CHAVE_NFE     
	LEFT JOIN VW_PIT_SINTESE_AGENDAMENTOS_NAO_CONCLUIDOS C ON A.CHAVE_NFE = C.CHAVE_NFE     
	WHERE B.NF_ENTRADA IS NULL     
			AND C.CHAVE_NFE IS NULL     
			AND A.APP_ORIGEM = 'PITAGORAS'     
			AND (ISNULL(A.LOG_APP_ORIGEM,'') = '' 
					OR ISNULL(A.LOG_APP_ORIGEM,'') LIKE '%LX_SEQUENCIAL%' 
					OR ISNULL(A.LOG_APP_ORIGEM,'') LIKE '%DEADLOCK%'
					OR ISNULL(A.LOG_APP_ORIGEM,'') LIKE '%Ocorreu um problema não identificado, tente novamente!%'
					OR ISNULL(A.LOG_APP_ORIGEM,'') LIKE '%Não foi possível atualizar sequencial%'  -- [ERR_NI]   
					OR ISNULL(A.LOG_APP_ORIGEM,'') LIKE '%Materiais com controle de peças partidas, porém não há preenchi%')	-- [PP]
			AND A.CHAVE_NFE = CASE WHEN @CHAVE IS NULL THEN A.CHAVE_NFE ELSE @CHAVE END   
			AND A.APP_ENTRADA_LIBERADA = 1 
	group by A.TIPO_ORIGEM