--ACESSO DE LEITURA E ESCRITA NO DB_VIEWS E NO SOMA SÓ LEITURA
--CASO ALGUEM QUEIRA ESCREVER EM QUALQUER TABELA DA DATABASE SOMA, MANDAR EMAIL E ESCALAR

--CRIAR LOGIN NO 200 
--CRIA LOGIN NORMALMENTE COM AS PERMISSOES NECESSÁRIAS(CRIAR COM ACESSO DE LEITURA NA MASTER SEMPRE)
INSERT INTO ss_acesso_bd VALUES (<login>, <aplicacao>, getdate(), system_user);

--EXECUTAR A PROC PARA GERAR O CREATE USER PARA RODAR NO 9.100
SP_HELP_REVLOGIN 'LOGIN'

--CRIAR LOGIN NO 100

--INSERIR NA PLANILHA
