INSERT INTO SOMA.dbo.ZTBMM_SALDDEPLJ_LNR WITH (TABLOCK) (ERDAT,J_3ASIZE,MATNR,LGORT,WERKS,STCD1,MENGE,MEINS,VERPR_LJ,WAERS_LJ,VERPR_CD,WAERS_CD,DATA_INSERT)
SELECT
	REPLACE(CONVERT(DATE, [Dt#Criação], 103),'-','') AS ERDAT,
	VMz AS J_3ASIZE,
	MATERIAL AS MATNR,
	[Dep#] AS LGORT,
	[Cen#] AS WERKS,
	left(convert(BIGint, CNPJ), 14) AS STCD1,
	REPLACE(Quantidade, ',', '.') AS MENGE,
	UMB AS MEINS,
	REPLACE([Custo Loja],',', '.') AS VERPR_LJ,
	'' AS WAERS_LJ,
	REPLACE([  Custo CD],',', '.') AS VERPR_CD,
	'' AS WAERS_CD,
	GETDATE() AS DATA_INSERT
FROM AnaliseTI.dbo.[IMPORT_WALLACE];