CREATE PROCEDURE stpJuncaoContratosMigracaoLocaliza(    
 @reprocessar bit = 0,    
 @QtdTot int output    
)    
as    
begin try    
    
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED     
    
 declare @obj varchar(100) = 'stpJuncaoContratosMigracaoLocaliza'    
 declare @dt_ini datetime, @dt_fim datetime, @Qtd int = null    
    
 -------------------------------- JUNÇÃO CONTRATOS --------------------------------     
    
 IF OBJECT_ID('TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA') IS NULL    
 BEGIN     
  CREATE TABLE TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA(    
   CONTRATO_ORIGINAL VARCHAR(50) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,    
   CPF_DEV VARCHAR(14) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,    
   CONTRATO_FIN VARCHAR(20) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,    
   IDCONTRATO BIGINT,    
   IDDEVEDOR BIGINT    
  )    
  CREATE NONCLUSTERED INDEX NON_IX ON TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA(IDDEVEDOR) INCLUDE(CPF_DEV)    
  CREATE NONCLUSTERED INDEX NON_IX2 ON TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA(IDCONTRATO) INCLUDE(CPF_DEV, CONTRATO_ORIGINAL)    
  --CREATE NONCLUSTERED INDEX NON_IX3 ON TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA(CONTRATO_FIN)    
 END;    
    
 set @dt_ini = getdate()    
    
 if @reprocessar = 1    
 begin    
  TRUNCATE TABLE TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA     
    
  ALTER INDEX ALL ON TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA  REBUILD    
  ALTER INDEX ALL ON TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA  REORGANIZE    
 end;    
    
 INSERT TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA (    
  CONTRATO_ORIGINAL, CPF_DEV, CONTRATO_FIN, IDCONTRATO, IDDEVEDOR    
 )    
 SELECT     
  CONTRATO_ORIGINAL, CPF_DEV, CONTRATO_FIN, IDCONTRATO, IDDEVEDOR    
 FROM (    
  SELECT    
   C.CONTRATO_ORIGINAL, C.CPF_DEV, C.CONTRATOFIXO AS CONTRATO_FIN, A.IDCONTRATO, B.IDDEVEDOR,    
   ROW_NUMBER() OVER(PARTITION BY C.CONTRATOFIXO ORDER BY C.CONTRATOFIXO) AS RW    
  FROM     
   NEO_ESPELHO_CONTRATOS_LOCALIZA     AS A WITH(NOLOCK)    
   JOIN NEO_ESPELHO_DEVEDORES_LOCALIZA AS B WITH(NOLOCK) ON A.IDCONTRATO = B.IDCONTRATO    
   JOIN SRC.DBO.CAD_IDCONTRATO      AS C WITH(NOLOCK) ON A.CONTRATO_ORIGINAL = C.CONTRATO_ORIGINAL AND B.CPF_DEV = C.CPF_DEV      
 ) AS X    
 WHERE     
  RW = 1    
  AND NOT EXISTS (SELECT * FROM TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA AS Y     
      WHERE X.CONTRATO_FIN = Y.CONTRATO_FIN)    
    
 set @Qtd = @@rowcount    
 set @dt_fim = getdate()    
 exec stpLogTempoExecucao @obj, 'TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA', @Dt_Ini, @Dt_Fim, @Qtd    
    
 set @QtdTot = @Qtd    
    
END TRY    
BEGIN CATCH    
    
 EXEC STP_LOG_ERRO 'stpJuncaoContratosMigracaoLocaliza'    
    
 SELECT      
    ERROR_NUMBER() AS ERRORNUMBER        
   ,ERROR_SEVERITY() AS ERRORSEVERITY        
   ,ERROR_STATE() AS ERRORSTATE        
   ,ERROR_PROCEDURE() AS ERRORPROCEDURE        
   ,ERROR_LINE() AS ERRORLINE        
   ,ERROR_MESSAGE() AS ERRORMESSAGE;      
    
END CATCH