    
CREATE PROCEDURE stpMigracaoRecupAcordo(    
 @qtdtot int = 0 output    
)    
as    
BEGIN TRY    
    
DECLARE @OBJ VARCHAR(100) = 'stpMigracaoRecupAcordo'    
DECLARE @DT_INI DATETIME, @DT_FIM DATETIME, @QTD INT = NULL    
    
-----------------------------------------------------------------------------------------------------------------    
    
--TABELA USADA PARA MIGRAÇÃO DE AMOSTRA: AUXSRC.DBO.TBL_AJUSTE_RECUP_ACORDO_LOCALIZA_TESTE    
    
set @dt_ini = getdate()    
IF OBJECT_ID('TBL_AJUSTE_RECUP_ACORDO_LOCALIZA') IS NOT NULL    
BEGIN    
 DROP TABLE TBL_AJUSTE_RECUP_ACORDO_LOCALIZA;    
END;    
    
SELECT *, ROW_NUMBER() OVER(ORDER BY IDCONTRATO) AS ID    
 INTO AUXSRC.DBO.TBL_AJUSTE_RECUP_ACORDO_LOCALIZA    
FROM (    
 SELECT --TOP 20     
  A.CONTRATO_ORIGINAL, A.IDCONTRATO, B.CONTRATO_FIN, C.NACORDO_ACO, C.NUMACORDO_ACO, A.IDFUNCIONARIO, E.COD_RECUP, E.LOGIN_RECUP, C.RECUP_ACO AS RECUP_ACO_OLD    
     
 FROM     
  AUXSRC.[DBO].NEO_ESPELHO_ACORDOS_LOCALIZA    AS A WITH(NOLOCK)     
  JOIN AUXSRC.[DBO].TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA AS B WITH(NOLOCK) ON A.CONTRATO_ORIGINAL = B.CONTRATO_ORIGINAL    
  JOIN SRC.DBO.CAD_ACO         AS C WITH(NOLOCK) ON B.CONTRATO_FIN = C.CONTRATO_FIN AND A.NUMEROACORDOCONTRATANTE = C.NUMACORDO_ACO    
    
  JOIN AUXSRC.[DBO].NEO_ESPELHO_RECUPS_LOCALIZA  AS D ON A.IDFUNCIONARIO = D.IDFUNCIONARIOS    
  JOIN SRC.DBO.CAD_RECUP        AS E ON D.LOGONUSUARIO = E.LOGIN_RECUP     
 --WHERE    
 -- EXISTS (SELECT * FROM SRC.DBO.CAD_DEVF AS X WHERE B.CONTRATO_FIN = X.CONTRATO_FIN AND X.STATCONT_FIN = 0)     
) AS Y    
WHERE     
 RECUP_ACO_OLD IS NULL     
 OR     
 COD_RECUP <> RECUP_ACO_OLD    
    
set @qtd = @@rowcount    
set @dt_fim = getdate()    
exec stpLogTempoExecucao @obj, 'TBL_AJUSTE_RECUP_ACORDO_LOCALIZA', @Dt_Ini, @Dt_Fim, @Qtd    
    
set @qtdtot = @QTD    
    
-----------------------------------------------------------------------------------------------------------------    
    
set @dt_ini = getdate()    
DECLARE @VLR_INI INT, @VLR_FIN INT, @VLR_TOT INT, @BLOCO INT    
    
SET @BLOCO = 1000    
SET @VLR_INI = 1    
SET @VLR_FIN = (@VLR_INI + @BLOCO)-1    
SELECT @VLR_TOT = MAX(ID) FROM TBL_AJUSTE_RECUP_ACORDO_LOCALIZA WITH(NOLOCK)    
    
IF @VLR_TOT > 0    
BEGIN    
 WHILE 1=1    
 BEGIN     
  UPDATE A SET    
   A.RECUP_ACO = B.COD_RECUP    
  FROM SRC.DBO.CAD_ACO AS A    
  JOIN AUXSRC.DBO.TBL_AJUSTE_RECUP_ACORDO_LOCALIZA AS B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.NACORDO_ACO = B.NACORDO_ACO    
  WHERE B.ID BETWEEN @VLR_INI AND @VLR_FIN    
    
  IF @VLR_FIN >= @VLR_TOT    
  BEGIN    
   BREAK;    
  END;    
    
  SET @VLR_INI += @BLOCO    
  SET @VLR_FIN += @BLOCO    
 END;    
END;    
    
set @dt_fim = getdate()    
exec stpLogTempoExecucao @obj, 'UPDATE RECUP_ACO', @Dt_Ini, @Dt_Fim, @Qtd    
    
-------- ATUALIZAÇÃO TIPO_ACO ---------------------------------------------------------------------------    
    
/*    
IF OBJECT_ID('TBL_AJUSTE_TIPO_ACORDOS_LOCALIZA') IS NOT NULL    
BEGIN    
 DROP TABLE TBL_AJUSTE_TIPO_ACORDOS_LOCALIZA;    
END;    
    
SELECT     
 A.*, B.CONTRATO_FIN, C.NACORDO_ACO, C.TIPO_ACO AS TIPO_ACO_OLD, IIF(OBS = 'BOLETO', 1, 2) AS TIPO_ACO    
 INTO TBL_AJUSTE_TIPO_ACORDOS_LOCALIZA    
FROM     
 AUXSRC.[DBO].[MIGRACAO SRC TIPOACORDO] AS A WITH(NOLOCK)    
 JOIN SRC.DBO.CAD_DEVF AS B WITH(NOLOCK) ON A.CONTA = B.CONTRATO_LOS AND SUBSTRING(A.CPF,PATINDEX('%[A-Z,1-9]%',A.CPF),14) = B.CPF_DEV    
 JOIN SRC.DBO.CAD_ACO AS C WITH(NOLOCK) ON B.CONTRATO_FIN = C.CONTRATO_FIN AND A.[ACORDO LOCALIZA ] = C.NUMACORDO_ACO    
    
--BEGIN TRAN    
UPDATE A SET    
 A.TIPO_ACO = B.TIPO_ACO    
FROM SRC.DBO.CAD_ACO AS A    
JOIN AUXSRC.DBO.TBL_AJUSTE_TIPO_ACORDOS_LOCALIZA AS B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.NACORDO_ACO = B.NACORDO_ACO    
--COMMIT    
*/    
    
end try    
begin catch    
 EXEC STP_LOG_ERRO 'stpMigracaoRecupAcordo'    
    
 SELECT      
    ERROR_NUMBER() AS ERRORNUMBER        
   ,ERROR_SEVERITY() AS ERRORSEVERITY        
   ,ERROR_STATE() AS ERRORSTATE        
   ,ERROR_PROCEDURE() AS ERRORPROCEDURE        
   ,ERROR_LINE() AS ERRORLINE        
   ,ERROR_MESSAGE() AS ERRORMESSAGE;      
end catch