CREATE PROCEDURE stpMigracaoAcionaFullLocaliza(      
 @reprocessa bit = 0, @qtdtot int = 0 output        
)      
as      
BEGIN TRY      
      
DECLARE @OBJ VARCHAR(100) = 'stpMigracaoAcionaFullLocaliza'      
DECLARE @DT_INI DATETIME, @DT_FIM DATETIME, @QTD INT = NULL      
      
/*      
-- CASO PRECISE REMIGRAR OS DADOS, É NECESSÁRIO, APÓS DELETAR OS DADOS DA ACIONA, TRUNCAR A TABELA ABAIXO      
-- TRUNCATE TABLE AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA      
      
 LIMPAR ACIONA E TABELAS DE MIGRAÇÃO:      
      
-- TRUNCATE TABLE AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA      
-- TRUNCATE TABLE AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA]      
      
--ALTER TABLE [DBO].[CAD_ACIONA_DISCADOR] DROP CONSTRAINT [FK_CAD_ACIONA_DISCADOR_ACIONA]      
      
--TRUNCATE TABLE CAD_ACIONA_DISCADOR      
--TRUNCATE TABLE ACIONA      
      
--ALTER TABLE [DBO].[CAD_ACIONA_DISCADOR]  WITH CHECK ADD  CONSTRAINT [FK_CAD_ACIONA_DISCADOR_ACIONA] FOREIGN KEY([ID_ACIONA])      
--REFERENCES [DBO].[ACIONA] ([ID])      
      
--ALTER TABLE [DBO].[CAD_ACIONA_DISCADOR] CHECK CONSTRAINT [FK_CAD_ACIONA_DISCADOR_ACIONA]      
      
SELECT * FROM AUXSRC.[DBO].[TBL_DEXPARA_ACIONAMENTOS_NEO_LOCALIZA]      
      
-- INSERT NOVOS ACIONAMENTOS - 07/10      
INSERT AUXSRC.[DBO].[TBL_DEXPARA_ACIONAMENTOS_NEO_LOCALIZA](      
 COD_ACIONAMENTO, IDENTIFICADORRESPOSTA      
)      
VALUES      
(8273,212),      
(8274,801),      
(8275,802),      
(8276,803),      
(8277,804)      
      
      
*/      
--COMMIT      
      
------------------------------ LIMPA TABELAS ----------------------------------------------------------------------      
      
IF @reprocessa = 1      
BEGIN      
 TRUNCATE TABLE AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA]      
 TRUNCATE TABLE AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA      
END;      
      
------------------------------ TABELA AUXILIAR DE MIGRAÇÃO ACIONAMENTO ----------------------------------------------------------------------      
      
--DROP TABLE AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA]      
IF OBJECT_ID ('AUXSRC.DBO.TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA') IS NULL      
BEGIN      
 CREATE TABLE AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA](      
  ID INT IDENTITY(1,1) PRIMARY KEY,      
  [CONTRATO_FIN] [VARCHAR](20) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS,      
  [DATA_ACIONA] [DATETIME] NULL,      
  [DATA_ACIONA2] [DATE] NULL,      
  [COD_TIPAC] [INT] NOT NULL,      
  [DDD_TEL] [VARCHAR](2) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS NULL,      
  [TEL_TEL] [VARCHAR](10) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS NULL,      
  [COD_ACIONAMENTO] [INT] NULL,      
  [IDENTIFICADORRESPOSTA] [INT] NULL,      
  [COD_RECUP] [INT] NOT NULL,      
  [AGENDA_ACIONA] [VARCHAR](8000) COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS NULL,      
  [ID_LINKEDSERVER] [INT] NULL,      
  [ID_BULKINSERT] [INT] NULL,      
  [DATA_INSERT] [DATETIME] DEFAULT GETDATE()      
 )       
 CREATE NONCLUSTERED INDEX NON_IX ON AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA] (CONTRATO_FIN, DATA_ACIONA)      
END;      
      
------------------------------ TABELA CONTROLE MIGRAÇÃO ACIONA ----------------------------------------------------------------------      
      
IF OBJECT_ID ('AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA') IS NULL      
BEGIN      
 CREATE TABLE AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA(      
  ID INT,      
  DATA_INSERT DATETIME DEFAULT GETDATE()      
 )      
 CREATE CLUSTERED INDEX CL_IX ON AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA (ID)      
END;      
      
/* ********************************************************************************************************************************* */      
------------------------------ BULLK INSERT ----------------------------------------------------------------------      
/*  NÃO SERÁ USADO BULK INSERT POR ARQUIVO NESSA MIGRAÇÃO DE 2025    
set @dt_ini = getdate()      
INSERT AUXSRC.[DBO].TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA(       CONTRATO_FIN, DATA_ACIONA, DATA_ACIONA2, COD_TIPAC, DDD_TEL, TEL_TEL, COD_ACIONAMENTO, COD_RECUP, AGENDA_ACIONA, ID_BULKINSERT      
)      
SELECT       
 B.CONTRATO_FIN,      
 CONVERT(DATETIME,LEFT(A.ANCO_DATAHORA,19),120) AS DATA_ACIONA,       
 CONVERT(DATE,LEFT(A.ANCO_DATAHORA,19),120) AS DATA_ACIONA2,       
 0 AS COD_TIPAC,      
 LEFT(REPLACE(REPLACE(A.TDEV_TELEFONE,'(',''),')',''),2) AS DDD_TEL,      
 IIF(LEN(A.TDEV_TELEFONE) > 14, SUBSTRING(REPLACE(A.TDEV_TELEFONE,'-',''),7,9), SUBSTRING(REPLACE(A.TDEV_TELEFONE,'-',''),5,9)) AS TEL_TEL,      
 COALESCE(C.COD_ACIONAMENTO, 8161) AS COD_ACIONAMENTO,      
 COALESCE(E.COD_RECUP, 377) AS COD_RECUP,      
 UPPER(REPLACE(REPLACE(REPLACE(A.STAC_DESCRICAO,CHAR(13),''),'‡','Ç'),'Æ','Ã') + ' | ' +       
   REPLACE(REPLACE(REPLACE(A.ANCO_DESCRICAO,CHAR(13),''),'‡','Ç'),'Æ','Ã') + ' | ' +       
   REPLACE(A.FUNC_NOME,CHAR(13),'')) AS AGENDA_ACIONA,      
 A.ID      
FROM       
 AUXSRC.[DBO].NEO_ESPELHO_ACIONA_CARTOES_02    AS A /* AQUI PERMANECE CARTÕES MESMO PARA LOCALIZA */       
 JOIN AUXSRC.[DBO].TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA AS B ON A.CTRA_ID = CAST(B.IDCONTRATO AS VARCHAR(20))      
 LEFT JOIN AUXSRC.[DBO].[TBL_DEXPARA_ACIONAMENTOS_NEO_LOCALIZA]  AS C ON TRY_CAST(REPLACE(A.STAC_ID,CHAR(13),'') AS INT) = C.IDENTIFICADORRESPOSTA      
 LEFT JOIN AUXSRC.[DBO].NEO_ESPELHO_RECUPS_LOCALIZA  AS D ON D.NOMEUSUARIO = REPLACE(A.FUNC_NOME,CHAR(13),'')       
 LEFT JOIN SRC.DBO.CAD_RECUP        AS E ON D.LOGONUSUARIO = E.LOGIN_RECUP      
--where exists (select * from auxsrc.dbo.TBL_CPFS_TESTE_MIGRACAO as xxx with(nolock) where xxx.contrato_fin = b.CONTRATO_FIN)      
      
set @Qtd = @@ROWCOUNT      
set @Dt_Fim = getdate()      
exec stpLogTempoExecucao @obj, 'REGISTROS BULK INSERT', @Dt_Ini, @Dt_Fim, @Qtd      
 */    
------------------------------ LINKED SERVER ----------------------------------------------------------------------      
      
set @dt_ini = getdate()      
INSERT AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA](      
 CONTRATO_FIN, DATA_ACIONA, DATA_ACIONA2, COD_TIPAC, DDD_TEL, TEL_TEL, COD_ACIONAMENTO, COD_RECUP, AGENDA_ACIONA, ID_LINKEDSERVER      
)      
SELECT       
 B.CONTRATO_FIN,      
 A.DATAHORAANDAMENTO AS DATA_ACIONA,       
 CAST(A.DATAHORAANDAMENTO AS DATE) AS DATA_ACIONA2,      
 0 AS COD_TIPAC,      
 IIF(A.RECEPTIVO = 1, NULL, LEFT(REPLACE(REPLACE(A.NUMEROTELEFONE,'(',''),')',''),2)) AS DDD_TEL,      
 IIF(A.RECEPTIVO = 1, 'RECEPTIVO', IIF(LEN(A.NUMEROTELEFONE) > 14, SUBSTRING(REPLACE(A.NUMEROTELEFONE,'-',''),7,9), SUBSTRING(REPLACE(A.NUMEROTELEFONE,'-',''),5,9))) AS TEL_TEL,      
 COALESCE(C.COD_ACIONAMENTO, 8161) AS COD_ACIONAMENTO,      
 COALESCE(E.COD_RECUP, 377) AS COD_RECUP,      
 A.DESCRICAORESPOSTA + ' | ' + A.DESCRICAOANDAMENTO + ' | ' + A.NOMEUSUARIO AS AGENDA_ACIONA,      
 ID      
FROM       
 AUXSRC.[DBO].NEO_ESPELHO_ACIONA_LOCALIZA        AS A WITH(NOLOCK)       
 JOIN AUXSRC.[DBO].TBL_CONTRATOS_JUNCAO_SRC_NEO_LOCALIZA  AS B WITH(NOLOCK) ON A.CONTRATO_ORIGINAL = B.CONTRATO_ORIGINAL      
 LEFT JOIN AUXSRC.[DBO].[TBL_DEXPARA_ACIONAMENTOS_NEO_LOCALIZA]      AS C WITH(NOLOCK) ON A.IDENTIFICADORRESPOSTA = C.IDENTIFICADORRESPOSTA      
 LEFT JOIN AUXSRC.[DBO].NEO_ESPELHO_RECUPS_LOCALIZA      AS D WITH(NOLOCK) ON D.NOMEUSUARIO = A.NOMEUSUARIO      
 LEFT JOIN SRC.DBO.CAD_RECUP            AS E WITH(NOLOCK) ON D.LOGONUSUARIO = E.LOGIN_RECUP      
--where exists (select * from auxsrc.dbo.TBL_CPFS_TESTE_MIGRACAO as xxx with(nolock) where xxx.contrato_fin = b.CONTRATO_FIN)      
      
set @Qtd = @@ROWCOUNT      
set @Dt_Fim = getdate()      
exec stpLogTempoExecucao @obj, 'REGISTROS LINKED SERVER', @Dt_Ini, @Dt_Fim, @Qtd      
      
      
/* ************************************************************ INSERT ACIONA ********************************************************************* */      
set @Qtd = 0      
set @dt_ini = getdate()      
DECLARE @VLR_INI INT, @VLR_FIN INT, @VLR_TOT INT, @BLOCO INT      
      
IF (DATEPART(HOUR,GETDATE()) >= 20 OR DATEPART(WEEKDAY,GETDATE()) = 1)      
BEGIN      
 SET @BLOCO = 20000      
END ELSE      
BEGIN      
 SET @BLOCO = 5000      
END;      
      
SELECT @VLR_INI = COALESCE(MAX(ID),0)+1 FROM AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA WITH(NOLOCK)      
SET @VLR_FIN = (@VLR_INI + @BLOCO)-1      
SELECT @VLR_TOT = MAX(ID) FROM AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA] WITH(NOLOCK)      
      
IF @VLR_TOT >= @VLR_INI      
BEGIN      
      
 WHILE 1=1      
 BEGIN      
  INSERT SRC.DBO.ACIONA(      
   CONTRATO_FIN, DATA_ACIONA, DATA_ACIONA2, COD_TIPAC, DDD_TEL, TEL_TEL, COD_ACIONAMENTO, COD_RECUP, AGENDA_ACIONA      
  )      
  SELECT      
   CONTRATO_FIN, DATA_ACIONA, DATA_ACIONA2, COD_TIPAC, DDD_TEL, TEL_TEL, COD_ACIONAMENTO, COD_RECUP, AGENDA_ACIONA      
  FROM      
   AUXSRC.[DBO].[TBL_TEMP_MIGRACAO_ACIONA_NEO_LOCALIZA] AS A WITH(NOLOCK)      
  WHERE      
   ID BETWEEN @VLR_INI AND @VLR_FIN      
      
  SET @Qtd += @@ROWCOUNT      
      
  IF @VLR_FIN >= @VLR_TOT      
  BEGIN      
   INSERT AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA(ID) VALUES(@VLR_TOT)      
   BREAK;      
  END;      
      
  INSERT AUXSRC.[DBO].TBL_CONTROLE_MIGRACAO_ACIONA_NEO_LOCALIZA(ID) VALUES(@VLR_FIN)      
      
  SET @VLR_INI += @BLOCO      
  SET @VLR_FIN += @BLOCO      
 END;      
      
END;      
      
SET @qtdtot = @QTD      
      
set @Dt_Fim = getdate()      
exec stpLogTempoExecucao @obj, 'INSERT ACIONA', @Dt_Ini, @Dt_Fim, @Qtd      
      
/* ************************************************************ UPDATE DTULTAC_FIN ********************************************************************* */      
      
set @Qtd = 0      
set @dt_ini = getdate()      
IF OBJECT_ID('tempdb.dbo.#TEMP_AJUSTE_ULTIDACIONA_MIGRACAO') IS NOT NULL      
BEGIN      
 DROP TABLE #TEMP_AJUSTE_ULTIDACIONA_MIGRACAO;      
END;      
      
SELECT       
 A.CONTRATO_FIN, A.DTULTAC_FIN, A.ULTIDACIONA_FIN, X.DATA_ACIONA, X.ID AS ID_ACIONA      
 INTO #TEMP_AJUSTE_ULTIDACIONA_MIGRACAO      
FROM       
 SRC.DBO.CAD_DEVF AS A WITH(NOLOCK)      
 CROSS APPLY ( SELECT TOP 1 B.ID, B.DATA_ACIONA FROM SRC.DBO.ACIONA AS B WITH(NOLOCK)      
      JOIN SRC.DBO.CAD_ACIONAMENTO AS C WITH(NOLOCK) ON C.COD_ACIONAMENTO = B.COD_ACIONAMENTO      
      WHERE A.CONTRATO_FIN = B.CONTRATO_FIN AND C.ALTDTULTAC_ACIONAMENTO = 0       
      ORDER BY B.DATA_ACIONA DESC    ) AS X      
WHERE      
 (X.ID IS NULL OR X.ID > A.ULTIDACIONA_FIN)      
 --and exists (select * from auxsrc.dbo.TBL_CPFS_TESTE_MIGRACAO as xxx with(nolock) where xxx.contrato_fin = a.CONTRATO_FIN)      
      
set @Qtd = @@ROWCOUNT      
      
ALTER TABLE #TEMP_AJUSTE_ULTIDACIONA_MIGRACAO ADD ID INT IDENTITY(1,1)      
      
--DECLARE @VLR_INI INT, @VLR_FIN INT, @VLR_TOT INT, @BLOCO INT = 5000      
SET @VLR_INI = 1      
SET @VLR_FIN = (@VLR_INI + @BLOCO)-1      
SELECT @VLR_TOT = MAX(ID) FROM #TEMP_AJUSTE_ULTIDACIONA_MIGRACAO WITH(NOLOCK)      
      
IF @VLR_TOT >= @VLR_INI      
BEGIN      
 WHILE 1=1      
 BEGIN      
  UPDATE A SET      
   A.ULTIDACIONA_FIN = B.ID_ACIONA,      
   A.DTULTAC_FIN = B.DATA_ACIONA      
  FROM      
   SRC.DBO.CAD_DEVF AS A      
   JOIN #TEMP_AJUSTE_ULTIDACIONA_MIGRACAO AS B ON A.CONTRATO_FIN = B.CONTRATO_FIN      
  WHERE      
   B.ID BETWEEN @VLR_INI AND @VLR_FIN      
      
  IF @VLR_FIN >= @VLR_TOT      
  BEGIN      
   BREAK;      
  END;      
      
  SET @VLR_INI += @BLOCO      
  SET @VLR_FIN += @BLOCO      
 END;      
END;      
      
set @Dt_Fim = getdate()      
exec stpLogTempoExecucao @obj, 'UPDATE DTULTAC_FIN', @Dt_Ini, @Dt_Fim, @Qtd      
      
end try      
begin catch      
 EXEC STP_LOG_ERRO 'stpMigracaoAcionaFullLocaliza'      
 SELECT        
    ERROR_NUMBER() AS ERRORNUMBER          
   ,ERROR_SEVERITY() AS ERRORSEVERITY          
   ,ERROR_STATE() AS ERRORSTATE          
   ,ERROR_PROCEDURE() AS ERRORPROCEDURE          
   ,ERROR_LINE() AS ERRORLINE          
   ,ERROR_MESSAGE() AS ERRORMESSAGE;        
end catch