--DELETE FROM CAD_IDCONTRATO WHERE DATA_INCLUSAO = '20240831'

update CAD_DEVP_RIACHUELO_CAR10 set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf), LEN(cpf))
GO

INSERT INTO CAD_IDCONTRATO(CONTRATO_ORIGINAL, CPF_DEV, DATA_INCLUSAO)
SELECT  
convert(varchar,A.NUM_CONTRATO),
A.CPF COLLATE SQL_Latin1_General_CP1_CI_AS,
'20240831'
FROM CAD_DEVP_RIACHUELO_CAR10 A
WHERE NOT EXISTS (SELECT 1 FROM CAD_IDCONTRATO B WHERE B.CONTRATO_ORIGINAL = convert(varchar,A.NUM_CONTRATO) collate SQL_Latin1_General_CP1_CI_AS
AND B.CPF_DEV = A.CPF COLLATE SQL_Latin1_General_CP1_CI_AS)

--SELECT A.* FROM CAD_iDCONTRATO A JOIN CAD_DEVP_RIACHUELO_CAR10 B ON A.CONTRATO_ORIGINAL = convert(varchar,B.NUM_CONTRATO) collate SQL_Latin1_General_CP1_CI_AS
--WHERE A.DATA_INCLUSAO != '20240831'