SELECT 
B.CONTRATOFIXO AS CONTRATO_FIN,
B.CPF_DEV,
114 AS COD_CLI,
10 AS COD_CAR,
'P' AS TIPO_FIN,
coalesce(A.VALOR, 0) AS VALOR_FIN,
1 AS MOEDA_FIN,
VENC,
98 AS COD_STCB
INTO CAD_DEVF_INSERT_RIACHUELO_CAR10
FROM CAD_DEVP_RIACHUELO_CAR10 A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.NUM_CONTRATO collate Latin1_General_CI_AS
LEFT JOIN CAD_DEVF C ON B.CONTRATOFIXO = C.CONTRATO_FIN
WHERE B.DATA_INCLUSAO = '20240831' AND C.CONTRATO_FIN IS NULL
GO

--DROP TABLE CAD_DEVF_INSERT_RIACHUELO_CAR10

INSERT INTO CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN, VENC_FIN, COD_STCB)
SELECT * FROM CAD_DEVF_INSERT_RIACHUELO_CAR10
GO

--DELETE A FROM CAD_DEVF A JOIN CAD_DEVF_INSERT_RIACHUELO_CAR10 B ON A.CONTRATO_FIN = B.CONTRATO_FIN

--SELECT A.* FROM CAD_IDCONTRATO A LEFT JOIN CAD_DEV B ON A.CPF_DEV = B.CPF_DEV WHERE A.DATA_INCLUSAO = '20240831' AND B.CPF_DEV IS NULL