SELECT *  
INTO CAD_DEVP_RIACHUELO_CAR10
FROM OPENQUERY (CS2,'        
SELECT C.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', C.CPF, A.* FROM PARC_GERAL A
INNER JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
WHERE C.ID_CARTEIRA=''30''
AND C.STATUS IN (''0'',''4'',''3'',''5'')')
GO

DROP TABLE CAD_DEVP_RIACHUELO_CAR10_AUX
SELECT
	B.CONTRATOFIXO AS CONTRATO_FIN,
	--A.NUM_PARC2 AS PARCELA_PARC,
	'P' AS TIPO_PARC,
	A.VENC AS VENC_PARC,
	A.VALOR AS VALOR_PARC,
	status as COD_STPA
	INTO CAD_DEVP_RIACHUELO_CAR10_AUX
	FROM CAD_DEVP_RIACHUELO_CAR10 A
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.NUM_CONTRATO collate Latin1_General_CI_AS
	WHERE B.DATA_INCLUSAO = '20240831'
	GO

DROP TABLE CAD_DEVP_RIACHUELO_CAR10_INSERT;
with cte
as
(
select
*,
row_number() over (partition by contrato_fin order by venc_parc) as NUm_parc2
from CAD_DEVP_RIACHUELO_CAR10_AUX
)
select *
into CAD_DEVP_RIACHUELO_CAR10_INSERT
from cte
GO

	UPDATE CAD_DEVP_RIACHUELO_CAR10_INSERT SET cod_stpa = 7  WHERE cod_stpa = 0
	GO
	UPDATE CAD_DEVP_RIACHUELO_CAR10_INSERT SET cod_stpa = 16 WHERE cod_stpa = 2
	GO
	UPDATE CAD_DEVP_RIACHUELO_CAR10_INSERT SET cod_stpa = 0  WHERE cod_stpa IN (1,3)
	GO
	UPDATE CAD_DEVP_RIACHUELO_CAR10_INSERT SET cod_stpa = 14 WHERE cod_stpa = 5
	GO

INSERT INTO CAD_DEVP (CONTRATO_FIN, PARCELA_PARC, TIPO_PARC, VENC_PARC, VALOR_PARC, COD_STPA)
	SELECT
	A.CONTRATO_FIN,
	NUM_PARC2 AS PARCELA_PARC,
	A.TIPO_PARC,
	A.VENC_PARC,
	A.VALOR_PARC,
	A.COD_STPA
	FROM CAD_DEVP_RIACHUELO_CAR10_INSERT A
	LEFT JOIN CAD_DEVP B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND NUM_PARC2 = PARCELA_PARC AND A.TIPO_PARC = B.TIPO_PARC
	WHERE B.CONTRATO_FIN IS NULL
	GO

	--DELETE B FROM CAD_DEVP_RIACHUELO_CAR10_INSERT A
	--JOIN CAD_DEVP B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND NUM_PARC2 = PARCELA_PARC AND A.TIPO_PARC = B.TIPO_PARC