SELECT *  
INTO ACORDO_RIACHUELO_CAR10
FROM OPENQUERY (CS2,'        
SELECT B.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', A.* 
FROM ACORDO A
  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
  JOIN  PARC_GERAL B ON C.ID_CONTR = B.ID_CONTR
WHERE C.ID_CARTEIRA=''30''
AND C.STATUS IN (''0'',''4'',''3'',''5'') ')
GO

--DROP TABLE ACORDO_RIACHUELO_CAR10

	UPDATE ACORDO_RIACHUELO_CAR10 SET [STATUS] = 3 WHERE [STATUS] IN (1,2)
	GO
	UPDATE ACORDO_RIACHUELO_CAR10 SET [STATUS] = 5 WHERE [STATUS] IN (4,6)
	GO
	UPDATE ACORDO_RIACHUELO_CAR10 SET [STATUS] = 9 WHERE [STATUS] IN (7,8)
	GO

INSERT INTO CAD_ACO (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACO, DTACORDO_ACO, PLANO_ACO, VLRACORDO_ACO, VENC_ACO, COD_STAC, VLRPRI_ACO, VLRMUL_ACO, VLRJUR_ACO, ID_EXTERNO)
SELECT
CONTRATOFIXO,
(row_number() over (partition by CONTRATOFIXO order by CONTRATOFIXO, DATA)) AS NACORDO_ACO,
NUM_PARC_ABERTO AS PARCELA_ACO,
DATA AS DTACORDO_ACO,
NUM_PARCELAS AS PLANO_ACO,
TOTAL AS VLRACORDO_ACO,
DATA AS VENC_ACO,
STATUS,
PRINCIPAL,
MULTA,
JUROS,
ID_ACORDO
FROM ACORDO_RIACHUELO_CAR10 A
INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) COLLATE SQL_Latin1_General_CP1_CI_AS
LEFT JOIN CAD_ACO C ON B.CONTRATOFIXO = C.CONTRATO_FIN
--CROSS APPLY (SELECT TOP 1 VENCIMENTO FROM ACORDO_PARCELAS_SEMPARAR_CAR4 D WHERE D.ID_ACORDO = A.ID_ACORDO ORDER BY VENCIMENTO) D
WHERE C.CONTRATO_FIN IS NULL
GO

--DELETE C FROM ACORDO_RIACHUELO_CAR10 A
--JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) COLLATE SQL_Latin1_General_CP1_CI_AS
--JOIN CAD_ACO C ON B.CONTRATOFIXO = C.CONTRATO_FIN