SELECT * 
	INTO ACORDO_PARCELAS_RIACHUELO_CAR10
FROM OPENQUERY (CS2,'        
SELECT DISTINCT 
	D.NUM_CONTRATO AS CONTRATO_ORIGINAL, 
	C.CPF, 
	A.ID_FUNCIONARIO,
	A.DATA,
	B.*
FROM ACORDO A JOIN PARCELA B ON A.ID_ACORDO = B.ID_ACORDO
  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
  AND C.ID_CARTEIRA=''30''
  AND C.STATUS IN (''0'',''4'',''3'',''5'')
    JOIN  PARC_GERAL D ON C.ID_CONTR = D.ID_CONTR
;')
GO

--DROP TABLE ACORDO_PARCELAS_RIACHUELO_CAR10

	update ACORDO_PARCELAS_RIACHUELO_CAR10 set STATUS = 0 where STATUS <> 3
	GO
	update ACORDO_PARCELAS_RIACHUELO_CAR10 set STATUS = 4 where STATUS = 3
	GO

DROP TABLE ACORDO_PARCELAS_RIACHUELO_CAR10_INSERT
with cte
as (
SELECT
B.CONTRATO_FIN,
NACORDO_ACO,
NUM_PARC AS PARCELA_ACOP,
'A' AS TIPO_PARCACO,
B.PLANO_ACO AS PLANO_ACOP,
TOTAL AS VALOR_ACOP,
VENCIMENTO AS VENC_ACOP,
STATUS AS COD_STPA,
PRINCIPAL_O AS VLRPRI_ACOP,
JUROS_O AS VLRJUR_ACOP,
MULTA_O AS VLRMUL_ACOP--,row_number() over (partition by B.CONTRATO_FIN, B.NACORDO_ACO, NUM_PARC order by NACORDO_ACO) as SEQNUM
FROM ACORDO_PARCELAS_RIACHUELO_CAR10  A
INNER JOIN CAD_IDCONTRATO C ON C.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) collate SQL_Latin1_General_CP1_CI_AS
INNER JOIN CAD_ACO AS B ON C.CONTRATOFIXO = B.CONTRATO_FIN AND B.ID_EXTERNO = A.ID_ACORDO 
)
select * 
into ACORDO_PARCELAS_RIACHUELO_CAR10_INSERT
from cte
--where seqnum = 1
GO

INSERT INTO CAD_ACOP (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACOP, TIPO_PARCACO, PLANO_ACOP, VALOR_ACOP, VENC_ACOP, COD_STPA, VLRPRI_ACOP, VLRJUR_ACOP, VLRMUL_ACOP)
SELECT A.CONTRATO_FIN, A.NACORDO_ACO, A.PARCELA_ACOP, A.TIPO_PARCACO, A.PLANO_ACOP, A.VALOR_ACOP, A.VENC_ACOP, A.COD_STPA, A.VLRPRI_ACOP, A.VLRJUR_ACOP, A.VLRMUL_ACOP 
FROM ACORDO_PARCELAS_RIACHUELO_CAR10_INSERT A
LEFT JOIN CAD_ACOP B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.NACORDO_ACO = B.NACORDO_ACO AND A.PARCELA_ACOP = B.PARCELA_ACOP
WHERE B.CONTRATO_FIN IS NULL
GO

--DELETE A FROM CAD_ACOP A JOIN ACORDO_PARCELAS_RIACHUELO_CAR10_INSERT B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.NACORDO_ACO = B.NACORDO_ACO AND A.PARCELA_ACOP = B.PARCELA_ACOP