SELECT 
A.CONTRATO_ORIGINAL AS CONTRATO_FIN,
A.CPF,
CASE 
	WHEN ID_CARTEIRA = 214 THEN 110
	ELSE 84
END AS COD_CLI,
CASE
	WHEN ID_CARTEIRA = 200 THEN 1
	WHEN ID_CARTEIRA = 201 THEN 2
	WHEN ID_CARTEIRA = 202 THEN 3
	WHEN ID_CARTEIRA = 203 THEN 4
	WHEN ID_CARTEIRA = 204 THEN 5
	WHEN ID_CARTEIRA = 205 THEN 6
	WHEN ID_CARTEIRA = 206 THEN 7
	WHEN ID_CARTEIRA = 207 THEN 8
	WHEN ID_CARTEIRA = 208 THEN 9
	WHEN ID_CARTEIRA = 209 THEN 10
	WHEN ID_CARTEIRA = 210 THEN 11
	WHEN ID_CARTEIRA = 211 THEN 12
	WHEN ID_CARTEIRA = 212 THEN 13
	WHEN ID_CARTEIRA = 213 THEN 14
	WHEN ID_CARTEIRA = 214 THEN 1
END AS COD_CAR, 
'P' AS TIPO_FIN,
coalesce(A.PRINCIPAL_ATUAL, a.principal, 0) AS VALOR_FIN,
1 AS MOEDA_FIN,
PRIM_VENC_ORIGINAL,
98 AS COD_STCB
INTO AUXSRC.dbo.CAD_DEVF_CARREFOUR_INSERT
FROM CAD_DEVF_CARREFOUR A
--INNER JOIN AUX_DEVF B ON B.CONTRATO_FIN = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
LEFT JOIN CAD_DEVF C ON A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS = C.CONTRATO_FIN
WHERE C.CONTRATO_FIN IS NULL
GO

--DROP TABLE CAD_DEVF_INSERT_RIACHUELO_CAR11

INSERT INTO CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN, VENC_FIN, COD_STCB)
SELECT * FROM AUXSRC.dbo.CAD_DEVF_CARREFOUR_INSERT
GO

--DELETE FROM CAD_DEVF WHERE CONTRATO_FIN = '44487602ID'

--CÓDIGO DO CLIENTE -> NUM_CONTRATO DA TABELA CONTRATO
--COD_CREDOR da tbl SEM_PARAR_RECUPERA_CONTRATO
--NUM_ACORDO -> COD_PARC DA ACORDO_SEM_PARAR_RECUPERA

--AUX_SEMPARAR_SYSOPEN