SELECT *  
INTO ACORDO_CARREFOUR
FROM OPENQUERY (CS2,'        
SELECT DISTINCT C.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', B.COD_ACORDO_INTERNO AS ''NUM_ACORDO'', A.* 
FROM ACORDO A 
  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
  LEFT JOIN ACORDO_CARREFOUR B ON A.ID_ACORDO = B.ID_ACORDO
WHERE C.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
AND C.STATUS IN (0,4,3,5) 
')
GO

SELECT *  
INTO ACORDO_CARREFOUR_BKP
FROM ACORDO_CARREFOUR
GO
--SELECT DISTINCT B.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', D.COD_PARCE AS ''NUM_ACORDO'', A.* 
--FROM ACORDO A 
--  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--  JOIN PARC_GERAL B ON B.ID_CONTR = A.ID_CONTR
--  JOIN ACORDO_SEM_PARAR_RECUPERA D ON A.ID_ACORDO = D.ID_ACORDO
--WHERE C.ID_CARTEIRA=32
--AND C.STATUS IN (0,4,3,5) 

SELECT DISTINCT CONTRATO_FIN 
INTO ACORDO_CARREFOUR_DELETE
FROM ACORDO_CARREFOUR A
INNER JOIN SRC.DBO.AUX_DEVF B ON B.CONTRATO_FIN = A.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS
GO

DELETE A FROM SRC.dbo.RECIBOCREDOR A
JOIN ACORDO_CARREFOUR_DELETE B ON A.CONTRATO_FIN = B.CONTRATO_FIN
GO

WHILE 1 = 1
BEGIN

DELETE TOP(100000) A FROM SRC.DBO.CAD_ACOP A
JOIN ACORDO_CARREFOUR_DELETE B ON A.CONTRATO_FIN = B.CONTRATO_FIN

IF @@ROWCOUNT < 100000
	BREAK;

END

DELETE A FROM SRC.DBO.CAD_ACO A
JOIN ACORDO_CARREFOUR_DELETE B ON A.CONTRATO_FIN = B.CONTRATO_FIN
GO

--select * from cad_idcontrato where contratofixo = '44487603id'

--SELECT * FROM ACORDO_RIACHUELO_migracao_2

--SELECT * FROM CAD_ACO WHERE CONTRATO_FIN = '44407886ID'

--DELETE FROM CAD_ACO WHERE CONTRATO_FIN = '44082481ID'

	UPDATE ACORDO_CARREFOUR SET [STATUS] = 3 WHERE [STATUS] IN (1,2)
	GO
	UPDATE ACORDO_CARREFOUR SET [STATUS] = 5 WHERE [STATUS] IN (4,6)
	GO
	UPDATE ACORDO_CARREFOUR SET [STATUS] = 9 WHERE [STATUS] IN (7,8)
	GO

INSERT INTO SRC.DBO.CAD_ACO (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACO, DTACORDO_ACO, PLANO_ACO, VLRACORDO_ACO, VENC_ACO, COD_STAC, VLRPRI_ACO, VLRMUL_ACO, VLRJUR_ACO, ID_EXTERNO, RECUP_ACO) --NUMACORDO_ACO,

SELECT DISTINCT
B.CONTRATO_FIN,
--(COALESCE(D.NACORDO_ACO,0) + ((row_number() over (partition by B.CONTRATO_FIN order by B.CONTRATO_FIN, DATA)))) AS NACORDO_ACO,
((row_number() over (partition by B.CONTRATO_FIN order by B.CONTRATO_FIN, DATA))) AS NACORDO_ACO,
COALESCE(NUM_PARC_ABERTO, 1) AS PARCELA_ACO,
DATA AS DTACORDO_ACO,
NUM_PARCELAS AS PLANO_ACO,
TOTAL AS VLRACORDO_ACO,
DATA AS VENC_ACO,
STATUS,
PRINCIPAL,
MULTA,
JUROS,
ID_ACORDO,
--NUM_ACORDO,
ID_FUNCIONARIO
FROM ACORDO_CARREFOUR A
INNER JOIN SRC.DBO.AUX_DEVF B ON B.CONTRATO_FIN = A.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS
--LEFT JOIN CAD_ACO C ON B.CONTRATO_FIN = C.CONTRATO_FIN AND DTACORDO_ACO = [DATA]
--OUTER APPLY (SELECT TOP 1 NACORDO_ACO FROM CAD_ACO D WHERE B.CONTRATO_FIN = D.CONTRATO_FIN ORDER BY NACORDO_ACO DESC) D
--WHERE C.CONTRATO_FIN IS NULL
GO

--SELECT * FROM CAD_IDCONTRATO WHERE CONTRATO_ORIGINAL = '100340008'

--SELECT * FROM ACORDO_RIACHUELO_migracao_2
--WHERE CONTRATO_ORIGINAL = '100340008'

--SELECT *  
--INTO ACORDO_RIACHUELO_migracao_2
--FROM OPENQUERY (CS2,'        
--SELECT DISTINCT C.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', B.NRPROPOSTA, A.* 
--FROM ACORDO A 
--JOIN ACORDO_RIACHUELO_migracao_2 B ON A.ID_ACORDO = B.ID_ACORDO
--  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--WHERE C.ID_CARTEIRA=''10''
--AND C.STATUS IN (''0'',''4'',''3'',''5'') 
--')

--SELECT NUMACOCON_ACO
-- ,* FROM CAD_ACO

-- SELECT NUMACOCON_ACO, A.* FROM CAD_ACO A
-- JOIN 

	UPDATE A SET COD_STPA = 3 FROM SRC.DBO.CAD_DEVP A
	JOIN SRC.DBO.AUX_DEVF B ON A.CONTRATO_FIN = B.CONTRATO_FIN
	JOIN ACORDO_CARREFOUR C ON B.CONTRATO_ORIGINAL = CONVERT(varchar,C.CONTRATO_ORIGINAL) COLLATE SQL_Latin1_General_CP1_CI_AS
	WHERE C.STATUS = 0