SELECT * 
	INTO ACORDO_PARCELAS_CARREFOUR
FROM OPENQUERY (CS2,'        
SELECT DISTINCT 
	C.NUM_CONTRATO AS CONTRATO_ORIGINAL, 
	C.CPF, 
	A.ID_FUNCIONARIO,
	A.DATA,
	B.*
FROM ACORDO A JOIN PARCELA B ON A.ID_ACORDO = B.ID_ACORDO
  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
  AND C.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
  AND C.STATUS IN (0,4,3,5)
;')
GO

--DELETE FROM CAD_ACOP WHERE CONTRATO_FIN = '44082481ID'

	update ACORDO_PARCELAS_CARREFOUR set STATUS = 0 where STATUS <> 3
	GO
	update ACORDO_PARCELAS_CARREFOUR set STATUS = 4 where STATUS = 3
	GO

DROP TABLE ACORDO_PARCELAS_CARREFOUR_INSERT
GO

with cte
as (
SELECT
B.CONTRATO_FIN,
NACORDO_ACO,
NUM_PARC AS PARCELA_ACOP,
'A' AS TIPO_PARCACO,
B.PLANO_ACO AS PLANO_ACOP,
TOTAL AS VALOR_ACOP,
VENCIMENTO AS VENC_ACOP,
STATUS AS COD_STPA,
PRINCIPAL_O AS VLRPRI_ACOP,
JUROS_O AS VLRJUR_ACOP,
MULTA_O AS VLRMUL_ACOP,
DATA_PGTO
,row_number() over (partition by B.CONTRATO_FIN, B.NACORDO_ACO, NUM_PARC order by NACORDO_ACO) as SEQNUM
FROM ACORDO_PARCELAS_CARREFOUR  A
INNER JOIN src.dbo.CAD_ACO AS B ON A.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_FIN AND A.ID_ACORDO = TRY_CONVERT(INT, B.ID_EXTERNO)
--where a.CONTRATO_ORIGINAL = '00000239231'
)
select * 
into ACORDO_PARCELAS_CARREFOUR_INSERT
from cte
where seqnum = 1
ORDER BY CONTRATO_FIN, NACORDO_ACO, VENC_ACOP
GO

DELETE A 
--SELECT DISTINCT A.*
--INTO CAD_ACOP_BKP_CARREFOUR 
FROM CAD_ACOP A  
JOIN ACORDO_PARCELAS_CARREFOUR_INSERT B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.NACORDO_ACO = B.NACORDO_ACO

	--INSERT INTO SRC.Dbo.CAD_ACOP (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACOP, TIPO_PARCACO, PLANO_ACOP, VALOR_ACOP, VENC_ACOP, COD_STPA, VLRPRI_ACOP, VLRJUR_ACOP, VLRMUL_ACOP)
	--SELECT DISTINCT CONTRATO_FIN, NACORDO_ACO, PARCELA_ACOP, TIPO_PARCACO, PLANO_ACOP, VALOR_ACOP, VENC_ACOP, COD_STPA, VLRPRI_ACOP, VLRJUR_ACOP, VLRMUL_ACOP
	--FROM ACORDO_PARCELAS_CARREFOUR_INSERT

SELECT DISTINCT A.CONTRATO_FIN, A.NACORDO_ACO, A.PARCELA_ACOP, A.TIPO_PARCACO, A.PLANO_ACOP, A.VALOR_ACOP, A.VENC_ACOP, A.COD_STPA, A.VLRPRI_ACOP, A.VLRJUR_ACOP, A.VLRMUL_ACOP 
INTO ACORDO_PARCELAS_CARREFOUR_INSERT_FINAL
FROM ACORDO_PARCELAS_CARREFOUR_INSERT A
--LEFT JOIN SRC.Dbo.CAD_ACOP B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.NACORDO_ACO = B.NACORDO_ACO AND A.PARCELA_ACOP = B.PARCELA_ACOP
--WHERE B.CONTRATO_FIN IS NULL
GO

SELECT *, row_number() over (ORDER BY contrato_fin, nacordo_aco, parcela_acop) as ID
INTO AUXSRC.dbo.ACORDO_PARCELAS_CARREFOUR_INSERT_FINAL_FINAL
FROM ACORDO_PARCELAS_CARREFOUR_INSERT

CREATE CLUSTERED INDEX CL_IX  on AUXSRC.dbo.ACORDO_PARCELAS_CARREFOUR_INSERT_FINAL_FINAL(ID) 
GO

--select a.* from ACORDO_PARCELAS_CARREFOUR_INSERT a
----left join cad_aco b on a.CONTRATO_FIN = b.CONTRATO_FIN
--where not exists (select 1 from cad_aco b where a.CONTRATO_FIN = b.CONTRATO_FIN and a.NACORDO_ACO = b.NACORDO_ACO)

--select * from cad_aco where contrato_fin = '00000239231         '

--select * from acordo_carrefour where contrato_original = '00000239231         '

--select * from ACORDO_PARCELAS_CARREFOUR where contrato_original = '00000239231         '
----3516518

DECLARE @VLR_INI INT = 1, @VLR_FINAL INT = 10000
WHILE 1 = 1
BEGIN

	INSERT INTO SRC.Dbo.CAD_ACOP (CONTRATO_FIN, NACORDO_ACO, PARCELA_ACOP, TIPO_PARCACO, PLANO_ACOP, VALOR_ACOP, VENC_ACOP, COD_STPA, VLRPRI_ACOP, VLRJUR_ACOP, VLRMUL_ACOP)
	SELECT A.CONTRATO_FIN, A.NACORDO_ACO, A.PARCELA_ACOP, A.TIPO_PARCACO, A.PLANO_ACOP, A.VALOR_ACOP, A.VENC_ACOP, A.COD_STPA, A.VLRPRI_ACOP, A.VLRJUR_ACOP, A.VLRMUL_ACOP 
	FROM AUXSRC.dbo.ACORDO_PARCELAS_CARREFOUR_INSERT_FINAL_FINAL A
	WHERE ID BETWEEN @VLR_INI AND @VLR_FINAL

	IF @@ROWCOUNT = 0
		BREAK;

	SET @VLR_INI = @VLR_INI + 10000;
	SET @VLR_FINAL = @VLR_FINAL + 10000;

	PRINT @VLR_FINAL;

END
GO

INSERT INTO SRC.dbo.RECIBOCREDOR (CONTRATO_FIN, TIPO_PARC, PARCELA_PARC, DATA_PAGTO, VALOR_PARC, NACORDO_ACO)
SELECT A.CONTRATO_FIN, TIPO_PARCACO, PARCELA_ACOP, DATA_PGTO, VALOR_ACOP, A.NACORDO_ACO
FROM [dbo].[ACORDO_PARCELAS_CARREFOUR_INSERT] A
--LEFT JOIN RECIBOCREDOR B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.PARCELA_ACOP = B.PARCELA_PARC AND A.NACORDO_ACO = B.NACORDO_ACO
WHERE COD_STPA = 4 --AND B.CONTRATO_FIN IS NULL

--DELETE C
----SELECT C.* 
----INTO CAD_ACO_BKP_SEMPARAR
--FROM ACORDO_RIACHUELO_migracao_2 A
--INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) COLLATE SQL_Latin1_General_CP1_CI_AS
--INNER JOIN CAD_ACO C ON B.CONTRATOFIXO = C.CONTRATO_FIN

--SELECT * 
--	INTO ACORDO_PARCELAS_RIACHUELO_migracao_2
--FROM OPENQUERY (CS2,'        
--SELECT DISTINCT 
--	C.NUM_CONTRATO AS CONTRATO_ORIGINAL, 
--	C.CPF, 
--	A.ID_FUNCIONARIO,
--	A.DATA,
--	B.*
--FROM ACORDO A JOIN PARCELA B ON A.ID_ACORDO = B.ID_ACORDO
--  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--  AND C.ID_CARTEIRA=''10''
--  AND C.STATUS IN (''0'',''4'',''3'',''5'')
--;')
--GO