--select * from cad_idcontrato where cpf_dev = '11037365000107'
----44044308ID
----13640055

----44034290ID
----11408203

--select * from cad_devf where contrato_fin = '44034290ID'

--select * from cad_devp where contrato_fin = '44071015ID'

--select * from CAD_DEVF_RIACHUELO_migracao_2 where NUM_CONTRATO = '8171964'

--select * from CAD_DEVF_RIACHUELO_migracao_2 where cpf like '%27025997889'

--select * from CAD_DEVP_RIACHUELO_migracao_2 where CONTRATO_ORIGINAL = '8820653'

--select * from ACORDO_RIACHUELO_migracao_2 where CONTRATO_ORIGINAL = '11408203'

--select * from cad_aco where contrato_fin = '44034290ID'

--select * from ACORDO_PARCELAS_RIACHUELO_migracao_2 where CONTRATO_ORIGINAL = '11408203'

--select * from cad_acop where contrato_fin = '44034290ID'

--DELETE FROM CAD_ACOP WHERE CONTRATO_FIN = '44034290ID'
--DELETE FROM CAD_ACO WHERE CONTRATO_FIN = '44034290ID'

--/*
--4562967609 - pagamento da 1ª parcela no acordo 2 não baixada

--select * from ACORDO_PARCELAS_RIACHUELO_migracao_2 where CONTRATO_ORIGINAL = '13640055'
--select * from cad_acop where contrato_fin = '44044308ID'
--*/

--SELECT * 
-- --INTO TOKEN_RIACHUELO_migracao_2
--FROM OPENQUERY (CS2,'        
--SELECT
--A.* 
--FROM SEM_PARAR_RECUPERA_CONTRATO A
--  JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--WHERE C.ID_CARTEIRA=''26''
--AND C.STATUS IN (''0'',''4'',''3'',''5'') 
--;')

--SEM_PARAR_RECUPERA_CONTRATO

--INSERT INTO AUX_REMESSA_TOKEN
--SELECT COD_CREDOR, DES_REGIS, CODIGO_TOKEN FROM TOKEN_RIACHUELO_migracao_2

--UPDATE A SET NUMACORDO_ACO = B.COD_PARCE FROM CAD_ACO A
--JOIN NUMACORDO_RIACHUELO_migracao_2 B ON TRY_CONVERT(INT,A.ID_EXTERNO) = B.ID_ACORDO

--select * from NUMACORDO_RIACHUELO_migracao_2

--select * from ACORDO_RIACHUELO_migracao_2

--DELETE B FROM ACORDO_PARCELAS_RIACHUELO_migracao_2  A
--INNER JOIN CAD_IDCONTRATO C ON C.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) collate SQL_Latin1_General_CP1_CI_AS
--INNER JOIN CAD_ACOP AS B ON C.CONTRATOFIXO = B.CONTRATO_FIN

--DELETE B FROM ACORDO_RIACHUELO_migracao_2  A
--INNER JOIN CAD_IDCONTRATO C ON C.CONTRATO_ORIGINAL = CONVERT(varchar,A.CONTRATO_ORIGINAL) collate SQL_Latin1_General_CP1_CI_AS
--INNER JOIN CAD_ACO AS B ON C.CONTRATOFIXO = B.CONTRATO_FIN

--AUX_REMESSA_TOKEN

SELECT * 
into ACIONAMENTOS_CARREFOUR
FROM OPENQUERY (CS2,'
SELECT B.NUM_CONTRATO, B.CPF, A.ID_CONTR, A.SEQ, A.ID_TEL, A.DATA, A.CODIGO, A.MODO,
C.ID_FUNCIONARIO, C.LOGIN, C.NOME, C.STATUS, C.CPF_F,
D.MOTIVO, D.AUTORIZACAO,
E.DDD, E.NUMERO,
F.COD, F.HISTORICO, CONVERT(D.MENSAGEM,CHAR(500)) AS ''COMENTARIO''
FROM HISTORICO A
JOIN CONTRATO B ON A.ID_CONTR = B.ID_CONTR
JOIN FUNCIONARIO C ON A.ID_FUNCIONARIO = C.ID_FUNCIONARIO
LEFT JOIN HISTORICO_TEXTO D ON A.ID_CONTR = D.ID_CONTR AND A.SEQ = D.SEQ
LEFT JOIN TELEFONE E ON B.CPF = E.CPF AND A.ID_TEL = E.ID_TEL
JOIN CODIGO F ON A.CODIGO = F.COD
WHERE B.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
AND B.STATUS IN (0,4,3,5)
AND A.DATA >= ''20240921''
ORDER BY A.DATA;')
GO
--JOIN PARC_GERAL G ON G.ID_CONTR = A.ID_CONTR

SELECT * 
INTO ACIONAMENTOS_CARREFOUR_BKP
FROM ACIONAMENTOS_CARREFOUR
GO

update ACIONAMENTOS_CARREFOUR set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf), LEN(cpf))
GO

--DROP TABLE ACIONAMENTOS_CARREFOUR

--SELECT * 
--INTO ACIONAMENTOS_CARREFOUR
--FROM ACIONAMENTOS_CARREFOUR_BKP

--select * from cad_idcontrato where contratofixo = '44324801ID'

--BEGIN TRAN
--SELECT COD, CODIGO, ID_FUNCIONARIO, LOGIN FROM [ACIONAMENTOS_RIACHUELO_migracao_2]
--UPDATE [ACIONAMENTOS_RIACHUELO_migracao_2] SET COD = CODIGO, ID_FUNCIONARIO = LOGIN

--SELECT * FROM ACIONAMENTOS_RIACHUELO_migracao_2 WHERE LOGIN = 'luana.dias'

--UPDATE ACIONAMENTOS_RIACHUELO_migracao_2 SET LOGIN = 459 WHERE LOGIN = 'luana.dias'

--DROP TABLE CAD_DEVP_SEMPARAR_VALIDACAO

--PARC_GERAL_SEM_PARAR_RECUPERA
--SELECT *  
----INTO CAD_DEVP_SEMPARAR_VALIDACAO
--FROM OPENQUERY (CS2,'        
--SELECT A.* FROM PARC_GERAL_SEM_PARAR_RECUPERA A
--INNER JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--AND C.CPF LIKE (''%5216374736'')
--WHERE C.ID_CARTEIRA=''26''
--AND C.STATUS IN (''0'',''4'',''3'',''5'')')
--GO

--CÓDIGO DO CLIENTE -> NUM_CONTRATO DA TABELA CONTRATO
--COD_CREDOR da tbl SEM_PARAR_RECUPERA_CONTRATO

--SELECT *  
--INTO AUX_SEM_PARAR_RECUPERA_CONTRATO_SEMPARAR_VALIDACAO
--FROM OPENQUERY (CS2,'        
--SELECT A.* FROM CONTRATO C
--JOIN SEM_PARAR_RECUPERA_CONTRATO A ON C.ID_CONTR = A.ID_CONTR
--AND C.CPF LIKE (''%5216374736'')
--WHERE C.ID_CARTEIRA=''26''
--AND C.STATUS IN (''0'',''4'',''3'',''5'')')
--GO

--SELECT * FROM AUX_SEM_PARAR_RECUPERA_CONTRATO_SEMPARAR_VALIDACAO

--INSERT INTO AUX_SEMPARAR_SYSOPEN (CONTRATO_FIN, COD_CLIENTE, COD_CREDOR, CONTRATO_ORIGINAL)
--SELECT CONTRATOFIXO, DES_REGIS, COD_CREDOR, NUM_CONTRATO
--FROM AUX_SEM_PARAR_RECUPERA_CONTRATO_SEMPARAR_VALIDACAO A
--JOIN CAD_IDCONTRATO B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
--WHERE B.DATA_INCLUSAO = '20240903'

--SP_HELPTEXT STPCAD_ID

--DECLARE @i INT = 0, @ID INT;
--PRINT 'INICIO'
--SELECT @ID = MAX(ID) FROM CAD_ID
--PRINT @ID
--WHILE @i < 6425
--BEGIN
--	EXEC STPCAD_ID;
--	SET @i = @i + 1;
--END
--PRINT 'FIM'
--SELECT @ID = MAX(ID) FROM CAD_ID
--PRINT @ID

--DECLARE @i2 INT = 59241539;
--WHILE @i2 <= (@i2 + 6425)
--BEGIN
--	UPDATE TOP(1) A SET NUMACOCON_ACO = @i2 FROM CAD_ACO A
--	join acordo_carrefour_aux b on a.CONTRATO_FIN = b.contrato_fin
--	WHERE NUMACOCON_ACO IS NULL;
--	SET @i2 = @i2 + 1;
--END

--SP_SHOWINDEX @INDEX_NAME = 'NON_IX_numacocon_aco'
--ID_EXTERNO
--DROP INDEX IX_CAD_ACO_3 ON dbo.CAD_ACO

--CREATE NONCLUSTERED INDEX IX_CADACO_DTACOR ON dbo.CAD_ACO (DTACORDO_ACO) INCLUDE (DTACORDOHORA_ACO,PARCELA_ACO,PLANO_ACO,VLRACORDO_ACO,VENC_ACO,COD_STAC,RECUP_ACO,NUMACORDO_ACO)

--WHILE 1 = 1
--BEGIN 
--	EXEC STPCAD_ID 
--	--UPDATE TOP(1) A SET NUMACOCON_ACO = @ID FROM CAD_ACO A
--	--JOIN ACORDO_CARREFOUR B ON TRY_CONVERT(INT,A.ID_EXTERNO) = B.ID_ACORDO
--	--WHERE NUMACOCON_ACO IS NULL

--	UPDATE TOP(1) A SET NUMACOCON_ACO = (SELECT MAX(ID) FROM CAD_ID) FROM CAD_ACO A
--	join acordo_carrefour_aux b on a.CONTRATO_FIN = b.contrato_fin
--	WHERE NUMACOCON_ACO IS NULL

--	IF @@ROWCOUNT = 0
--		BREAK;

--END

--DROP TABLE ACIONAMENTOS_RIACHUELO_MIGRACAO
--SELECT * 
--INTO ACIONAMENTOS_RIACHUELO_MIGRACAO
--FROM ACIONAMENTOS_RIACHUELO_MIGRACAO_BKP