SELECT *  
INTO ACORDO_BOLETO_RIACHUELO_MIGRACAO
FROM OPENQUERY (CS2,'        
SELECT DISTINCT B.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', A.* 
FROM ACORDO_RIACHUELO A
  JOIN ACORDO D ON D.ID_ACORDO = A.ID_ACORDO
  JOIN CONTRATO C ON C.ID_CONTR = D.ID_CONTR
  JOIN PARC_GERAL B ON B.ID_CONTR = D.ID_CONTR
WHERE C.ID_CARTEIRA IN (30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 300, 301, 302, 303, 304, 305, 306, 307)
AND C.STATUS IN (0,4,3,5) 
')
GO

SELECT * 
INTO ACORDO_BOLETO_RIACHUELO_MIGRACAO_FILTRADO
FROM ACORDO_BOLETO_RIACHUELO_MIGRACAO
WHERE UUID_ACORDO IS NOT NULL
GO

--SELECT B.* FROM SRC.dbo.CAD_ACO A
--JOIN ACORDO_BOLETO_RIACHUELO_MIGRACAO_FILTRADO B ON B.ID_ACORDO = TRY_CONVERT(INT,A.ID_EXTERNO)
--GO

UPDATE A SET ID_EXTERNO = UUID_ACORDO FROM SRC.dbo.CAD_ACO A
JOIN ACORDO_BOLETO_RIACHUELO_MIGRACAO_FILTRADO B ON B.ID_ACORDO = TRY_CONVERT(INT,A.ID_EXTERNO)
GO