CREATE CLUSTERED INDEX CL_IX ON ACIONAMENTOS_CARREFOUR (NUM_CONTRATO)
GO

SELECT A.*
INTO ACIONA_BKP_20241223
FROM SRC.DBO.ACIONA A
JOIN ACIONAMENTOS_CARREFOUR C ON a.CONTRATO_fin = C.NUM_CONTRATO collate SQL_Latin1_General_CP1_CI_AS
GO

WHILE 1 = 1
BEGIN

DELETE top(100000) A FROM SRC.DBO.ACIONA A
JOIN ACIONAMENTOS_CARREFOUR C ON a.CONTRATO_fin = C.NUM_CONTRATO collate SQL_Latin1_General_CP1_CI_AS

IF @@ROWCOUNT < 100000
	BREAK;

END
GO

--CREATE nonCLUSTERED INDEX NO_IX_ORIGINAL ON CAD_IDCONTRATO (CONTRATO_ORIGINAL)
--GO

SELECT DISTINCT
num_contrato AS CONTRATO_FIN
,DATA AS DATA_ACIONA
,COD AS COD_ACIONAMENTO
,ID_FUNCIONARIO AS COD_RECUP
,LEFT(DDD,3) AS DDD_TEL
,RIGHT(NUMERO,9) AS TEL_TEL
,COMENTARIO
INTO ACIONAMENTOS_CARREFOUR_INSERT
FROM ACIONAMENTOS_CARREFOUR A

INSERT INTO SRC.DBO.ACIONA(
CONTRATO_FIN
,DATA_ACIONA
,COD_ACIONAMENTO
,COD_RECUP
,DDD_TEL
,TEL_TEL
,AGENDA_ACIONA
)
SELECT * FROM ACIONAMENTOS_CARREFOUR_INSERT
--SELECT DISTINCT
--B.CONTRATOFIXO AS CONTRATO_FIN
--,DATA AS DATA_ACIONA
--,COD AS COD_ACIONAMENTO
--,ID_FUNCIONARIO AS COD_RECUP
--,LEFT(DDD,3) AS DDD_TEL
--,RIGHT(NUMERO,9) AS TEL_TEL
--,COMENTARIO
--FROM ACIONAMENTOS_CARREFOUR A
--JOIN SRC.dbo.CAD_IDCONTRATO B ON A.NUM_CONTRATO = B.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
--WHERE --ID_FUNCIONARIO NOT IN (2134,2135,2140) AND
--COD NOT IN (111)

--select * from api.LOG_REQUISICOES_EXTERNAS(Nolock)
--where ID_LOG_REQUISICAO = 1157069