select * from cad_devp where CONTRATO_FIN = '42675865ID'

select * from cad_devf where CONTRATO_FIN = '42675865ID'

select * from CAD_IDCONTRATO where CONTRATOFIXO = '42675865ID'

select * from AUXSRC.dbo.CAD_DEVP_GETNET_AUX_aux_2 where CONTRATO_ORIGINAL = '0009622427'

SELECT * FROM OPENQUERY (CS2,'
SELECT A.NOME, A.CPF, A.RG, A.SEXO, A.DATA_NASC, A.ESTADO_CIVIL, A.NOME_PAI, A.NOME_MAE, A.LOCAL_TRABALHO, A.PRINCIPAL_ATUAL, A.PRIM_VENC_ORIGINAL, A.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'',
B.NUM_CONTRATO AS ''FATURA'', B.VENC, B.VALOR, B.VALOR_CHEIO, B.VALOR_ORIGINAL, B.STATUS AS ''ST_PARCELAS'',
C.RUA, C.NUMERO AS ''NUMERO_ENDEREO'', C.COMPL, C.BAIRRO, C.CIDADE, C.ESTADO, C.CEP, C.STATUS AS ''ST_ENDERECO'', C.ID_FUNCIONARIO AS ''FUNC_ENDERECO'', C.DATA_CRIACAO AS ''CRI_ENDERECO'', C.DATA_ALT,
D.DDD, D.NUMERO AS ''NUMERO_TELEFONE'', D.STATUS AS ''ST_TELEFONE'', D.TIPO, D.ORIGEM, D.ULTIMA_ATUALIZ, D.ID_FUNCIONARIO AS ''FUNC_TELEFONE'', D.DATA_CRIACAO AS ''CRI_TELEFONE'',
E.ID_FUNCIONARIO AS ''FUNC_MAIL'', E.EMAIL, E.STATUS AS ''ST_EMAIL'', E.ULTIMA_ATUALIZ AS ''ULT_ATUA_E-MAIL'', D.ORIGEM AS ''ORIGEM_EMAIL'', D.DATA_CRIACAO AS ''DT_CRIACAO_EMAIL''
FROM CONTRATO A JOIN PARC_GERAL B ON A.ID_CONTR = B.ID_CONTR
LEFT JOIN ENDERECO C ON A.CPF = C.CPF
LEFT JOIN TELEFONE D ON A.CPF = D.CPF
LEFT JOIN EMAIL E ON A.CPF = E.CPF
WHERE A.ID_CARTEIRA=''11''
AND A.ID_CONTR=''16228651''
AND A.STATUS IN (''0'',''4'',''3'',''5'')
;')

SELECT * 
--into AUXSRC.dbo.CAD_DEVP_GETNET_aux_2
FROM OPENQUERY (CS2,'SELECT B.NUM_CONTRATO AS ''CONTRATO_ORIGINAL'', A.* FROM PARC_GERAL A
JOIN CONTRATO B ON A.ID_CONTR = B.ID_CONTR
WHERE A.ID_CONTR=''16056995''
;')

drop table AUXSRC.dbo.CAD_DEVP_GETNET_aux_2

SELECT * 
into CAD_DEVF2_2_GETNET_DATACARGA_2
FROM OPENQUERY (CS2,'SELECT * FROM CONTRATO
WHERE ID_CARTEIRA=''11''
AND STATUS IN (''0'',''4'',''3'',''5'')
;')



SELECT * FROM CAD_CAR WHERE COD_CLI = 136



SELECT * FROM CAD_DEVF WHERE CPF_DEV = '08102222808'