--DECLARE @VLRINI INT = 11001, @VLRFIM INT = 12000

--WHILE 1 = 1
--BEGIN
--	insert into CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN)
--	SELECT CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN
--	FROM AUXSRC.DBO.ACORDOS_GETNET_AUX_AUX_2 
--	WHERE ID BETWEEN @VLRINI AND @VLRFIM

--	IF @@ROWCOUNT < 1000
--		BREAK;

--	SET @VLRINI = @VLRINI + 1000;
--	SET @VLRFIM = @VLRFIM + 1000;
--END

DECLARE @VLRINI INT = 323001, @VLRFIM INT = 333000

WHILE 1 = 1
BEGIN
	--insert into CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN)
	--SELECT CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN
	--FROM AUXSRC.DBO.ACORDOS_GETNET_AUX_AUX_2 
	--WHERE ID BETWEEN @VLRINI AND @VLRFIM

	INSERT INTO CAD_DEVP (CONTRATO_FIN, PARCELA_PARC, TIPO_PARC, VENC_PARC, VALOR_PARC, COD_STPA)
	SELECT
	CONTRATO_FIN,
	NUM_PARC2 AS PARCELA_PARC,
	TIPO_PARC,
	VENC_PARC,
	VALOR_PARC,
	COD_STPA
	FROM CAD_DEVP4_AJUSTE_GETNET_2_final

	SELECT * FROM CAD_DEVP2_AJUSTE_GETNET_2_final WHERE CONTRATO_FIN = '42355090ID'

	DELETE A FROM CAD_DEVP2_AJUSTE_GETNET_2_final A INNER JOIN CAD_DEVP B ON A.CONTRATO_FIN = B.CONTRATO_FIN

	FROM AUXSRC.dbo.CAD_DEVP_GETNET_AUX_aux_2 A
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
	INNER JOIN AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2] C ON B.CONTRATOFIXO = C.CONTRATOFIXO
	--WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'
	WHERE ID BETWEEN @VLRINI AND @VLRFIM

	IF @@ROWCOUNT < 1
		BREAK;

	SET @VLRINI = @VLRINI + 10000;
	SET @VLRFIM = @VLRFIM + 10000;
END

select * from AUXSRC.dbo.CAD_DEVP_GETNET_AUX_aux_2