INSERT INTO CAD_DEVP (CONTRATO_FIN, PARCELA_PARC, TIPO_PARC, VENC_PARC, VALOR_PARC, COD_STPA)
	SELECT
	B.CONTRATOFIXO AS CONTRATO_FIN,
	A.NUM_PARC2 AS PARCELA_PARC,
	'P' AS TIPO_PARC,
	A.VENC AS VENC_PARC,
	A.VALOR AS VALOR_PARC,
	status as COD_STPA
	FROM CAD_DEVP2_AJUSTE_GETNET_2 A
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
	--INNER JOIN AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2] C ON B.CONTRATOFIXO = C.CONTRATOFIXO
	--WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'
	WHERE b.CONTRATOFIXO = '42743074ID'

SELECT
	B.CONTRATOFIXO AS CONTRATO_FIN,
	--A.NUM_PARC2 AS PARCELA_PARC,
	'P' AS TIPO_PARC,
	A.VENC AS VENC_PARC,
	A.VALOR AS VALOR_PARC,
	status as COD_STPA
	INTO CAD_DEVP4_AJUSTE_GETNET_2_AUX
	FROM CAD_DEVP4_GETNET_2 A
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
	WHERE B.DATA_INCLUSAO = '20240813'

	drop table CAD_DEVP2_AJUSTE_GETNET_2_AUX_aux

	SELECT distinct A.* 
	INTO CAD_DEVP4_AJUSTE_GETNET_2_AUX_aux
	FROM CAD_DEVP4_AJUSTE_GETNET_2_AUX A INNER JOIN CAD_DEVF B ON A.CONTRATO_FIN = B.CONTRATO_FIN WHERE B.STATCONT_FIN = 0

	SELECT * FROM CAD_IDCONTRATO WHERE CONTRATOFIXO = '42669885ID'
	SELECT * FROM CAD_IDCONTRATO WHERE CONTRATO_ORIGINAL = '0009654763'

	SELECT * FROM CAD_DEVP2_AJUSTE_GETNET_2 WHERE CONTRATO_ORIGINAL = '0012993852'
	select * from CAD_DEVP2_AJUSTE_GETNET_2_AUX where contrato_fin = '42669885ID'

	0009654763

	select * from CAD_DEVP2_AJUSTE_GETNET_2_final where contrato_fin = '42669885ID'
	select * from CAD_DEVP2_AJUSTE_GETNET_2_AUX where contrato_fin = '42669885ID'