--DECLARE @VLRINI INT = 11001, @VLRFIM INT = 12000

--WHILE 1 = 1
--BEGIN
--	insert into CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN)
--	SELECT CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN
--	FROM AUXSRC.DBO.ACORDOS_GETNET_AUX_AUX_2 
--	WHERE ID BETWEEN @VLRINI AND @VLRFIM

--	IF @@ROWCOUNT < 1000
--		BREAK;

--	SET @VLRINI = @VLRINI + 1000;
--	SET @VLRFIM = @VLRFIM + 1000;
--END

--;disable trigger [TRG_CAD_DEVP_UNIFICADA_IUX] on CAD_DEVP

--;enable trigger [TRG_CAD_DEVP_UNIFICADA_IUX] on CAD_DEVP

DECLARE @VLRINI INT = 1, @VLRFIM INT = 10000

WHILE 1 = 1
BEGIN
	--insert into CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN)
	--SELECT CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN
	--FROM AUXSRC.DBO.ACORDOS_GETNET_AUX_AUX_2 
	--WHERE ID BETWEEN @VLRINI AND @VLRFIM

	INSERT INTO CAD_DEVP (CONTRATO_FIN, PARCELA_PARC, TIPO_PARC, VENC_PARC, VALOR_PARC)
	SELECT
	B.CONTRATOFIXO AS CONTRATO_FIN,
	A.NUM_PARC2 AS PARCELA_PARC,
	'P' AS TIPO_PARC,
	A.VENC AS VENC_PARC,
	A.VALOR AS VALOR_PARC
	FROM CAD_DEVP3_INSERT_AUX_GETNET_2 A
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate Latin1_General_CI_AS
	--INNER JOIN AUXSRC.DBO.[CADDEV_GETNET_CAD_IDCONTRATO_aux_2] C ON B.CONTRATOFIXO = C.CONTRATOFIXO
	--WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'
	--WHERE ID BETWEEN @VLRINI AND @VLRFIM

	IF @@ROWCOUNT < 1
		BREAK;

	SET @VLRINI = @VLRINI + 10000;
	SET @VLRFIM = @VLRFIM + 10000;
END

--;DISABLE TRIGGER [TRG_CAD_DEVP_UNIFICADA_XXD] ON CAD_DEVP;

--WHILE 1 = 1
--BEGIN

--	DELETE TOP(100000) A FROM CAD_DEVP A
--	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATOFIXO = A.CONTRATO_FIN
--	WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247';

--	IF @@ROWCOUNT < 100000
--		BREAK;

--END

--;ENABLE TRIGGER [TRG_CAD_DEVP_UNIFICADA_XXD] ON CAD_DEVP;