select a.* 
INTO CAD_DEVF_INSERT_GETNET_2
from CAD_DEVF2_2_GETNET_DATACARGA_2 a
left join cad_idcontrato b on a.num_contrato collate SQL_Latin1_General_CP1_CI_AS = b.CONTRATO_ORIGINAL
where b.CONTRATOFIXO is null

SELECT DATA_CARGA, B.CONTRATOFIXO 
INTO AUX2_GETNET_DATACARGA_2
FROM CAD_DEVF2_2_GETNET_DATACARGA_2 A INNER JOIN CAD_IDCONTRATO B ON a.num_contrato collate SQL_Latin1_General_CP1_CI_AS = b.CONTRATO_ORIGINAL
WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'

SELECT B.CONTRATOFIXO, PRIM_VENC_ORIGINAL
INTO CAD_DEVF_AJUSTE_GENET_2
FROM CAD_DEVF2_2_GETNET_DATACARGA_2 A
INNER JOIN cad_idcontrato b on a.num_contrato collate SQL_Latin1_General_CP1_CI_AS = b.CONTRATO_ORIGINAL
WHERE B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'

UPDATE A SET VENC_FIN = PRIM_VENC_ORIGINAL FROM CAD_DEVF A INNER JOIN CAD_DEVF_AJUSTE_GENET_2 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

SELECT * FROM CAD_DEVF A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO LEFT JOIN CAD_DEVF_AJUSTE_GENET_2 C ON  A.CONTRATO_FIN = C.CONTRATOFIXO
WHERE C.CONTRATOFIXO IS NULL AND B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'

update a set cod_stcb = 98 FROM CAD_DEVF A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO LEFT JOIN CAD_DEVF_AJUSTE_GENET_2 C ON  A.CONTRATO_FIN = C.CONTRATOFIXO
WHERE C.CONTRATOFIXO IS NULL AND B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'

update a set STATCONT_FIN = 1 FROM CAD_DEVF A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO LEFT JOIN CAD_DEVF_AJUSTE_GENET_2 C ON  A.CONTRATO_FIN = C.CONTRATOFIXO
WHERE C.CONTRATOFIXO IS NULL AND B.DATA_INCLUSAO = '2024-08-04 21:34:37.247'

select * from cad_devf where cpf_dev = '71019711132'

select * from cad_idcontrato where contratofixo = '42757874ID          '

select statcont_fin, a.* FROM CAD_DEVF A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO 
where (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247') and cod_stcb <> 98
and statcont_fin = 1

insert into cad_idcontrato (CONTRATO_ORIGINAL, CPF_DEV, DATA_INCLUSAO)
select num_contrato, cpf, '20240811'
from CAD_DEVF_INSERT_GETNET_2

SELECT B.CONTRATOFIXO, CPF collate SQL_Latin1_General_CP1_CI_AS as cpf, 142 as oi, 1 as oi2, 'P' as oi3, principal, 1 as oi4, prim_venc_original, 0 as oi5
INTO CAD_DEVF_INSERT5_FINAL_GETNET_2
	FROM CAD_DEVF5_GETNET2 a
	INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.num_contrato collate SQL_Latin1_General_CP1_CI_AS
WHERE B.DATA_INCLUSAO = '20240813'

SELECT A.* 
INTO ACORDOS_3_INSERT_GETNET_2
FROM ACORDOS_3_GETNET_2 A INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS WHERE B.DATA_INCLUSAO = '20240811'


SELECT A.* 
INTO ACORDOS_PARCELAS_3_INSERT_GETNET_2
FROM ACORDOS_PARCELAS_3_GETNET_2 A INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS WHERE B.DATA_INCLUSAO = '20240811'


	SELECT * FROM CAD_DEVF 

insert into CAD_DEVF(CONTRATO_FIN, CPF_DEV, COD_CLI, COD_CAR, TIPO_FIN, VALOR_FIN, MOEDA_FIN, VENC_FIN, STATCONT_FIN, COD_STCB)
	SELECT *, 98
	FROM CAD_DEVF_INSERT5_FINAL_GETNET_2

	select b.contratofixo, venc, status 
	INTO CAD_DEVP3_AJUSTE_GETNET_2
	from CAD_DEVP3_GETNET_2 a
	inner join cad_idcontrato b on a.contrato_original  collate SQL_Latin1_General_CP1_CI_AS = b.CONTRATO_ORIGINAL

	UPDATE CAD_DEVP4_AJUSTE_GETNET_2_final SET cod_stpa = 7  WHERE cod_stpa IN (0,1)
	UPDATE CAD_DEVP4_AJUSTE_GETNET_2_final SET cod_stpa = 16 WHERE cod_stpa = 2
	UPDATE CAD_DEVP4_AJUSTE_GETNET_2_final SET cod_stpa = 0  WHERE cod_stpa = 3
	UPDATE CAD_DEVP4_AJUSTE_GETNET_2_final SET cod_stpa = 14 WHERE cod_stpa = 5


	UPDATE A SET COD_STPA = B.STATUS FROM CAD_DEVP A INNER JOIN CAD_DEVP3_AJUSTE_GETNET_2 B ON A.CONTRATO_FIN = B.CONTRATOFIXO

	UPDATE A SET COD_STCB = 98 FROM CAD_DEVF A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
	WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247')

	SELECT * FROM ACORDOS_4_GETNET_2

	UPDATE ACORDO5_AJUSTE_GETNET2 SET [STATUS] = 3 WHERE [STATUS] IN (1,2)
	UPDATE ACORDO5_AJUSTE_GETNET2 SET [STATUS] = 5 WHERE [STATUS] IN (4,6)
	UPDATE ACORDO5_AJUSTE_GETNET2 SET [STATUS] = 9 WHERE [STATUS] IN (7,8)

	SELECT DISTINCT B.CONTRATOFIXO, A.[STATUS] 
	INTO ACORDO4_AJUSTE_GETNET2_AUX
	FROM ACORDO4_AJUSTE_GETNET2 A INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS
	WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247')

	SELECT * FROM ACORDO4_AJUSTE_GETNET2 WHERE ID_CONTR = '15778067'

	DROP TABLE ACORDOS_4_AJUSTE_PARCELA_GETNET_2

	SELECT DISTINCT B.CONTRATOFIXO, A.STATUS, vencimento
	INTO ACORDOS_4_AJUSTE_PARCELA_GETNET_2
	FROM ACORDOS_PARCELAS_ajuste_3_GETNET_2 A INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS

	--DELETE A FROM CAD_ACOP A JOIN (
	SELECT *
	--DELETE A 
	FROM CAD_ACO A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO --INNER JOIN ACORDO4_AJUSTE_GETNET2_AUX C ON A.CONTRATO_FIN = C.CONTRATOFIXO
	WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247') --AND COD_STAC IS NULL
	--) B ON A.CONTRATO_FIN = B.CONTRATO_FIN

	SELECT * FROM CAD_ACO WHERE CONTRATO_FIN = '42846568ID'   
	SELECT * FROM CAD_IDCONTRATO WHERE CONTRATOFIXO = '42660619ID          '
	SELECT * FROM CAD_IDCONTRATO WHERE CONTRATO_ORIGINAL = '0011108711'

	SELECT * 
	--UPDATE A SET COD_STPA = STATUS
	FROM CAD_ACOP A INNER JOIN ACORDOS_4_AJUSTE_PARCELA_GETNET_2 B ON A.CONTRATO_FIN = B.CONTRATOFIXO AND VENC_ACOP = VENCIMENTO

	update ACORDOS_PARCELAS_4_AUX_INSERT_GETNET_2 set COD_STPA = 0 where COD_STPA <> 3
	update ACORDOS_PARCELAS_4_AUX_INSERT_GETNET_2 set COD_STPA = 4 where COD_STPA = 3

	SELECT * FROM ACORDOS_PARCELAS_ajuste_3_GETNET_2

	SELECT * FROM CAD_IDCONTRATO WHERE CONTRATOFIXO = '42923588ID'

	0009654763

	SELECT * FROM CAD_DEVP WHERE CONTRATO_FIN = '42751386ID'

	WITH CTE AS (
	SELECT A.*,
	row_number() over (partition by A.CONTRATO_FIN, VENC_PARC order by VENC_PARC) as seqnum
	FROM CAD_DEVP A JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
	JOIN CAD_DEVF C ON A.CONTRATO_FIN = C.CONTRATO_FIN
	WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247') AND C.STATCONT_FIN = 0
	)
	SELECT CONTRATO_FIN, VENC_PARC
	--into CAD_DEVF_DUPLICADAS_BKP_20240811
	INTO AUX_DELETE_CADDEVF_GENET_2
	FROM CTE WHERE SEQNUM > 1 -- AQUI

	SELECT * 
	INTO CAD_DEVP_DUPLICADAS
	FROM CAD_DEVF_DUPLICADAS_BKP_20240811 WHERE SEQNUM = 2

	ALTER TABLE CAD_DEVP_DUPLICADAS DROP COLUMN SEQNUM

	INSERT INTO CAD_DEVP 
	SELECT * FROM CAD_DEVP_DUPLICADAS

	SELECT * FROM CAD_IDCONTRATO WHERE CONTRATOFIXO = '42669885ID'

SELECT * FROM CAD_DEVP WHERE CONTRATO_FIN = '42669885ID'

	DELETE A FROM CAD_DEVP A INNER JOIN AUX_DELETE_CADDEVF_GENET_2 B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.VENC_PARC = B.VENC_PARC

	INSERT INTO 

	SELECT A.* 
	INTO CAD_DEVP3_INSERT_GETNET_2
	FROM CAD_DEVP3_GETNET_2 A INNER JOIN CAD_IDCONTRATO B ON B.CONTRATO_ORIGINAL = A.CONTRATO_ORIGINAL collate SQL_Latin1_General_CP1_CI_AS WHERE B.DATA_INCLUSAO = '20240811'

	select a.cpf from CAD_DEVF_INSERT_GETNET_2 a left join cad_dev b on a.cpf collate SQL_Latin1_General_CP1_CI_AS = b.cpf_dev where b.cpf_dev is null

	update CAD_DEVF_INSERT_GETNET_2 set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))
	update AUXSRC.DBO.[CADDEVEND3_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))
	update AUXSRC.DBO.[CADDEVT3_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))
	update AUXSRC.DBO.[CADDEVE3_GETNET_2] set cpf = SUBSTRING(cpf, PATINDEX('%[^0]%', cpf+'.'), LEN(cpf))

	select distinct CPF, DDD, NUMERO, TIPO, SCORE
	--into [CADDEVT3_GETNET_2]
	from AUXSRC.DBO.[CADDEVT3_GETNET_2]

    insert into cad_dev (cpf_dev, nome_dev)
	select cpf, nome
	from CAD_DEVF5_novos_GETNET2 a
	left join cad_dev b on a.cpf collate SQL_Latin1_General_CP1_CI_AS = b.cpf_dev
	where b.cpf_dev is null

	DELETE A FROM AUXSRC.DBO.[CADDEVT3_GETNET_2] A INNER JOIN CAD_DEV B on a.cpf collate SQL_Latin1_General_CP1_CI_AS = b.cpf_dev
	[CADDEVEND3_GETNET_2]
	[CADDEVE3_GETNET_2]

	with cte as (
	select *
	,row_number() over (partition by cpf order by cpf) as seqnum
	from CAD_DEV_INSERT_GENET_2
	)
	delete from cte where seqnum > 1

	delete from CAD_DEV_INSERT_GENET_2 where nome = 'OLYMPIO E OLYMPIO LTDA'

	select distinct cpf, nome
	into CAD_DEV_INSERT_GENET_2
	from CAD_DEVF_INSERT_GETNET_2

--delete A
--select A.*
--INTO CAD_DEVP_BKP_20240811
FROM CAD_DEVP A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
	WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247')

--SELECT A.* 
UPDATE A SET COD_STPA = 0
FROM CAD_DEVP A INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_FIN = B.CONTRATOFIXO
LEFT JOIN CAD_ACO C ON C.CONTRATO_FIN = A.CONTRATO_FIN
WHERE (b.DATA_INCLUSAO = '20240813') AND COD_STPA = 7
AND C.CONTRATO_FIN IS NULL
