SELECT * FROM CAD_IDCONTRATO WHERE CONTRATO_ORIGINAL = '0010520698'

SELECT * FROM CAD_IDCONTRATO  WHERE CONTRATOFIXO = '42684047ID'

SELECT * FROM CAD_ACO WHERE CONTRATO_FIN = '42684047ID'

SELECT * FROM CAD_ACOP WHERE CONTRATO_FIN = '42835662ID'

SELECT * FROM CAD_DEVP WHERE CONTRATO_FIN = '42835662ID'

SELECT * FROM ACORDOS_4_AJUSTE_PARCELA_GETNET_2 WHERE CONTRATOFIXO = '42835662ID'

SELECT * FROM ACORDO5_AJUSTE_GETNET2 WHERE CONTRATO_ORIGINAL = '0011937193'

SELECT CONTRATOFIXO AS CONTRATO_FIN, TOTAL, PRINCIPAL, MULTA, JUROS 
INTO ACORDO5_AJUSTE_VALOR_GETNET2
FROM ACORDO5_AJUSTE_GETNET2 A
INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247' or b.DATA_INCLUSAO = '20240813')

SELECT CONTRATOFIXO AS CONTRATO_FIN, ID_FUNCIONARIO
INTO ACORDO5_AJUSTE_FUNC_GETNET2
FROM ACORDO5_AJUSTE_GETNET2 A
INNER JOIN CAD_IDCONTRATO B ON A.CONTRATO_ORIGINAL COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
WHERE (b.DATA_INCLUSAO = '20240811' or b.DATA_INCLUSAO = '2024-08-04 21:34:37.247' or b.DATA_INCLUSAO = '20240813')

UPDATE A SET VLRACORDO_ACO = TOTAL, VLRPRI_ACO = PRINCIPAL, VLRMUL_ACO = MULTA, VLRJUR_ACO = JUROS
FROM CAD_ACO A JOIN ACORDO5_AJUSTE_VALOR_GETNET2 B ON A.CONTRATO_FIN = B.CONTRATO_FIN

UPDATE A SET RECUP_ACO = ID_FUNCIONARIO
FROM CAD_ACO A JOIN ACORDO5_AJUSTE_FUNC_GETNET2 B ON A.CONTRATO_FIN = B.CONTRATO_FIN

TOTAL, PRINCIPAL, MULTA, JUROS