--SELECT *  
--INTO AUX_CYBER_REMESSA_CARREFOUR
--FROM OPENQUERY (CS2,'        
--SELECT C.NUM_CONTRATO
--,C.PRINCIPAL
--,C.PRINCIPAL_ATUAL
--,A.COD_PRODUTO
--,A.ID_FILA_SEGMENTADA 
--,A.CONTA_DATA_ABERTURA
--,A.CONTA_BLOQUEIO
--,A.PRODUTO_DESCRICAO
--,A.DIAS_ATRASO
--,A.SCORE14
--,A.SCORE15
--,A.U1DTPRIMACORDO
--,A.DMCURBAL
--,A.U1DTAGDAYS
--,A.CREDOR FROM CONTR_CARREFOUR A
--JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
--WHERE C.WHERE C.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
--AND C.STATUS IN (0,4,3,5) 
--')
--GO

SELECT *  
INTO AUX_CYBER_REMESSA_CARREFOUR
FROM OPENQUERY (CS2,'        
SELECT C.NUM_CONTRATO
,C.PRINCIPAL
,C.PRINCIPAL_ATUAL
,A.COD_PRODUTO
,B.FILA 
,A.CONTA_DATA_ABERTURA
,A.CONTA_BLOQUEIO
,A.PRODUTO_DESCRICAO
,A.DIAS_ATRASO
,A.SCORE14
,A.SCORE15
,A.U1DTPRIMACORDO
,A.DMCURBAL
,A.U1DTAGDAYS
,A.CREDOR FROM CONTR_CARREFOUR A
JOIN CONTRATO C ON C.ID_CONTR = A.ID_CONTR
JOIN CARREFOUR_FILA_SEGMENTADA B ON A.ID_FILA_SEGMENTADA = B.ID_FILA_SEGMENTADA
WHERE C.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
AND C.STATUS IN (0,4,3,5) 
')
GO

DELETE B FROM 
AUX_CYBER_REMESSA_CARREFOUR A
JOIN SRC.dbo.AUX_CYBER_REMESSA B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_FIN

INSERT INTO SRC.dbo.AUX_CYBER_REMESSA (
CONTRATO_FIN
,CODPRODUTO
,FILASEGMENTADA
,ADESAOCONTA
,BLOQUEIOCONTA
,PRODUTO
,U1SCORE14
,U1SCORE15
,U1DTPRIMACORDO
,U1DTAGDAYS
,DESCCREDOR
,VALORPRINCIPAL
,SALDODEVEDOR
,ATRASO_CONGELADO_MIGRADO
)
SELECT NUM_CONTRATO,
COD_PRODUTO
,FILA
,CONTA_DATA_ABERTURA
,CONTA_BLOQUEIO
,PRODUTO_DESCRICAO
,SCORE14
,SCORE15
,REPLACE(CONVERT(CHAR(10), A.U1DTPRIMACORDO, 103), '/', '') 
,A.U1DTAGDAYS
,CREDOR
,PRINCIPAL
,PRINCIPAL_ATUAL
,DIAS_ATRASO
FROM AUX_CYBER_REMESSA_CARREFOUR A
--LEFT JOIN AUX_CYBER_REMESSA B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_FIN
--WHERE B.CONTRATO_FIN IS NULL
--INNER JOIN AUX_DEVF B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL

--SELECT * FROM CAD_DEVF WHERE CONTRATO_FIN = '00006133813'

--DELETE A FROM AUX_CYBER_REMESSA A
--JOIN AUX_CYBER_REMESSA_CARREFOUR B ON B.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = A.CONTRATO_FIN
--JOIN CAD_DEVF C ON A.CONTRATO_FIN = C.CONTRATO_FIN
--WHERE C.COD_CLI IN (84,110)

--UPDATE C SET U1DTPRIMACORDO = REPLACE(CONVERT(CHAR(10), A.U1DTPRIMACORDO, 103), '/', '') 
----SELECT C.U1DTPRIMACORDO
--FROM AUX_CYBER_REMESSA_CARREFOUR A
--INNER JOIN AUX_DEVF B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
--INNER JOIN AUX_CYBER_REMESSA C ON C.CONTRATO_FIN = B.CONTRATO_FIN

--UPDATE C SET ATRASO_CONGELADO_MIGRADO = DIAS_ATRASO 
----SELECT C.U1DTPRIMACORDO
--FROM AUX_CYBER_REMESSA_CARREFOUR A
--INNER JOIN AUX_DEVF B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
--INNER JOIN AUX_CYBER_REMESSA C ON C.CONTRATO_FIN = B.CONTRATO_FIN

--SELECT U1DTPRIMACORDO FROM AUX_CYBER_REMESSA
--WHERE U1DTPRIMACORDO IS NOT NULL

--DELETE C FROM AUX_CYBER_REMESSA_CARREFOUR A
----INNER JOIN AUX_DEVF B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_ORIGINAL
--INNER JOIN SRC.dbo.AUX_CYBER_REMESSA C ON C.CONTRATO_FIN = A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS

SELECT *  
INTO AUX_CYBER_ACORDO_CARREFOUR
FROM OPENQUERY (CS2,'        
SELECT C.NUM_CONTRATO,
A.ID_ACORDO,
A.FUNCIONARIO_ID
FROM ACORDO_CARREFOUR A
JOIN ACORDO B ON A.ID_ACORDO = B.ID_ACORDO
JOIN CONTRATO C ON C.ID_CONTR = B.ID_CONTR
WHERE C.ID_CARTEIRA IN (200,201,202,203,204,205,206,207,208,209,210,211,212,213,214)
AND C.STATUS IN (0,4,3,5) 
')
GO

DELETE A FROM SRC.dbo.AUX_CYBER_ACORDO A
JOIN AUX_CYBER_ACORDO_CARREFOUR B ON B.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = A.CONTRATO_FIN
--JOIN CAD_DEVF C ON A.CONTRATO_FIN = C.CONTRATO_FIN
--WHERE C.COD_CLI IN (84,110)

INSERT INTO SRC.dbo.AUX_CYBER_ACORDO (CONTRATO_FIN, USUARIO, ID_ACORDO)
SELECT 
NUM_CONTRATO,
FUNCIONARIO_ID,
A.ID_ACORDO
FROM AUX_CYBER_ACORDO_CARREFOUR A
--LEFT JOIN AUX_CYBER_ACORDO B ON A.NUM_CONTRATO COLLATE SQL_Latin1_General_CP1_CI_AS = B.CONTRATO_FIN
--WHERE B.CONTRATO_FIN IS NULL