DELETE FROM CAD_DEV, 
DELETE FROM CAD_DEVF (e relacionadas), 
DELETE FROM CAD_DEVP, 
DELETE FROM CAD_ACO, 
DELETE FROM CAD_DEVE, 
DELETE FROM CAD_DEVT, 
DELETE FROM CAD_DEVMAIL, 
DELETE FROM CAD_DEVR, 
DELETE FROM CAD_ACOP, 
DELETE FROM CAD_IDCONTRATO, 
DELETE FROM AUX_DEVF, 
DELETE FROM AUX_SABESP_REMESSA, 
DELETE FROM ACIONA, 
DELETE FROM EVENTO, 
DELETE FROM EVENTO_IMPORTACAO, 
DELETE FROM RECIBOCREDOR, 
DELETE FROM BOLETO 


WHILE 1=1
BEGIN
	DELETE TOP (50000)
	FROM CAD_DEV

	IF (@@ROWCOUNT = 0)
	BEGIN
		BREAK;
	END
END

/*
DESABILITAR TRIGGER PARA LIMPAR A TABELA
--DESABILITA
ALTER TABLE [dbo].[CAD_DEVP] DISABLE TRIGGER [TRG_CAD_DEVP_UNIFICADA_XXD]
GO
--HABILITA
ALTER TABLE [dbo].[CAD_DEVP] ENABLE TRIGGER [TRG_CAD_DEVP_UNIFICADA_XXD]
GO
*/