--TRAZ OS IDOCORRENCIAS QUE PRECISAM SER ALTERADOS(FALTA OS QUE A HRHORAFIM NÃO VEM DA SRC.DeepCenter.ACIONA_BRADESCO_SELECAO, 
--E SIM DA SRC.DeepCenter.TBL_DEEPCENTER_DISCADOR_OLOS_BRADESCO_SELECAO_2)
SELECT
	*
FROM(
	SELECT
		A.CONTRATO_FIN,
		FORMAT(A.DATA_ACIONA, 'yyyy-MM-dd HH:mm:ss') AS DATA_ACIONA,
		CONVERT(VARCHAR(10), C.DTDATAREFERENCIA, 120) + ' ' + CONVERT(VARCHAR(8), C.HRHORAFIM, 108) AS DATA_DEEPCENTER,
		B.CONTRATO_ORIGINAL,
		C.NUMCONTRACT,
		A.COD_ACIONAMENTO,
		C.IDOCORRENCIA AS IDOCORRENCIA_ATUAL,
		D.COD_OCORRENCIA AS IDOCORRENCIA_CORRETO
	FROM
		ACIONA AS A (NOLOCK)
		JOIN AUX_DEVF AS B (NOLOCK) ON A.CONTRATO_FIN = B.CONTRATO_FIN
		JOIN DEEPCENTER.FINAL_ACIONAMENTO AS C (NOLOCK) ON B.CONTRATO_ORIGINAL = C.NUMCONTRACT AND FORMAT(A.DATA_ACIONA, 'yyyy-MM-dd HH:mm:ss') = CONVERT(VARCHAR(10), C.DTDATAREFERENCIA, 120) + ' ' + CONVERT(VARCHAR(8), C.HRHORAFIM, 108)
		JOIN DeepCenter.CONFIG_ACIONAMENTO AS D ON D.COD_ACIONAMENTO = A.COD_ACIONAMENTO
	WHERE 
		CAST(A.DATA_ACIONA AS DATE) = '20250502'
	) AS E
WHERE
	E.IDOCORRENCIA_ATUAL <> E.IDOCORRENCIA_CORRETO


	--ANALISE
	SELECT
	A.CONTRATO_FIN,
	FORMAT(A.DATA_ACIONA, 'yyyy-MM-dd HH:mm:ss') AS DATA_ACIONA,
	--CONVERT(VARCHAR(10), C.DTDATAREFERENCIA, 120) + ' ' + CONVERT(VARCHAR(8), C.HRHORAFIM, 108) AS DATA_DEEPCENTER,
	B.CONTRATO_ORIGINAL,
	--C.NUMCONTRACT,
	A.COD_ACIONAMENTO--,
	--C.IDOCORRENCIA AS IDOCORRENCIA_ATUAL
FROM
	ACIONA AS A (NOLOCK)
	JOIN AUX_DEVF AS B (NOLOCK) ON A.CONTRATO_FIN = B.CONTRATO_FIN
	--JOIN DEEPCENTER.FINAL_ACIONAMENTO AS C (NOLOCK) ON B.CONTRATO_ORIGINAL = C.NUMCONTRACT AND FORMAT(A.DATA_ACIONA, 'yyyy-MM-dd HH:mm:ss') = CONVERT(VARCHAR(10), C.DTDATAREFERENCIA, 120) + ' ' + CONVERT(VARCHAR(8), C.HRHORAFIM, 108)
WHERE 
	A.CONTRATO_FIN = '6131507ID'
	AND CAST(A.DATA_ACIONA AS DATE) = '20250502'
ORDER BY
	FORMAT(A.DATA_ACIONA, 'yyyy-MM-dd HH:mm:ss')

SELECT
	CONVERT(VARCHAR(10), C.DTDATAREFERENCIA, 120) + ' ' + CONVERT(VARCHAR(8), C.HRHORAFIM, 108) AS DATA_DEEPCENTER,
	C.DTDATAREFERENCIA,
	C.HRHORAFIM,
	C.HRHORAINICIO,
	*
FROM
	DEEPCENTER.FINAL_ACIONAMENTO AS C (NOLOCK)
WHERE
	NUMCONTRACT = '3068562752551657CSC'
	AND DTDATAREFERENCIA = '20250502'
ORDER BY
	C.HRHORAFIM


SELECT NUMUNICO, DTDATAREFERENCIA, HRHORAINICIO, NUMCLIENTE, DSIDCALL, IDOCORRENCIA  FROM DEEPCENTER.FINAL_ACIONAMENTO
WHERE NUMCLIENTE = '19285523587' AND DTDATAREFERENCIA = '2025-05-02' AND DSIDCALL = '126804725'

SELECT * FROM ACIONA
WHERE CONTRATO_FIN = '6131507ID' AND FORMAT(DATA_ACIONA, 'yyyy-MM-dd HH:mm') = '2025-05-02 10:42'

SELECT * FROM DeepCenter.CONFIG_ACIONAMENTO WHERE COD_ACIONAMENTO = 8203