
--CONFIGURAÇÃO UTILIZADA NO LIM_ID
SELECT 
    ICP_VALOR_CONFIGURADO, 
    * 
FROM 
    SPR_FUN_CARREGA_CAMPOS_LOG_CONFIGURACAO_PROCESSAMENTO (10166, 11)

    x = lim id
    y = id do menu

4614

--CONFIGURAÇÃO ATUALMENTE UTILIZADA NO LIM_ID
SELECT 
    ICP_VALOR_CONFIGURADO, 
    * 
FROM 
    SPR_FUN_CARREGA_CAMPOS_CONFIGURACAO_PROCESSAMENTO (X, Y)

X = ID da Configuração
Y = ID do Menu
