DECLARE @DataAtual DATE = '2024-09-02';
DECLARE @DataFinal DATE = '2024-09-11';

--CREATE TABLE TBL_LOG_ACIONAMENTO_OLOS (ID INT PRIMARY KEY IDENTITY, NOME VARCHAR(100) NULL, DIA DATE NULL, INICIO DATETIME NULL, FIM DATETIME NULL)

WHILE (@DataAtual <= @DataFinal) AND (DATEPART(HOUR, GETDATE()) >= 21 AND DATEPART(HOUR, GETDATE()) <= 6)
BEGIN

	INSERT INTO TBL_LOG_ACIONAMENTO_OLOS VALUES ('ExecucaoAcionamentoBlocoOlos_WC_DEV_REP', @DataAtual, GETDATE(), NULL)
    EXEC  ExecucaoAcionamentoBlocoOlos_WC_DEV_REP @DATA = @DataAtual, @Reprocessar = 1;
	INSERT INTO TBL_LOG_ACIONAMENTO_OLOS VALUES ('ExecucaoAcionamentoBlocoOlos_WC_DEV_REP', @DataAtual, NULL, GETDATE())

    SET @DataAtual = DATEADD(DAY, 1, @DataAtual);
END;