INSERT INTO AUX_SANTANDERPIC_PARCPROMESSAS (
    CONTRATO_FIN,
    ID_PARCELAPROMESSA,
    ID_PROMESSA,
    NUM_PARCELA,
    TIPO_PAGAMENTO,
    DT_VENCIMENTO,
    DT_EXPIRACAOPARCELA,
    VALOR_PARCELA,
    NOSSO_NUMERO,
    NUM_BANCO,
    NUM_AGENCIA,
    DIG_AGENCIA,
    NUM_CONTACORRENTE,
    DIG_CONTACORRENTE,
    LINHA_DIGITAVEL,
    CODIGO_BARRAS,
    CODIGO_CARTEIRA,
    CIDIGO_CEDENTE,
    CNPJ_CEDENTE,
    NOME_CEDENTE,
    DT_DOCUMENTO,
    LOCALIDADE,
    ESPECIE,
    ACEITE,
    USO_BANCO,
    MOEDA,
    INSTRUCOES,
    CODIGO_COMPENSACAO,
    NOSSO_NUMEROFORMATADO,
    NUMERO_DOCUMENTO,
    STATUS_PARCELA,
    DT_PAGAMENTO,
    VALOR_PAGO
)
SELECT 
    aux.CONTRATO_FIN,                                
    p.ID_PARCELAPROMESSA,                                        
    p.ID_PROMESSA,
    p.NUM_PARCELA,
    p.TIPO_PAGAMENTO,
    p.DT_VENCIMENTO,
    p.DT_EXPIRACAOPARCELA,
    p.VALOR_PARCELA,
    p.NOSSO_NUMERO,
    p.NUM_BANCO,
    p.NUM_AGENCIA,
    p.DIG_AGENCIA,
    p.NUM_CONTACORRENTE,
    p.DIG_CONTACORRENTE,
    p.LINHA_DIGITAVEL,
    p.CODIGO_BARRAS,
    p.CODIGO_CARTEIRA,
    p.CIDIGO_CEDENTE,
    p.CNPJ_CEDENTE,
    p.NOME_CEDENTE,
    p.DT_DOCUMENTO,
    p.LOCALIDADE,
    p.ESPECIE,
    p.ACEITE,
    p.USO_BANCO,
    p.MOEDA,
    p.INSTRUCOES,
    p.CODIGO_COMPENSACAO,
    p.NOSSO_NUMEROFORMATADO,
    p.NUMERO_DOCUMENTO,
    p.STATUS_PARCELA,
    p.DT_PAGAMENTO,
    p.VALOR_PAGO
FROM AUX_SANTANDERPIC_PROMESSAS aux
INNER JOIN AUX_SANTANDERPIC_PARCPROMESSAS p
    ON aux.ID_PROMESSA = p.ID_PROMESSA
WHERE NOT EXISTS (
    SELECT 1 
    FROM AUX_SANTANDERPIC_PARCPROMESSAS pp
    WHERE pp.CONTRATO_FIN = aux.CONTRATO_FIN
      AND pp.ID_PROMESSA = aux.ID_PROMESSA
)


UPDATE A
	SET A.NNUMEROBOLETO_ACOP = B.ID_PARCELAPROMESSA
FROM
	CAD_ACOP AS A
	INNER JOIN AUX_SANTANDERPIC_PARCPROMESSAS AS B ON A.CONTRATO_FIN = B.CONTRATO_FIN AND A.PARCELA_ACOP = B.NUM_PARCELA
	INNER JOIN CAD_ACO AS C ON CAST(B.ID_PROMESSA AS VARCHAR) = CAST('0'+C.NUMACORDO_ACO AS VARCHAR) 
WHERE
	A.NNUMEROBOLETO_ACOP IS NULL