USE SRC_RETURN
SELECT COUNT(1) FROM TBL_LOG_APITASKEN WHERE DATA < DATEADD(MONTH, -6, GETDATE())
SELECT COUNT(1) FROM TBL_LOG_HEADER_RESPOSTA_APITASKEN

USE SRC_RETURN_JURIDICO
SELECT COUNT(1) FROM TBL_LOG_APITASKEN WHERE DATA < DATEADD(MONTH, -6, GETDATE()) --36.533
SELECT COUNT(1) FROM TBL_LOG_HEADER_RESPOSTA_APITASKEN --397.938

USE SRC_MANUTENCAO
SELECT COUNT(1) FROM SDM_HISTORICO_ACIONAMENTO --528.973.278
SELECT COUNT(1) FROM TBL_LOG_APITASKEN WHERE DATA < DATEADD(MONTH, -6, GETDATE()) --22.489
